// ZSA Oryx API client — generated by secret-sauce
// Direct GraphQL access to the ZSA keyboard configurator at oryx.zsa.io
//
// Usage:
//   oryx whoami                                    Current user
//   oryx layouts                                   List your layouts
//   oryx search [--tags=t1,t2] [--geom=voyager] [--start=0] [--limit=20]
//                                                  Search public layouts
//   oryx tags [--filter=foo] [--limit=50]          List available tags
//
//   oryx get <hashId> [--rev=latest] [--geom=...] List one layout (summary)
//   oryx full <hashId> [--rev=latest] [--geom=...] Full layout JSON (layers+combos+keys)
//   oryx layers <hashId> [--rev=latest]            Show layer summary
//   oryx keys <hashId> --layer=N [--rev=latest]    Show key codes for a layer (compact)
//   oryx combos <hashId> [--rev=latest]            Show combos summary
//   oryx download <hashId> [--rev=latest] [--type=hex|zip] [-o file]
//                                                  Download .bin/.zip firmware bundle
//
//   oryx fork <revisionHashId>                     Fork a revision (creates editable copy)
//   oryx clone <parentHashId> --title=...          Create a new layout from a parent
//   oryx privacy <hashId> public|private           Toggle layout privacy
//   oryx title <hashId> <new-title>                Rename layout
//   oryx layout-tags <hashId> <tagId1,tagId2,...>  Set tags on layout
//   oryx compile <revisionHashId>                  Trigger firmware compile
//   oryx delete-layout <hashId>                    Delete a layout
//
//   oryx layer-update <layerHashId> [--title=...] [--color=#hex]
//   oryx layer-color <layerHashId> <#hex>
//   oryx layer-delete <layerHashId>
//   oryx layer-restore <layerHashId>
//   oryx layer-add <revisionHashId> --pos=N [--title=...]
//
//   oryx key-update <layerHashId> --pos=N --json=<keydata>
//                                                  Update a single key. <keydata> is the Key JSON object.
//   oryx swap-keys <srcLayerId> <dstLayerId> [--src-pos=A] [--dst-pos=B]
//
//   oryx combo-add <revisionHashId> --layer=I --indices=1,2,3 --name=Foo --trigger=<json>
//   oryx combo-delete <revisionHashId> --idx=N
//
//   oryx gql <query> [--vars=<json>]               Run an arbitrary GraphQL query
//   oryx schema [--type=Query|Mutation|<name>]     Print schema fields
//
//   oryx help                                      Show this help
//
// Auth:
//   Reads JWT from /workspace/skills/oryx/.config (key: jwtToken) if present.
//   Otherwise pulls localStorage `jwtToken` from any open zsa.io browser tab.
//   On 401, tells you to log into oryx.zsa.io in your browser, then retry.

const CONFIG_FILE = '/workspace/skills/oryx/.config';
const ENDPOINT    = 'https://oryx.zsa.io/graphql';
const ZSA_DOMAIN  = 'zsa.io';

// ─── Argument Parsing ─────────────────────────────────────────────────────

const rawArgs = process.argv.slice(2);
const cmd = rawArgs[0] || '';
const positional = [];
const flags = {};

for (let i = 1; i < rawArgs.length; i++) {
  const a = rawArgs[i];
  if (a === '-o') { flags.o = rawArgs[++i]; continue; }
  if (a.startsWith('--')) {
    const eq = a.indexOf('=');
    if (eq !== -1) {
      flags[a.slice(2, eq)] = a.slice(eq + 1);
    } else {
      const k = a.slice(2);
      if (i + 1 < rawArgs.length && !rawArgs[i + 1].startsWith('--')) {
        flags[k] = rawArgs[++i];
      } else {
        flags[k] = true;
      }
    }
  } else {
    positional.push(a);
  }
}

// ─── Auth ─────────────────────────────────────────────────────────────────

async function loadConfig() {
  try {
    const r = await exec(`cat ${CONFIG_FILE}`);
    if (r.exitCode === 0 && r.stdout.trim()) return JSON.parse(r.stdout.trim());
  } catch (_) {}
  return {};
}

async function findZsaTabs() {
  const r = await exec('playwright-cli tab-list');
  if (r.exitCode !== 0) return [];
  const tabs = [];
  for (const line of r.stdout.split('\n')) {
    const m = line.match(/\[([A-F0-9]+)\]\s+(https?:\/\/[^\s"]*)/);
    if (m && /\.?zsa\.io/i.test(m[2])) tabs.push({ id: m[1], url: m[2] });
  }
  // Prefer configure.zsa.io and oryx.zsa.io (where jwtToken lives)
  tabs.sort((a, b) => {
    const score = u => /(configure|oryx)\.zsa\.io/i.test(u) ? 0 : 1;
    return score(a.url) - score(b.url);
  });
  return tabs;
}

async function getToken() {
  // 1. Config file
  const cfg = await loadConfig();
  if (cfg.jwtToken) return cfg.jwtToken;
  // 2. Try every zsa.io tab in priority order
  const tabs = await findZsaTabs();
  for (const t of tabs) {
    const r = await exec(`playwright-cli localstorage-get jwtToken --tab=${t.id}`);
    if (r.exitCode !== 0) continue;
    const tok = r.stdout.trim().replace(/^"+|"+$/g, '');
    if (tok && tok !== 'null' && tok !== 'undefined') return tok;
  }
  return null;
}

async function authHeaders() {
  const token = await getToken();
  if (!token) {
    console.error('No JWT found. Either:');
    console.error('  1. Log into https://oryx.zsa.io in your browser, then retry, or');
    console.error(`  2. Save a token in ${CONFIG_FILE} as {"jwtToken":"..."}`);
    process.exit(1);
  }
  return {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Authorization': 'Bearer ' + token,
  };
}

// ─── GraphQL ──────────────────────────────────────────────────────────────

async function gql(query, variables) {
  const headers = await authHeaders();
  const r = await fetch(ENDPOINT, {
    method: 'POST',
    headers,
    body: JSON.stringify({ query, variables: variables || {} }),
  });
  if (r.status === 401 || r.status === 403) {
    console.error(`Auth failed (${r.status}). Log into https://oryx.zsa.io in your browser, then retry.`);
    process.exit(1);
  }
  const text = await r.text();
  let body;
  try { body = JSON.parse(text); } catch (_) {
    console.error(`Bad response (${r.status}): ${text.slice(0, 500)}`);
    process.exit(1);
  }
  if (body.errors) {
    console.error('GraphQL error:');
    for (const e of body.errors) console.error('  ' + (e.message || JSON.stringify(e)));
    process.exit(1);
  }
  return body.data;
}

function parseJsonArg(name) {
  const v = flags[name];
  if (!v) return null;
  try { return JSON.parse(v); }
  catch (e) {
    console.error(`--${name} must be valid JSON: ${e.message}`);
    process.exit(1);
  }
}

function out(obj) {
  console.log(JSON.stringify(obj, null, 2));
}

// ─── Read commands ────────────────────────────────────────────────────────

const commands = {

  async whoami() {
    const data = await gql(`{ currentUser { hashId email name admin has2fa pictureUrl } }`);
    out(data.currentUser);
  },

  async layouts() {
    const data = await gql(`{
      myLayouts {
        hashId title geometry privacy createdAt
        revisions { hashId title createdAt model qmkVersion }
      }
    }`);
    out(data.myLayouts);
  },

  async search() {
    const tags = (flags.tags || '').split(',').map(s => s.trim()).filter(Boolean);
    const data = await gql(`
      query ($start: Int!, $limit: Int!, $tags: [String!]!, $geom: String) {
        searchLayouts(start: $start, limit: $limit, tags: $tags, geometry: $geom) {
          totalCount
          layouts {
            hashId title geometry hasTour lastUpdate username
            commitMessage aboutIntro tags
          }
        }
      }`,
      {
        start: parseInt(flags.start || '0', 10),
        limit: parseInt(flags.limit || '20', 10),
        tags,
        geom: flags.geom || null,
      }
    );
    out(data.searchLayouts);
  },

  async tags() {
    const data = await gql(`
      query ($limit: Int, $filter: String) { tags(limit: $limit, filter: $filter) { hashId name } }`,
      { limit: parseInt(flags.limit || '100', 10), filter: flags.filter || null }
    );
    out(data.tags);
  },

  async get() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx get <hashId> [--rev=latest] [--geom=...]'); process.exit(1); }
    const data = await gql(`
      query ($hashId: String!, $rev: String!, $geom: String) {
        layout(hashId: $hashId, revisionId: $rev, geometry: $geom) {
          hashId title geometry privacy createdAt updatedAt
          user { hashId name }
          tags { hashId name }
          revision {
            hashId title model md5 hexUrl zipUrl qmkVersion qmkUptodate hasTour
            layers { hashId title position color builtIn automouse }
          }
        }
      }`,
      { hashId, rev: flags.rev || 'latest', geom: flags.geom || null }
    );
    out(data.layout);
  },

  async full() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx full <hashId> [--rev=latest] [--geom=...]'); process.exit(1); }
    const data = await gql(`
      query ($hashId: String!, $rev: String!, $geom: String) {
        layout(hashId: $hashId, revisionId: $rev, geometry: $geom) {
          hashId title geometry privacy createdAt updatedAt
          tags { hashId name }
          revision {
            hashId title model md5 hexUrl zipUrl qmkVersion qmkUptodate hasTour
            config swatch navigators
            layers { hashId title position color builtIn automouse keys }
            combos { name layerIdx keyIndices trigger }
          }
        }
      }`,
      { hashId, rev: flags.rev || 'latest', geom: flags.geom || null }
    );
    out(data.layout);
  },

  async layers() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx layers <hashId> [--rev=latest]'); process.exit(1); }
    const data = await gql(`
      query ($hashId: String!, $rev: String!) {
        layout(hashId: $hashId, revisionId: $rev) {
          revision { layers { hashId position title color builtIn automouse } }
        }
      }`,
      { hashId, rev: flags.rev || 'latest' }
    );
    out(data.layout.revision.layers);
  },

  async keys() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx keys <hashId> --layer=N [--rev=latest]'); process.exit(1); }
    if (flags.layer === undefined) { console.error('--layer=N required'); process.exit(1); }
    const layerIdx = parseInt(flags.layer, 10);
    const data = await gql(`
      query ($hashId: String!, $rev: String!) {
        layout(hashId: $hashId, revisionId: $rev) {
          revision { layers { position title keys } }
        }
      }`,
      { hashId, rev: flags.rev || 'latest' }
    );
    const layer = data.layout.revision.layers.find(l => l.position === layerIdx);
    if (!layer) { console.error(`No layer at position ${layerIdx}`); process.exit(1); }
    if (flags.raw) { out(layer.keys); return; }
    // Compact view: position + tap code + hold + double-tap
    const compact = layer.keys.map((k, i) => {
      const codes = [];
      if (k.tap?.code) codes.push('tap=' + k.tap.code + (k.tap.modifiers ? '/' + JSON.stringify(k.tap.modifiers) : ''));
      if (k.hold?.code) codes.push('hold=' + k.hold.code);
      if (k.tapHold?.code) codes.push('tapHold=' + k.tapHold.code);
      if (k.doubleTap?.code) codes.push('dt=' + k.doubleTap.code);
      if (k.customLabel) codes.push('label="' + k.customLabel + '"');
      if (k.glowColor) codes.push('glow=' + k.glowColor);
      return { i, ...(codes.length ? { code: codes.join(' ') } : { code: '(empty)' }) };
    });
    out({ layer: layerIdx, title: layer.title, count: compact.length, keys: compact });
  },

  async combos() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx combos <hashId> [--rev=latest]'); process.exit(1); }
    const data = await gql(`
      query ($hashId: String!, $rev: String!) {
        layout(hashId: $hashId, revisionId: $rev) {
          revision { combos { name layerIdx keyIndices trigger } }
        }
      }`,
      { hashId, rev: flags.rev || 'latest' }
    );
    out(data.layout.revision.combos);
  },

  async download() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx download <hashId> [--type=hex|zip] [-o file]'); process.exit(1); }
    const type = (flags.type || 'hex').toLowerCase();
    const data = await gql(`
      query ($hashId: String!, $rev: String!) {
        layout(hashId: $hashId, revisionId: $rev) {
          title geometry
          revision { hashId hexUrl zipUrl }
        }
      }`,
      { hashId, rev: flags.rev || 'latest' }
    );
    const url = type === 'zip' ? data.layout.revision.zipUrl : data.layout.revision.hexUrl;
    if (!url) { console.error(`No ${type}Url available — try compiling first: oryx compile ${data.layout.revision.hashId}`); process.exit(1); }
    const outPath = flags.o || `./zsa_${data.layout.geometry}_${hashId}_${data.layout.revision.hashId}.${type === 'zip' ? 'zip' : 'bin'}`;
    // Use curl for binary download — SLICC jsh runtime doesn't have node fs.
    const r = await exec(`curl -sSL -o '${outPath.replace(/'/g, "'\\''")}' '${url.replace(/'/g, "'\\''")}'`);
    if (r.exitCode !== 0) { console.error('Download failed: ' + (r.stderr || r.stdout)); process.exit(1); }
    const stat = await exec(`wc -c < '${outPath.replace(/'/g, "'\\''")}'`);
    const size = parseInt((stat.stdout || '0').trim(), 10);
    console.log(`Downloaded ${size} bytes -> ${outPath}`);
  },

  // ─── Mutations ──────────────────────────────────────────────────────────

  async fork() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx fork <revisionHashId>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!) {
        forkRevision(hashId: $hashId) {
          revision { hashId title }
          errors
        }
      }`, { hashId });
    out(data.forkRevision);
  },

  async clone() {
    const parentHashId = positional[0];
    const title = flags.title;
    if (!parentHashId || !title) { console.error('Usage: oryx clone <parentHashId> --title=<name> [--geom=voyager]'); process.exit(1); }
    // parent here is parentHashId of revision per createLayout signature
    const data = await gql(`
      mutation ($title: String!, $rev: String!, $parent: String, $geom: String) {
        createLayout(title: $title, revisionHashId: $rev, parentHashId: $parent, geometry: $geom) {
          layout { hashId title }
          errors
        }
      }`,
      { title, rev: parentHashId, parent: parentHashId, geom: flags.geom || null }
    );
    out(data.createLayout);
  },

  async privacy() {
    const hashId = positional[0];
    const mode = positional[1];
    if (!hashId || !['public', 'private'].includes(mode)) {
      console.error('Usage: oryx privacy <hashId> public|private'); process.exit(1);
    }
    const privacy = mode === 'private';
    const data = await gql(`
      mutation ($hashId: String!, $privacy: Boolean!) {
        updateLayoutPrivacy(hashId: $hashId, privacy: $privacy) {
          layout { hashId privacy }
          errors
        }
      }`, { hashId, privacy });
    out(data.updateLayoutPrivacy);
  },

  async title() {
    const hashId = positional[0];
    const newTitle = positional.slice(1).join(' ');
    if (!hashId || !newTitle) { console.error('Usage: oryx title <hashId> <new-title>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!, $title: String!) {
        updateLayoutTitle(hashId: $hashId, title: $title) {
          layout { hashId title }
          errors
        }
      }`, { hashId, title: newTitle });
    out(data.updateLayoutTitle);
  },

  async 'layout-tags'() {
    const hashId = positional[0];
    const tagIds = (positional[1] || '').split(',').map(s => s.trim()).filter(Boolean);
    if (!hashId) { console.error('Usage: oryx layout-tags <hashId> <tagId1,tagId2,...>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!, $tagIds: [String!]!) {
        updateLayoutTags(hashId: $hashId, tagIds: $tagIds) {
          layout { hashId tags { hashId name } }
          errors
        }
      }`, { hashId, tagIds });
    out(data.updateLayoutTags);
  },

  async compile() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx compile <revisionHashId>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!) {
        compileRevision(hashId: $hashId) {
          revision { hashId hexUrl zipUrl md5 }
          errors
        }
      }`, { hashId });
    out(data.compileRevision);
  },

  async 'delete-layout'() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx delete-layout <hashId>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!) {
        deleteLayout(hashId: $hashId) { errors }
      }`, { hashId });
    out(data.deleteLayout);
  },

  // ─── Layer mutations ────────────────────────────────────────────────────

  async 'layer-update'() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx layer-update <layerHashId> [--title=...] [--color=#hex] [--pos=N]'); process.exit(1); }
    const vars = { hashId };
    let q = `mutation ($hashId: String!`;
    let args = `hashId: $hashId`;
    if (flags.title)  { q += `, $title: String`;  args += `, title: $title`;     vars.title = flags.title; }
    if (flags.color)  { q += `, $color: String`;  args += `, color: $color`;     vars.color = flags.color; }
    if (flags.pos !== undefined) { q += `, $pos: Int`; args += `, position: $pos`; vars.pos = parseInt(flags.pos, 10); }
    q += `) { updateLayer(${args}) { layer { hashId title color position } errors } }`;
    const data = await gql(q, vars);
    out(data.updateLayer);
  },

  async 'layer-color'() {
    const hashId = positional[0];
    const color = positional[1];
    if (!hashId || !color) { console.error('Usage: oryx layer-color <layerHashId> <#hex>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!, $color: String) {
        updateLayerColor(hashId: $hashId, color: $color) {
          layer { hashId color }
          errors
        }
      }`, { hashId, color });
    out(data.updateLayerColor);
  },

  async 'layer-delete'() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx layer-delete <layerHashId>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!) { deleteLayer(hashId: $hashId) { errors } }`, { hashId });
    out(data.deleteLayer);
  },

  async 'layer-restore'() {
    const hashId = positional[0];
    if (!hashId) { console.error('Usage: oryx layer-restore <layerHashId>'); process.exit(1); }
    const data = await gql(`
      mutation ($hashId: String!) { restoreLayer(layerHashId: $hashId) { hashId title position } }`, { hashId });
    out(data.restoreLayer);
  },

  async 'layer-add'() {
    const revisionHashId = positional[0];
    if (!revisionHashId || flags.pos === undefined) {
      console.error('Usage: oryx layer-add <revisionHashId> --pos=N [--title=...] [--keys=<json-array>]'); process.exit(1);
    }
    const newKeys = flags.keys ? parseJsonArg('keys') : [];
    const data = await gql(`
      mutation ($rev: String!, $newKeys: Json!, $position: Int!, $title: String) {
        createLayer(revisionHashId: $rev, newKeys: $newKeys, position: $position, title: $title) {
          layer { hashId title position }
          errors
        }
      }`,
      { rev: revisionHashId, newKeys, position: parseInt(flags.pos, 10), title: flags.title || null }
    );
    out(data.createLayer);
  },

  // ─── Key mutations ──────────────────────────────────────────────────────

  async 'key-update'() {
    const hashId = positional[0];
    if (!hashId || flags.pos === undefined || !flags.json) {
      console.error('Usage: oryx key-update <layerHashId> --pos=N --json=<keydata>'); process.exit(1);
    }
    const keyData = parseJsonArg('json');
    const data = await gql(`
      mutation ($hashId: String!, $keyData: Json!, $position: Int!) {
        updateKey(hashId: $hashId, keyData: $keyData, position: $position) {
          layer { hashId position }
          errors
        }
      }`,
      { hashId, keyData, position: parseInt(flags.pos, 10) }
    );
    out(data.updateKey);
  },

  async 'swap-keys'() {
    const src = positional[0];
    const dst = positional[1];
    if (!src || !dst) { console.error('Usage: oryx swap-keys <srcLayerId> <dstLayerId> [--src-pos=A] [--dst-pos=B]'); process.exit(1); }
    const vars = { src, dst };
    let argList = `targetLayerId: $dst, sourceLayerId: $src`;
    let argDecl = `$dst: String!, $src: String!`;
    if (flags['src-pos'] !== undefined) { argDecl += `, $sp: Int`; argList += `, sourcePosition: $sp`; vars.sp = parseInt(flags['src-pos'], 10); }
    if (flags['dst-pos'] !== undefined) { argDecl += `, $tp: Int`; argList += `, targetPosition: $tp`; vars.tp = parseInt(flags['dst-pos'], 10); }
    const data = await gql(`
      mutation (${argDecl}) {
        swapKeys(${argList}) { errors }
      }`, vars);
    out(data.swapKeys);
  },

  // ─── Combo mutations ────────────────────────────────────────────────────

  async 'combo-add'() {
    const revisionHashId = positional[0];
    if (!revisionHashId || flags.layer === undefined || !flags.indices || !flags.name || !flags.trigger) {
      console.error('Usage: oryx combo-add <revisionHashId> --layer=I --indices=1,2,3 --name=Foo --trigger=<json>'); process.exit(1);
    }
    const trigger = parseJsonArg('trigger');
    const indices = String(flags.indices).split(',').map(s => parseInt(s.trim(), 10));
    const data = await gql(`
      mutation ($rev: String!, $name: String!, $layerIdx: Int!, $keyIndices: [Int!]!, $trigger: Json!) {
        upsertCombo(revisionHashId: $rev, name: $name, layerIdx: $layerIdx, keyIndices: $keyIndices, trigger: $trigger) {
          combo { name layerIdx keyIndices }
          errors
        }
      }`,
      { rev: revisionHashId, name: flags.name, layerIdx: parseInt(flags.layer, 10), keyIndices: indices, trigger }
    );
    out(data.upsertCombo);
  },

  async 'combo-delete'() {
    const revisionHashId = positional[0];
    if (!revisionHashId || flags.idx === undefined) {
      console.error('Usage: oryx combo-delete <revisionHashId> --idx=N'); process.exit(1);
    }
    const data = await gql(`
      mutation ($rev: String!, $idx: Int!) {
        deleteCombo(revisionHashId: $rev, comboIdx: $idx) { errors }
      }`,
      { rev: revisionHashId, idx: parseInt(flags.idx, 10) }
    );
    out(data.deleteCombo);
  },

  // ─── Escape hatches ─────────────────────────────────────────────────────

  async gql() {
    const query = positional[0];
    if (!query) { console.error('Usage: oryx gql <query> [--vars=<json>]'); process.exit(1); }
    const vars = flags.vars ? parseJsonArg('vars') : {};
    const data = await gql(query, vars);
    out(data);
  },

  async schema() {
    const wantedType = flags.type || 'Query';
    const introspect = `
      query ($t: String!) {
        __type(name: $t) {
          name kind
          fields { name args { name type { kind name ofType { kind name ofType { kind name } } } } type { kind name ofType { kind name ofType { kind name } } } }
          inputFields { name type { kind name ofType { kind name ofType { kind name } } } }
          enumValues { name }
        }
      }`;
    const data = await gql(introspect, { t: wantedType });
    function typeRef(t) {
      if (!t) return '';
      if (t.kind === 'NON_NULL') return typeRef(t.ofType) + '!';
      if (t.kind === 'LIST') return '[' + typeRef(t.ofType) + ']';
      return t.name;
    }
    const tt = data.__type;
    if (!tt) { console.error(`Type not found: ${wantedType}`); process.exit(1); }
    console.log(`# ${tt.kind} ${tt.name}`);
    if (tt.fields) for (const f of tt.fields) {
      const args = (f.args || []).map(a => a.name + ':' + typeRef(a.type)).join(', ');
      console.log('  ' + f.name + (args ? '(' + args + ')' : '') + ': ' + typeRef(f.type));
    }
    if (tt.inputFields) for (const f of tt.inputFields) console.log('  ' + f.name + ': ' + typeRef(f.type));
    if (tt.enumValues) for (const v of tt.enumValues) console.log('  ' + v.name);
  },

  async help() {
    const r = await exec('cat /workspace/skills/oryx/scripts/oryx.jsh');
    const src = r.exitCode === 0 ? r.stdout : '';
    const lines = src.split('\n');
    const helpLines = [];
    for (const l of lines) {
      if (!l.startsWith('//')) {
        if (helpLines.length) break;
        else continue;
      }
      helpLines.push(l.replace(/^\/\/ ?/, ''));
    }
    console.log(helpLines.join('\n'));
  },
};

// ─── Dispatch ─────────────────────────────────────────────────────────────

if (!cmd || cmd === '-h' || cmd === '--help') { await commands.help(); process.exit(0); }
if (!commands[cmd]) {
  console.error('Unknown command: ' + cmd);
  console.error('Run `oryx help` for usage.');
  process.exit(1);
}
await commands[cmd]();
