// build.mjs — bundle xlsx.src.js -> xlsx.jsh (SheetJS rolled in).
//
// Run locally or in CI:  npm install && npm run build
//
// The shipped skill entrypoint is the bundled `xlsx.jsh`; `xlsx.src.js` is the
// readable source. Installing the skill (`upskill ai-ecoverse/skills --skill xlsx`)
// ships the committed `xlsx.jsh` and requires NO build step — this script only
// regenerates that artifact when the source changes.
//
// Why these options:
//  • platform:'node'  — keeps Node builtins (`fs`, `stream`) as runtime
//    `require(...)` calls. At the SLICC jsh runtime `require('fs')` resolves to
//    the VFS bridge (sync methods). SheetJS only touches `stream` on code paths
//    this CLI never exercises (it passes in-memory buffers everywhere).
//  • external fs/node:fs/stream — never inline the runtime-provided modules.
//  • format:'cjs' + minify — single self-contained CommonJS file.
//
// NOTE: inside the SLICC worker the esbuild-wasm *Node build API* fails on a
// missing `tty` (ai-ecoverse/slicc#1631) and the `esbuild` CLI wrapper lacks
// --external/--platform (ai-ecoverse/slicc#1632). This script therefore targets
// a real Node toolchain (local dev / GitHub Actions), where the esbuild npm
// package works normally. To rebuild from *within* SLICC, use the CLI fallback:
//   esbuild xlsx.src.js --bundle --format=cjs --target=node18 --minify --outfile=xlsx.jsh
// (the wrapper's implicit defaults keep fs/stream external).

import * as esbuild from 'esbuild';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));

await esbuild.build({
  entryPoints: [join(here, 'xlsx.src.js')],
  outfile: join(here, 'xlsx.jsh'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: ['node18'],
  minify: true,
  legalComments: 'none',
  external: ['fs', 'node:fs', 'stream', 'node:stream'],
  banner: {
    js: '// GENERATED by build.mjs from xlsx.src.js — do not edit by hand. Bundles SheetJS (xlsx).',
  },
});

console.log('built xlsx.jsh');
