// build.mjs — bundle pandoc-wasm/src/core.js -> pandoc-core.cjs
//
// Run locally or in CI:  npm install && npm run build
//
// Never require('pandoc-wasm') at runtime — the package entry uses top-level
// await and breaks the realm CJS transpiler. Ship this pre-bundled core and
// load pandoc.wasm bytes separately via fs.readFileBinary.
//
// NOTE: esbuild full bundle with embedded wasm URL fails in SLICC (relative
// fetch). Bundle glue only; WASM is loaded from node_modules at runtime.

import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));

await esbuild.build({
  entryPoints: [join(here, 'node_modules/pandoc-wasm/src/core.js')],
  outfile: join(here, 'pandoc-core.cjs'),
  bundle: true,
  platform: 'node',
  format: 'cjs',
  target: ['node18'],
  minify: true,
  legalComments: 'none',
  banner: {
    js: '// GENERATED by build.mjs from pandoc-wasm/src/core.js — do not edit by hand.',
  },
});

console.log('built pandoc-core.cjs');
