// Concur API client — generated by secret-sauce
//
// Concur uses cookie-based auth on .concursolutions.com. Browser fetch from
// SLICC's localhost origin can't carry that cookie, so every request runs
// inside a page-context fetch via `sliccy:browser` against a tab already
// loaded on us2.concursolutions.com.

const exec = require('sliccy:exec');
const browser = require('sliccy:browser');

const APP_DOMAIN = 'concursolutions.com';
const HOME_URL   = 'https://us2.concursolutions.com/home';
const HOST_WEB   = 'https://us2.concursolutions.com';
const HOST_API   = 'https://www-us2.api.concursolutions.com';
// Resolve operations + session paths relative to this script so the skill
// works regardless of where it is installed (e.g. /workspace/skills/concur,
// /shared/skills/concur, or any other prefix).
const _SCRIPT_DIR = process.argv[1].substring(0, process.argv[1].lastIndexOf('/'));
const SKILL_DIR   = _SCRIPT_DIR.replace(/\/scripts$/, '');
const OPS_DIR     = `${SKILL_DIR}/references/operations`;
const PERSIST     = `${SKILL_DIR}/.session.json`;

// ----------------- tab management -----------------

let _tab = null;

async function ensureTab() {
  if (_tab) return _tab;
  const existing = await browser.findTab({ urlMatch: /concursolutions\.com/ });
  if (existing) { _tab = existing; return _tab; }
  console.error('No Concur tab open — opening one. This may require login.');
  _tab = await browser.ensureTab(HOME_URL, { matchUrl: /concursolutions\.com/ });
  await new Promise(r => setTimeout(r, 4000));
  return _tab;
}

// ----------------- session info -----------------

let _userId = null;

async function getUserId() {
  if (_userId) return _userId;
  // Try cached session file
  try {
    const cache = JSON.parse(await readFile(PERSIST));
    if (cache.userId) { _userId = cache.userId; return _userId; }
  } catch {}
  // Discover via GetUserPermissions (no variables)
  const data = await graphql('spend', {
    operationName: 'GetUserPermissions',
    query: await loadOp('GetUserPermissions'),
    variables: {},
  });
  const uid = data?.userPermissions?.userId;
  if (!uid) {
    console.error('Could not determine userId from GetUserPermissions response:', JSON.stringify(data).slice(0, 500));
    process.exit(1);
  }
  _userId = uid;
  try { await writeFile(PERSIST, JSON.stringify({ userId: uid }, null, 2)); } catch {}
  return uid;
}

async function readFile(p) {
  const r = await exec(`cat "${p}"`);
  if (r.exitCode !== 0) throw new Error(`read failed: ${p}`);
  return r.stdout;
}

async function writeFile(p, s) {
  // Heredoc has an effective argv-size cap (~1 MB on this runtime), so for
  // large content we base64-pipe it through stdin instead. Encoding inflates
  // by ~33% so we keep a margin. Use /shared for the temp file so a
  // sibling Playwright process running in a different container/namespace
  // can still see it if the caller later moves it under /shared.
  const tmp = `/shared/.concur-write-${Date.now()}.tmp`;
  if (s.length < 600_000) {
    await exec(`cat > "${tmp}" <<'____CONCUR_EOF____'\n${s}\n____CONCUR_EOF____`);
  } else {
    // Chunk-stream via base64 so the shell never sees the raw payload as argv.
    const chunkSize = 400_000; // ~400 KB raw → ~540 KB base64 per chunk
    await exec(`: > "${tmp}"`);
    // Build the base64 string in small sub-chunks to avoid spreading a huge
    // typed-array into String.fromCharCode (which hits arg-limit / is slow).
    const encoder = new TextEncoder();
    const subChunk = 8_192;
    for (let i = 0; i < s.length; i += chunkSize) {
      const chunk = s.slice(i, i + chunkSize);
      const bytes = encoder.encode(chunk);
      let bin = '';
      for (let j = 0; j < bytes.length; j += subChunk) {
        bin += String.fromCharCode.apply(null, bytes.subarray(j, j + subChunk));
      }
      const b64 = btoa(bin);
      // Single arg of ~540 KB is safe (well below 1 MB cap).
      const r = await exec(`printf %s '${b64}' | base64 -d >> "${tmp}"`);
      if (r.exitCode !== 0) throw new Error(`writeFile chunk failed at offset ${i}: ${r.stderr}`);
    }
  }
  await exec(`mkdir -p "$(dirname "${p}")" && mv "${tmp}" "${p}"`);
}

async function loadOp(name) {
  return readFile(`${OPS_DIR}/${name}.graphql`);
}

// ----------------- page-context fetch -----------------
//
// Requests run inside the Concur tab's page context via `sliccy:browser`'s
// browser.fetch(). The page context handles cookies, origin, and any
// required browser headers automatically (credentials: 'include' is the
// browser.fetch default).

async function pageFetch(url, options = {}) {
  const tab = await ensureTab();
  const method = options.method || 'GET';
  const headers = { 'Accept': 'application/json', ...(options.headers || {}) };
  const body = options.body ?? null;
  if (body !== null && body !== undefined && method !== 'GET') {
    headers['Content-Type'] = headers['Content-Type'] || 'application/json';
  }
  let resp;
  try {
    resp = await browser.fetch(tab, url, { method, headers, body });
  } catch (e) {
    console.error('Network error:', e?.message || e);
    process.exit(1);
  }
  if (!resp.ok) {
    if (resp.status === 401 || resp.status === 403) {
      console.error(`Auth failed (${resp.status}). Open ${HOST_WEB} in your browser, log in, and retry.`);
    } else {
      const bodyStr = typeof resp.body === 'string' ? resp.body : JSON.stringify(resp.body);
      console.error(`HTTP ${resp.status}:`, (bodyStr || '').slice(0, 4000));
    }
    process.exit(1);
  }
  return resp.body;
}

// ----------------- GraphQL helpers -----------------

async function graphql(surface, body) {
  const url = surface === 'cds'
    ? `${HOST_API}/cds/graphql`
    : `${HOST_API}/spend-graphql/graphql`;
  const correlationId = crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
  const result = await pageFetch(url, {
    method: 'POST',
    body,
    headers: {
      'concur-correlationId': correlationId,
      'concur-correlationid': correlationId,
    },
  });
  if (result?.errors) {
    console.error('GraphQL errors:', JSON.stringify(result.errors, null, 2));
    process.exit(1);
  }
  return result?.data ?? result;
}

async function callOp(opName, variables = {}, surface = 'spend') {
  const query = await loadOp(opName);
  return graphql(surface, { operationName: opName, query, variables });
}

// Lookup a single report's status in the user's report list.
// Returns { reportId, name, approvalStatus, approvalStatusId, isLocked, ... }
// where isLocked === true means the report rejects mutations (Approved,
// Pending Audit Review, Submitted, Paid, etc.). Throws if the report is
// not found in the user's active list.
async function getReportStatus(reportId) {
  const userId = await getUserId();
  const data = await callOp('GetReportsForUser', {
    isAiUser: false, filterByStatus: 'ACTIVE', dateRange: null,
    paging: { page: 1, size: 200 }, sortBy: null, sortDirection: null,
    userId, contextRole: 'TRAVELER',
  });
  const list = data?.employee?.reportsForUser?.list || [];
  const r = list.find((x) => x.reportId === reportId);
  if (!r) {
    // Try the SUBMITTED filter as a fallback so we can surface "submitted but
    // not approved" reports rather than just claiming they don't exist.
    const subm = await callOp('GetReportsForUser', {
      isAiUser: false, filterByStatus: 'SUBMITTED', dateRange: null,
      paging: { page: 1, size: 200 }, sortBy: null, sortDirection: null,
      userId, contextRole: 'TRAVELER',
    });
    const r2 = (subm?.employee?.reportsForUser?.list || []).find((x) => x.reportId === reportId);
    if (r2) return { ...r2, isLocked: true };
    throw new Error(`Report ${reportId} not found in your active or submitted lists.`);
  }
  // "Not Submitted" / "Sent Back to Employee" / "Recalled" are mutable.
  // Anything else (Pending Approval, Approved, Pending Audit Review, Paid, …)
  // rejects mutations on Adobe's tenant.
  const mutableStatuses = new Set(['Not Submitted', 'Sent Back to Employee', 'Recalled']);
  return { ...r, isLocked: !mutableStatuses.has(r.approvalStatus) };
}

// Throw a friendly Error if the report is locked.
async function assertReportMutable(reportId, action = 'mutate') {
  const r = await getReportStatus(reportId);
  if (r.isLocked) {
    throw new Error(
      `Report ${reportId} ("${r.name}") is "${r.approvalStatus}" and cannot ${action}. ` +
      `Only "Not Submitted", "Sent Back to Employee", or "Recalled" reports accept mutations.`
    );
  }
  return r;
}

// ----------------- itemize helpers -----------------

// Resolve the parent expense entry: lets us validate the itemization total
// matches the entry amount, and surfaces the currency / parent expenseId.
async function getEntrySummary(reportId, expenseId) {
  // Pull the report's full entries list and pick the one we need. We avoid
  // GetExistingExpenseEntry because pageFetch process.exit(1)s on HTTP errors
  // and that op rejects partially-loaded entries with a generic 400.
  const userId = await getUserId();
  const list = await callOp('GetReportExceptionsAndEntries', {
    reportId, userId, contextRole: 'TRAVELER',
    expenseListDetailFormId: null, includeDetailItemizations: true,
  });
  const entries = list?.reportEntriesDetails?.entries
              || list?.employee?.expenseReport?.reportEntryDetails
              || [];
  const found = entries.find((e) => e.expenseId === expenseId)
            || entries.find((e) => e.summary?.id === expenseId);
  if (!found) return null;
  const s = found.summary || {};
  return {
    id: s.id || expenseId,
    expenseId: s.id || expenseId,
    transactionAmount: s.transactionAmount,
    transactionDate: s.transactionDate,
    expenseTypeId: s.expenseType?.id,
    expenseType: s.expenseType,
    vendor: s.vendor,
    location: s.location,
  };
}

// List itemization expense types available for an entry. Returns a
// flat array of { id, code, name, parentName, itemizationType }.
async function itemizeTypes(reportId, expenseId) {
  if (!reportId || !expenseId) {
    console.error('Usage: concur itemize types <reportId> <expenseId>');
    process.exit(1);
  }
  const userId = await getUserId();
  const entry = await getEntrySummary(reportId, expenseId);
  const parentTypeId = entry?.expenseTypeId || entry?.expenseType?.id || 'LODNG';
  const data = await callOp('GetNewItemizationExpenseTypesForm', {
    dataContext: { reportId, expenseTypeId: parentTypeId },
    userContext: { userId, contextType: 'TRAVELER' },
  });
  // The form has a "Expense Type" listOptions field (code-based), and the
  // GraphQL also exposes the parent's expenseTypes list under reportDetails;
  // we surface whatever we found.
  const fields = data?.expenseTypesForm?.fields || [];
  const typeField = fields.find((f) => /expense.?type/i.test(f.label) || f.formFieldId === 'ExpKey');
  const opts = typeField?.options || [];
  return {
    parent: { reportId, expenseId, expenseTypeId: parentTypeId },
    count: opts.length,
    types: opts.map((o) => ({ id: o.id, code: o.code, name: o.value })),
  };
}

// Adobe (us2.concursolutions.com) policy 23DB999B33CC4B28B692AB90112EB86F
// requires these "custom" fields on every SaveNewItemization. They're
// listItem ID references whose human meaning lives in Concur's lookup tables.
// Without them the API returns a generic HTTP 400 "An error occurred".
//
// custom8  → Travel-related Y/N flag (always set).
// custom24 → Personal Use flag.
// custom5  → Optional sub-category (left null is fine).
//
// Override these via bill.json customFields if your tenant uses different IDs.
const ADOBE_INTL_POLICY = {
  policyId: '23DB999B33CC4B28B692AB90112EB86F',
  custom8:  { listItemId: '3981FF8FF4CEEC4A9960A22023335A9F', value: '3981FF8FF4CEEC4A9960A22023335A9F' },
  custom24: { listItemId: 'D85857556CF1E24B88AB7B438221B177', value: 'D85857556CF1E24B88AB7B438221B177' },
  custom5:  { listItemId: null, value: null },
  taxRateLocation: 'HOME',
  receiptTypeId: 'R',
};

// Build the SaveNewItemization `fields` payload for an itemization line,
// inheriting locationId / exchangeRate from the parent entry and merging in
// the policy's required custom fields. Bill-level overrides take priority.
function buildItemizationFields(line, parentEntry, currency, overrides = {}) {
  const fields = {
    parentExpenseId: line.parentExpenseId,
    expenseTypeId: line.typeId,
    transactionDate: line.date,
    transactionAmount: { value: line.amount, currencyCode: currency },
    isExpensePartOfTravelAllowance: false,
    isPersonalExpense: false,
    taxRateLocation: overrides.taxRateLocation || ADOBE_INTL_POLICY.taxRateLocation,
    receiptTypeId:   overrides.receiptTypeId   || ADOBE_INTL_POLICY.receiptTypeId,
    custom8:  overrides.custom8  || ADOBE_INTL_POLICY.custom8,
    custom24: overrides.custom24 || ADOBE_INTL_POLICY.custom24,
    custom5:  overrides.custom5  || ADOBE_INTL_POLICY.custom5,
  };
  // Inherit locationId from the parent entry if known, or accept a bill override.
  const locationId = overrides.locationId || parentEntry?.location?.id;
  if (locationId) fields.locationId = locationId;
  // Exchange rate: required by Adobe policy. Inherit from the parent entry's
  // ratio of approvedAmount (EUR home) to transactionAmount (USD/etc.) if we
  // can compute it, otherwise accept an override, otherwise fall back to 1.
  let xr = overrides.exchangeRate;
  if (!xr && parentEntry?.approvedAmount?.value && parentEntry?.transactionAmount?.value) {
    const ratio = parentEntry.approvedAmount.value / parentEntry.transactionAmount.value;
    if (isFinite(ratio) && ratio > 0) {
      xr = { operation: 'MULTIPLY', value: ratio };
    }
  }
  if (xr) fields.exchangeRate = xr;
  if (line.comment) fields.comment = line.comment;
  return fields;
}

// Add one itemization line via SaveNewItemization.
async function itemizeAdd(reportId, parentExpenseId, typeId, amountStr, ...tail) {
  if (!reportId || !parentExpenseId || !typeId || !amountStr) {
    console.error('Usage: concur itemize add <reportId> <parentExpenseId> <typeId> <amount> [date] [comment] [--currency=USD]');
    process.exit(1);
  }
  // The [date] positional is optional. Treat any leading `--flag` as a flag
  // rather than the date so users can omit the date without losing
  // subsequent options (e.g. `... 12.50 --currency=EUR`).
  let dateStr = null;
  const positionals = [];
  const flags = [];
  for (const a of tail) {
    if (typeof a === 'string' && a.startsWith('--')) flags.push(a);
    else positionals.push(a);
  }
  if (positionals.length && /^\d{4}-\d{2}-\d{2}$/.test(positionals[0])) {
    dateStr = positionals.shift();
  }
  const opts = parseFlags(flags, { currency: '', policy: '' });
  const comment = positionals.join(' ') || null;
  const amount = parseFloat(amountStr);
  if (!isFinite(amount) || amount <= 0) {
    console.error(`Invalid amount: ${amountStr}`);
    process.exit(1);
  }
  await assertReportMutable(reportId, 'add itemizations');
  const userId = await getUserId();
  // Resolve the entry so we can default currency / date / policy from it.
  const entry = await getEntrySummary(reportId, parentExpenseId);
  const currency = opts.currency || entry?.transactionAmount?.currencyCode || 'USD';
  const date = dateStr || entry?.transactionDate || new Date().toISOString().slice(0, 10);
  const policyId = opts.policy || entry?.policy?.id || entry?.policyId || ADOBE_INTL_POLICY.policyId;

  const fields = buildItemizationFields(
    { parentExpenseId, typeId, date, amount, comment },
    entry, currency,
  );

  const result = await callOp('SaveNewItemization', {
    taxFields: null,
    shouldIncludeRpeKey: false,
    userId,
    contextRole: 'TRAVELER',
    isTrexEnabled: true,
    expenseListDetailFormId: null,
    reportId,
    fields,
    expenseTypeId: typeId,
    policyId,
  });
  const newId = result?.createExpense?.id || null;
  return { id: newId, ok: !!newId, raw: result };
}

// Direct CreateSame/Different room-rate wrapper.
async function itemizeRoomRate(reportId, expenseId, ratesJson) {
  if (!reportId || !expenseId || !ratesJson) {
    console.error('Usage: concur itemize room-rate <reportId> <expenseId> <rates.json>');
    console.error('rates.json: {"roomRate":160,"taxRate":21.41} OR [{...},{...},…]');
    process.exit(1);
  }
  await assertReportMutable(reportId, 'create room-rate itemizations');
  const userId = await getUserId();
  const txt = await readFile(ratesJson);
  const rates = JSON.parse(txt);
  const isArray = Array.isArray(rates);
  const opName = isArray ? 'CreateDifferentRoomRateMutation' : 'CreateSameRoomRateMutation';
  const result = await callOp(opName, {
    taxFields: null,
    userId,
    contextRole: 'TRAVELER',
    isTrexEnabled: true,
    expenseListDetailFormId: null,
    reportId,
    expenseId,
    roomRateObject: rates,
    roomRateExpenseTypeId: 'LODNG',
  });
  const root = result?.employee?.expenseReport
    || result?.createSameRoomRateItemizations
    || result?.createDifferentRoomRateItemizations
    || null;
  return { mutation: opName, success: root?.status?.success ?? null, root };
}

// Hotel folio itemization: one SaveNewItemization per line (Lodging room
// + Hotel Tax per night, plus any extras). We deliberately avoid the
// CreateSame/Different RoomRate mutations because Adobe's tenant has
// combineRoomRateAndTaxes = "NEVR" and silently rejects them.
async function itemizeHotel(reportId, expenseId, billJson) {
  if (!reportId || !expenseId || !billJson) {
    console.error('Usage: concur itemize hotel <reportId> <expenseId> <bill.json>');
    console.error('bill.json shape:');
    console.error('  { "currency":"USD",');
    console.error('    "nights":[ {"roomRate":160,"roomTax":21.41,"date":"2026-04-19"}, … ],');
    console.error('    "extras":[ {"typeId":"01022","amount":41.95,"date":"2026-04-19","comment":"Resort Fee"}, … ],');
    console.error('    "roomTypeId":"LODNG", "roomTaxTypeId":"LODTX" }');
    process.exit(1);
  }
  await assertReportMutable(reportId, 'itemize this hotel entry');

  const txt = await readFile(billJson);
  const bill = JSON.parse(txt);
  const nights = Array.isArray(bill.nights) ? bill.nights : [];
  const extras = Array.isArray(bill.extras) ? bill.extras : [];
  const roomTypeId    = bill.roomTypeId    || 'LODNG';
  const roomTaxTypeId = bill.roomTaxTypeId || 'LODTX';

  const entry = await getEntrySummary(reportId, expenseId);
  if (!entry) throw new Error(`Entry ${expenseId} on report ${reportId} not found.`);
  const entryTotal = entry?.transactionAmount?.value;
  const currency = bill.currency || entry?.transactionAmount?.currencyCode || 'USD';
  const checkin = bill.checkin || entry?.transactionDate;

  // Compute night dates (one per night, starting at checkin) if not given.
  function addDays(d, n) {
    const dt = new Date(d + 'T00:00:00Z');
    dt.setUTCDate(dt.getUTCDate() + n);
    return dt.toISOString().slice(0, 10);
  }
  const nightLines = nights.flatMap((n, i) => {
    const date = n.date || (checkin ? addDays(checkin, i) : new Date().toISOString().slice(0, 10));
    const out = [];
    if (n.roomRate) out.push({ typeId: roomTypeId,    amount: n.roomRate, date, comment: n.comment || `Room night ${i + 1}` });
    if (n.roomTax)  out.push({ typeId: roomTaxTypeId, amount: n.roomTax,  date, comment: n.taxComment || `Hotel tax night ${i + 1}` });
    return out;
  });
  const allLines = [...nightLines, ...extras.map((e) => ({
    typeId: e.typeId,
    amount: e.amount,
    date: e.date || checkin,
    comment: e.comment,
  }))];

  const sum = allLines.reduce((acc, l) => acc + (l.amount || 0), 0);
  const round = (x) => Math.round(x * 100) / 100;
  if (entryTotal != null && Math.abs(round(sum) - round(entryTotal)) > 0.02) {
    throw new Error(
      `Itemization sum ${round(sum)} ${currency} does not match entry total ` +
      `${round(entryTotal)} ${currency}. Adjust bill.json so the totals match (within $0.02).`
    );
  }

  const userId = await getUserId();
  const policyId = bill.policyId || ADOBE_INTL_POLICY.policyId;
  const overrides = bill.customFields || {};
  const results = [];
  for (let i = 0; i < allLines.length; i++) {
    const l = allLines[i];
    if (!l.typeId || !l.amount) {
      results.push({ idx: i, skipped: true, reason: 'missing typeId or amount', line: l });
      continue;
    }
    const fields = buildItemizationFields(
      { parentExpenseId: expenseId, typeId: l.typeId, date: l.date, amount: l.amount, comment: l.comment },
      entry, currency, overrides,
    );
    const res = await callOp('SaveNewItemization', {
      taxFields: null,
      shouldIncludeRpeKey: false,
      userId,
      contextRole: 'TRAVELER',
      isTrexEnabled: true,
      expenseListDetailFormId: null,
      reportId,
      fields,
      expenseTypeId: l.typeId,
      policyId,
    });
    const newId = res?.createExpense?.id || null;
    results.push({
      idx: i,
      typeId: l.typeId,
      amount: l.amount,
      date: l.date,
      id: newId,
      ok: !!newId,
    });
  }
  return {
    parentExpense: { reportId, expenseId, total: entryTotal, currency },
    summed: round(sum),
    nights: nights.length,
    extras: extras.length,
    lines: allLines.length,
    results,
  };
}

// ----------------- commands -----------------

const commands = {
  async me() {
    const userId = await getUserId();
    const data = await callOp('GetUserPermissions');
    return { userId, ...data.userPermissions };
  },

  async reports(...args) {
    const opts = parseFlags(args, { status: 'ACTIVE', page: '1', size: '100' });
    const userId = await getUserId();
    const data = await callOp('GetReportsForUser', {
      isAiUser: false,
      filterByStatus: opts.status,
      dateRange: null,
      paging: { page: parseInt(opts.page, 10), size: parseInt(opts.size, 10) },
      sortBy: null,
      sortDirection: null,
      userId,
      contextRole: 'TRAVELER',
    });
    return data.employee.reportsForUser;
  },

  async report(reportId) {
    if (!reportId) { console.error('Usage: concur report <reportId>'); process.exit(1); }
    const userId = await getUserId();
    const main = await callOp('GetReportPageData', {
      reportId, userId, contextRole: 'TRAVELER',
      includeCostObjects: true, includeDetailItemizations: true, includeEntries: true,
      includeExceptions: true, includeGroupSettings: true, includePolicy: true,
      includeSiteSettings: true, includeSummary: true, includeWorkflows: true,
      shouldChangeWarningAlertsToInformation: false,
    });
    return main;
  },

  async expenses(reportId) {
    if (!reportId) { console.error('Usage: concur expenses <reportId>'); process.exit(1); }
    const userId = await getUserId();
    const data = await callOp('GetReportExceptionsAndEntries', {
      reportId, userId, contextRole: 'TRAVELER',
      expenseListDetailFormId: null, includeDetailItemizations: true,
    });
    return data;
  },

  async 'available-receipts'() {
    const userId = await getUserId();
    const data = await callOp('GetAvailableReceipts', {
      userId, contextRole: 'TRAVELER', deleteEbunshoFlagEnabled: false,
    });
    return data;
  },

  async smartexpenses(...args) {
    const opts = parseFlags(args, { size: '25', context: 'TRAVELER' });
    const userId = await getUserId();
    return pageFetch(`${HOST_API}/smartexpense/v4/users/${userId}/context/${opts.context}/smartexpenses?size=${opts.size}`);
  },

  // -- mutations --

  async attendees(sub, ...args) {
    if (!sub) {
      console.error('Usage: concur attendees <list|search|book|add|remove> [args]');
      console.error('  list   <reportId> <expenseId>          — attendees on an entry');
      console.error('  search <terms>                          — GraphQL predictive search (entire org)');
      console.error('  book   [--search=<text>] [--max=N]      — your saved attendee book (returns v3 IDs)');
      console.error('  add    <reportId> <expenseId> <attendeeId> [--amount=N] [--count=N]');
      console.error('  remove <associationId>                  — drop one association (use list to get id)');
      process.exit(1);
    }
    const userId = await getUserId();

    if (sub === 'list') {
      const [reportId, expenseId] = args;
      if (!reportId || !expenseId) { console.error('Usage: concur attendees list <reportId> <expenseId>'); process.exit(1); }
      // 1. map hex expenseId -> v3 EntryID via /expense/entries
      const entries = await pageFetch(`${HOST_API}/api/v3.0/expense/entries?reportID=${reportId}&limit=100`);
      const entry = (entries.Items || []).find(e => e.ExpenseID === expenseId);
      if (!entry) { console.error(`No entry ${expenseId} on report ${reportId}`); process.exit(1); }
      const v3EntryID = entry.ID;

      // 2. paginate associations and filter
      const matches = [];
      let url = `${HOST_API}/api/v3.0/expense/entryattendeeassociations?limit=100`;
      let pages = 0;
      while (url && pages < 50) {
        pages++;
        const data = await pageFetch(url);
        for (const it of (data.Items || [])) if (it.EntryID === v3EntryID) matches.push(it);
        url = data.NextPage || null;
      }

      // 3. resolve names
      const out = [];
      for (const m of matches) {
        const a = await pageFetch(`${HOST_API}/api/v3.0/expense/attendees/${encodeURIComponent(m.AttendeeID)}`);
        out.push({
          associationId: m.ID,
          attendeeId: m.AttendeeID,
          firstName: a.FirstName,
          lastName: a.LastName,
          company: a.Company,
          title: a.Title,
          email: a.EmailAddress,
          attendeeType: a.AttendeeTypeName,
          amount: m.Amount,
          count: m.AssociatedAttendeeCount,
        });
      }
      return { entry: { reportId, expenseId, v3EntryID, vendor: entry.VendorDescription, total: entry.TransactionAmount, currency: entry.TransactionCurrencyCode }, attendeeCount: out.length, attendees: out };
    }

    if (sub === 'search') {
      const terms = args.join(' ').trim();
      if (!terms) { console.error('Usage: concur attendees search <terms>'); process.exit(1); }
      const data = await callOp('GetAttendeesByPredictiveSearch', {
        includeAttendeeDetails: true,
        userId,
        searchTerms: terms,
        includeInactiveEmp: false,
        includeAtnTypeKeys: [1, 2, 3, 2001],
        excludeKeys: [],
        allowedAtnTypeKeys: [1, 2, 3, 2001],
      });
      const list = data?.attendeesByPredictiveSearch?.attendees || [];
      return { count: list.length, results: list.map(a => ({
        firstName: a.firstName,
        lastName: a.lastName,
        atnTypeName: a.atnTypeName,
        emailAddress: a.emailAddress,
        company: a.company,
        atnKey: a.atnKey,
        graphqlId: a.id,
        title: a.title,
        // NOTE: graphqlId/atnKey CANNOT be used directly in `concur attendees add`.
        // Use `concur attendees book --search=<lastName>` instead to get the v3 attendeeId.
      })) };
    }

    if (sub === 'book') {
      const opts = parseFlags(args, { search: '', max: '500' });
      const max = parseInt(opts.max, 10);
      const needle = opts.search.toLowerCase();
      const collected = [];
      let url = `${HOST_API}/api/v3.0/expense/attendees?limit=100`;
      let pages = 0;
      const pageCap = needle ? 200 : 50;  // search needs more pages
      while (url && collected.length < max && pages < pageCap) {
        pages++;
        const data = await pageFetch(url);
        for (const a of (data.Items || [])) {
          if (needle) {
            const hay = [a.FirstName, a.LastName, a.Company, a.EmailAddress, a.Title].filter(Boolean).join(' ').toLowerCase();
            if (!hay.includes(needle)) continue;
          }
          collected.push({
            attendeeId: a.ID,
            firstName: a.FirstName,
            lastName: a.LastName,
            company: a.Company,
            title: a.Title,
            email: a.EmailAddress,
            attendeeType: a.AttendeeTypeName,
            attendeeTypeId: a.AttendeeTypeID,
          });
          if (collected.length >= max) break;
        }
        url = data.NextPage || null;
      }
      return { pages, count: collected.length, attendees: collected };
    }

    if (sub === 'add') {
      const [reportId, expenseId, attendeeId, ...rest] = args;
      if (!reportId || !expenseId || !attendeeId) { console.error('Usage: concur attendees add <reportId> <expenseId> <attendeeId> [--amount=N] [--count=N]'); process.exit(1); }
      const opts = parseFlags(rest, { amount: '', count: '1' });
      // Resolve v3 EntryID
      const entries = await pageFetch(`${HOST_API}/api/v3.0/expense/entries?reportID=${reportId}&limit=100`);
      const entry = (entries.Items || []).find(e => e.ExpenseID === expenseId);
      if (!entry) { console.error(`No entry ${expenseId} on report ${reportId}`); process.exit(1); }
      const body = {
        EntryID: entry.ID,
        AttendeeID: attendeeId,
        Amount: opts.amount === '' ? entry.TransactionAmount / Math.max(1, parseInt(opts.count, 10)) : parseFloat(opts.amount),
        AssociatedAttendeeCount: parseInt(opts.count, 10),
      };
      const result = await pageFetch(`${HOST_API}/api/v3.0/expense/entryattendeeassociations`, { method: 'POST', body });
      return { added: body, response: result };
    }

    if (sub === 'remove') {
      const [associationId] = args;
      if (!associationId) { console.error('Usage: concur attendees remove <associationId>\\n  (use `concur attendees list <reportId> <expenseId>` to find associationId)'); process.exit(1); }
      const result = await pageFetch(`${HOST_API}/api/v3.0/expense/entryattendeeassociations/${encodeURIComponent(associationId)}`, { method: 'DELETE' });
      return { removed: associationId, response: result };
    }

    console.error(`Unknown attendees subcommand: ${sub}`);
    console.error('Try: list, search, book, add, remove');
    process.exit(1);
  },

  async 'change-type'(reportId, expenseId, expenseTypeId, ...args) {
    if (!reportId || !expenseId || !expenseTypeId) {
      console.error('Usage: concur change-type <reportId> <expenseId> <expenseTypeId> [--policy=<policyId>]');
      console.error('Common typeIds: 01000 (Meals & Entertainment w/ Customers), CARRT (Car Rental), HOTEL, AIRFR, MEALS (Daily Meals).');
      console.error('Run `concur policies` to list expense policies and their types.');
      process.exit(1);
    }
    const opts = parseFlags(args, { policy: '' });
    const userId = await getUserId();
    let policyId = opts.policy;
    if (!policyId) {
      const policies = await callOp('GetPolicies', { userId, contextRole: 'TRAVELER' });
      const list = policies?.employee?.expensePolicies?.policies || [];
      const def = list.find(p => p.isDefault) || list[0];
      if (!def) { console.error('No expense policies found'); process.exit(1); }
      policyId = def.id;
    }
    return callOp('UpdateExistingExpenseEntry', {
      taxFields: null,
      userId,
      contextRole: 'TRAVELER',
      isTrexEnabled: true,
      reportId,
      expenseId,
      shouldCopyDownFields: false,
      fields: { expenseTypeId },
      expenseTypeId,
      policyId,
      updateRecentExpenseType: true,
      expenseListDetailFormId: null,
    });
  },

  async 'attach-receipt'(reportId, expenseId, localPath, ...args) {
    if (!reportId || !expenseId || !localPath) {
      console.error('Usage: concur attach-receipt <reportId> <expenseId> <localPath> [--no-convert] [--max-bytes=N]');
      console.error('Image is auto-converted to JPEG via ImageMagick if it is not already.');
      console.error('Files larger than --max-bytes (default 800000) are auto-downscaled to a 1800px JPEG q=75.');
      process.exit(1);
    }
    const opts = parseFlags(args, { 'no-convert': '', 'max-bytes': '800000' });
    const maxBytes = parseInt(opts['max-bytes'], 10) || 800_000;

    // Pre-flight: refuse early if the report is locked. Saves a 4 MB upload
    // round-trip when the AttachImage mutation would have rejected anyway
    // ("reports.expenses.associateImageFailedForSubmittedReports").
    await assertReportMutable(reportId, 'attach receipts');

    // Stat the file
    const stat = await exec(`test -f "${localPath}" && stat -c %s "${localPath}" 2>/dev/null || stat -f %z "${localPath}"`);
    if (stat.exitCode !== 0) { console.error('File not found:', localPath); process.exit(1); }
    const inputBytes = parseInt((stat.stdout || '').trim(), 10) || 0;

    // Convert to JPEG unless told otherwise. magick is on PATH; ffmpeg WASM
    // doesn't handle HEIC. We also auto-downscale anything larger than
    // maxBytes — base64'd 4 MB JPEGs blow past the page-context eval-file
    // argv limit and the upload silently fails.
    let jpgPath = localPath;
    const needConvert = opts['no-convert'] !== 'true' && !/\.jpe?g$/i.test(localPath);
    const needShrink  = opts['no-convert'] !== 'true' && inputBytes > maxBytes;
    if (needConvert || needShrink) {
      jpgPath = `/shared/.concur-receipt-${Date.now()}.jpg`;
      const dim = needShrink ? '1800x1800>' : '2048x2048>';
      const q   = needShrink ? '75' : '85';
      const conv = await exec(`magick "${localPath}" -resize '${dim}' -quality ${q} "${jpgPath}"`);
      if (conv.exitCode !== 0) {
        console.error('magick conversion failed:', conv.stderr);
        process.exit(1);
      }
    }

    // Base64 the JPEG to ship through the eval-file payload
    const b64r = await exec(`base64 < "${jpgPath}" | tr -d '\\n'`);
    if (b64r.exitCode !== 0) { console.error('base64 failed'); process.exit(1); }
    const b64 = b64r.stdout.trim();

    // Upload via page-context fetch with multipart FormData. browser.fetch()
    // JSON-stringifies object bodies, which can't carry a Blob/FormData, so
    // this one request still goes through browser.evalAsync() with the
    // payload embedded as a literal (evalAsync serializes the function to a
    // string call expression, same technique the old eval-file used).
    const tab = await ensureTab();
    const filename = jpgPath.split('/').pop();
    const uploadScript = `
(async () => {
  const b64 = ${JSON.stringify(b64)};
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const blob = new Blob([bytes], { type: 'image/jpeg' });
  const fd = new FormData();
  fd.append('file', blob, ${JSON.stringify(filename)});
  const r = await fetch('https://www-us2.api.concursolutions.com/spend-graphql/upload', {
    method: 'POST', credentials: 'include', body: fd,
  });
  const text = await r.text();
  return JSON.stringify({ status: r.status, body: text });
})()
    `.trim();
    let wrap;
    try {
      const upRes = await browser.evalAsync(tab, uploadScript);
      wrap = typeof upRes === 'string' ? JSON.parse(upRes) : upRes;
    } catch (e) {
      console.error('upload failed:', e?.message || e);
      process.exit(1);
    }
    if (jpgPath !== localPath) await exec(`rm -f "${jpgPath}"`);
    if (wrap.status >= 400) {
      console.error(`Upload HTTP ${wrap.status}:`, wrap.body);
      process.exit(1);
    }
    const upBody = JSON.parse(wrap.body);
    const imageId = upBody.imageId;
    if (!imageId) { console.error('No imageId in upload response:', wrap.body); process.exit(1); }

    // Attach via AttachImage mutation
    const userId = await getUserId();
    const attachRes = await callOp('AttachImage', {
      userId, contextRole: 'TRAVELER', reportId, expenseId, imageId,
    });
    return {
      uploaded: { imageId, href: upBody.href },
      attached: attachRes?.employee?.expenseReport?.entry?.attachImage,
    };
  },

  // -----------------------------------------------------------------
  // itemize: split a single expense entry into multiple itemization
  // lines (e.g. hotel folio → Lodging + Hotel Tax + Resort Fee).
  //
  // Subcommands:
  //   concur itemize types  <reportId> <expenseId>
  //       List the expense types valid for itemizing this entry.
  //
  //   concur itemize add    <reportId> <parentExpenseId> <typeId>
  //                          <amount> [date] [comment] [--currency=USD]
  //       Add a single itemization line via SaveNewItemization.
  //
  //   concur itemize room-rate <reportId> <expenseId> <rates.json>
  //       Direct wrapper around CreateSame/DifferentRoomRateMutation.
  //       rates.json is either {roomRate,taxRate} or [{roomRate,taxRate},…]
  //
  //   concur itemize hotel  <reportId> <expenseId> <bill.json>
  //       High-level hotel-folio itemization. bill.json shape:
  //       {
  //         "currency": "USD",
  //         "nights": [{ "roomRate": 160, "roomTax": 21.41 }, …],
  //         "extras": [
  //           { "typeId": "RESRT", "amount": 41.95,
  //             "date": "2026-04-19", "comment": "Resort Fee" }, …
  //         ]
  //       }
  //       The sum of (room+tax) per night plus all extras must equal
  //       the parent entry's transactionAmount; the command refuses
  //       otherwise.
  // -----------------------------------------------------------------
  async itemize(sub, ...rest) {
    if (!sub || sub === 'help' || sub === '-h') {
      console.error([
        'Usage:',
        '  concur itemize types     <reportId> <expenseId>',
        '  concur itemize add       <reportId> <parentExpenseId> <typeId> <amount> [date] [comment] [--currency=USD]',
        '  concur itemize room-rate <reportId> <expenseId> <rates.json>',
        '  concur itemize hotel     <reportId> <expenseId> <bill.json>',
      ].join('\n'));
      process.exit(sub ? 0 : 1);
    }
    if (sub === 'types')     return await itemizeTypes(...rest);
    if (sub === 'add')       return await itemizeAdd(...rest);
    if (sub === 'room-rate') return await itemizeRoomRate(...rest);
    if (sub === 'hotel')     return await itemizeHotel(...rest);
    console.error(`Unknown itemize subcommand: ${sub}`);
    process.exit(1);
  },

  async submit(reportId, ...args) {
    if (!reportId) { console.error('Usage: concur submit <reportId> [--source=WEB] [--approver-validated]'); process.exit(1); }
    const opts = parseFlags(args, { source: 'WEB', 'approver-validated': '' });
    const userId = await getUserId();
    const baseVars = {
      userId,
      contextRole: 'TRAVELER',
      reportSource: opts.source,
      reportId,
      approverValidated: opts['approver-validated'] === 'true',
    };
    // Concur requires a 2-step mutation: validate first, then commit
    const validation = await callOp('SubmitExpenseReport', { ...baseVars, validate: true });
    const vstatus = validation?.CDS_expense?.report?.submit?.status;
    if (vstatus !== 'COMPLETED') {
      console.error('Validation failed:', JSON.stringify(validation, null, 2));
      process.exit(1);
    }
    const commit = await callOp('SubmitExpenseReport', { ...baseVars, validate: false });
    const cstatus = commit?.CDS_expense?.report?.submit?.status;
    return { reportId, validation: vstatus, commit: cstatus };
  },

  // -- v3.0 REST API (public Concur Platform API, cookie-auth friendly) --

  async 'reports-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', user: '', modifiedAfter: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, user: opts.user, modifiedAfter: opts.modifiedAfter });
    return pageFetch(`${HOST_API}/api/v3.0/expense/reports${qs}`);
  },

  async 'report-v3'(reportId) {
    if (!reportId) { console.error('Usage: concur report-v3 <reportId>'); process.exit(1); }
    return pageFetch(`${HOST_API}/api/v3.0/expense/reports/${reportId}`);
  },

  async 'entries-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', reportId: '', user: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, reportID: opts.reportId, user: opts.user });
    return pageFetch(`${HOST_API}/api/v3.0/expense/entries${qs}`);
  },

  async 'attendees-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset });
    return pageFetch(`${HOST_API}/api/v3.0/expense/attendees${qs}`);
  },

  async digests(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', user: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, user: opts.user });
    return pageFetch(`${HOST_API}/api/v3.0/expense/reportdigests${qs}`);
  },

  async locations(...args) {
    const opts = parseFlags(args, { limit: '10', name: '', country: '' });
    const qs = buildQS({ limit: opts.limit, name: opts.name, country: opts.country });
    return pageFetch(`${HOST_API}/api/v3.0/common/locations${qs}`);
  },

  async policies() {
    const userId = await getUserId();
    return callOp('GetPolicies', { userId, contextRole: 'TRAVELER' });
  },

  async 'recent-types'(...args) {
    const opts = parseFlags(args, { policy: '' });
    // GetRecentExpenseTypes declares $policyId: ID! (non-null), so resolve
    // a default from GetPolicies when --policy is omitted (same auto-discover
    // strategy as `change-type`).
    let policyId = opts.policy;
    if (!policyId) {
      const userId = await getUserId();
      const policies = await callOp('GetPolicies', { userId, contextRole: 'TRAVELER' });
      const list = policies?.employee?.expensePolicies?.policies || [];
      const def = list.find((p) => p.isDefault) || list[0];
      if (!def) { console.error('No expense policies found; pass --policy=<id>'); process.exit(1); }
      policyId = def.id;
    }
    return callOp('GetRecentExpenseTypes', { policyId });
  },

  async cards() {
    const userId = await getUserId();
    return callOp('GetCardAccounts', { userId, contextRole: 'TRAVELER' });
  },

  async messages(...args) {
    const opts = parseFlags(args, { sort: 'timestamp', order: 'descending' });
    return pageFetch(`${HOST_API}/messagenexus/v1/messages?sort=${opts.sort}&order=${opts.order}`);
  },

  async ops() {
    const r = await exec(`ls ${OPS_DIR}`);
    const list = r.stdout.split('\n').filter(Boolean).map(s => s.replace(/\.graphql$/, ''));
    return { count: list.length, operations: list };
  },

  async graphql(opName, varsJson, surface = 'spend') {
    if (!opName) {
      console.error('Usage: concur graphql <operationName> [<variables-json>] [spend|cds]');
      console.error('Run "concur ops" to list available operations.');
      process.exit(1);
    }
    let variables = {};
    if (varsJson) {
      try { variables = JSON.parse(varsJson); }
      catch { console.error('variables must be valid JSON'); process.exit(1); }
    }
    return callOp(opName, variables, surface);
  },

  async tab() {
    const t = await ensureTab();
    return { tab: t };
  },

  async help() {
    return {
      usage: 'concur <command> [args]',
      commands: Object.keys(commands).filter(c => c !== 'help'),
      examples: [
        'concur me',
        'concur reports                                # GraphQL: active reports (rich)',
        'concur reports-v3                             # REST v3: all reports (history)',
        'concur reports-v3 --limit=50',
        'concur report A1B2C3D4E5F60718293A            # GraphQL: full detail',
        'concur report-v3 A1B2C3D4E5F60718293A         # REST v3: report header',
        'concur entries-v3 --reportId=A1B2C3D4E5F60718293A',
        'concur expenses A1B2C3D4E5F60718293A',
        'concur available-receipts',
        'concur smartexpenses',
        'concur policies',
        'concur ops',
        'concur graphql GetUserPermissions {}',
        'concur graphql GetReportsForUser \'{"userId":"...","contextRole":"TRAVELER","filterByStatus":"ACTIVE","paging":{"page":1,"size":25}}\'',
      ],
    };
  },
};

// ----------------- CLI plumbing -----------------

function parseFlags(args, defaults) {
  const out = { ...defaults };
  for (const a of args) {
    const m = a.match(/^--([\w-]+)(?:=(.*))?$/);
    if (m) out[m[1]] = m[2] ?? 'true';
  }
  return out;
}

function buildQS(obj) {
  const parts = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v === '' || v === null || v === undefined) continue;
    parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(v)}`);
  }
  return parts.length ? `?${parts.join('&')}` : '';
}

const [, , cmd, ...args] = process.argv;

if (!cmd || cmd === '-h' || cmd === '--help') {
  const h = await commands.help();
  console.log(JSON.stringify(h, null, 2));
  process.exit(0);
}

if (!commands[cmd]) {
  console.error(`Unknown command: ${cmd}`);
  console.error(`Run "concur help" for usage.`);
  process.exit(1);
}

try {
  const result = await commands[cmd](...args);
  if (result !== undefined) console.log(JSON.stringify(result, null, 2));
} catch (e) {
  console.error('Error:', e?.message || e);
  process.exit(1);
}
