// Concur API client — generated by secret-sauce
//
// Concur uses cookie-based auth on .concursolutions.com. Browser fetch from
// SLICC's localhost origin can't carry that cookie, so every request runs
// inside a page-context fetch via `playwright-cli eval-file` against a tab
// already loaded on us2.concursolutions.com.

const APP_DOMAIN = 'concursolutions.com';
const HOME_URL   = 'https://us2.concursolutions.com/home';
const HOST_WEB   = 'https://us2.concursolutions.com';
const HOST_API   = 'https://www-us2.api.concursolutions.com';
const OPS_DIR    = '/workspace/skills/concur/references/operations';
const PERSIST    = '/workspace/skills/concur/.session.json';

// ----------------- tab management -----------------

let _tabId = null;

async function findConcurTab() {
  const r = await exec('playwright-cli tab-list');
  // Match "[TARGETID] https://...concursolutions.com..."
  const re = /\[([A-F0-9]+)\]\s+https?:\/\/[^\s]*concursolutions\.com/g;
  const matches = [...r.stdout.matchAll(re)];
  return matches.length ? matches[0][1] : null;
}

async function ensureTab() {
  if (_tabId) return _tabId;
  const existing = await findConcurTab();
  if (existing) { _tabId = existing; return _tabId; }
  console.error('No Concur tab open — opening one. This may require login.');
  const r = await exec(`playwright-cli open ${HOME_URL}`);
  const m = r.stdout.match(/targetId:\s*(\S+?)\]/);
  if (!m) { console.error('Failed to open Concur tab:', r.stdout, r.stderr); process.exit(1); }
  _tabId = m[1];
  await new Promise(r => setTimeout(r, 4000));
  return _tabId;
}

// ----------------- session info -----------------

let _userId = null;

async function getUserId() {
  if (_userId) return _userId;
  // Try cached session file
  try {
    const cache = JSON.parse(await readFile(PERSIST));
    if (cache.userId) { _userId = cache.userId; return _userId; }
  } catch {}
  // Discover via GetUserPermissions (no variables)
  const data = await graphql('spend', {
    operationName: 'GetUserPermissions',
    query: await loadOp('GetUserPermissions'),
    variables: {},
  });
  const uid = data?.userPermissions?.userId;
  if (!uid) {
    console.error('Could not determine userId from GetUserPermissions response:', JSON.stringify(data).slice(0, 500));
    process.exit(1);
  }
  _userId = uid;
  try { await writeFile(PERSIST, JSON.stringify({ userId: uid }, null, 2)); } catch {}
  return uid;
}

async function readFile(p) {
  const r = await exec(`cat "${p}"`);
  if (r.exitCode !== 0) throw new Error(`read failed: ${p}`);
  return r.stdout;
}

async function writeFile(p, s) {
  const tmp = `/tmp/.concur-write-${Date.now()}.tmp`;
  await exec(`cat > "${tmp}" <<'____CONCUR_EOF____'\n${s}\n____CONCUR_EOF____`);
  await exec(`mkdir -p "$(dirname "${p}")" && mv "${tmp}" "${p}"`);
}

async function loadOp(name) {
  return readFile(`${OPS_DIR}/${name}.graphql`);
}

// ----------------- page-context fetch -----------------
//
// We write the request payload to a JS file and run it via
// `playwright-cli eval-file --tab=<id>`. The page context handles cookies,
// origin, and any required browser headers automatically.

async function pageFetch(url, options = {}) {
  const tabId = await ensureTab();
  const payload = {
    url,
    method: options.method || 'GET',
    body: options.body ?? null,
    headers: options.headers || {},
  };
  const evalFile = `/tmp/.concur-fetch-${Date.now()}-${Math.random().toString(36).slice(2,8)}.js`;
  const script = `
(async () => {
  const p = ${JSON.stringify(payload)};
  const init = { method: p.method, credentials: 'include', headers: { 'Accept': 'application/json', ...p.headers } };
  if (p.body !== null && p.body !== undefined && p.method !== 'GET') {
    init.headers['Content-Type'] = init.headers['Content-Type'] || 'application/json';
    init.body = typeof p.body === 'string' ? p.body : JSON.stringify(p.body);
  }
  let resp;
  try { resp = await fetch(p.url, init); }
  catch (e) { return JSON.stringify({ __concur_error: 'network', message: String(e) }); }
  const status = resp.status;
  const ctype = resp.headers.get('content-type') || '';
  const text = await resp.text();
  if (!resp.ok) return JSON.stringify({ __concur_error: 'http', status, body: text.slice(0, 4000) });
  if (/json/i.test(ctype)) {
    try { return JSON.stringify({ ok: true, status, json: JSON.parse(text) }); }
    catch { return JSON.stringify({ ok: true, status, text }); }
  }
  return JSON.stringify({ ok: true, status, text });
})()
  `.trim();
  await writeFile(evalFile, script);
  const r = await exec(`playwright-cli eval-file ${evalFile} --tab=${tabId}`);
  await exec(`rm -f ${evalFile}`);
  if (r.exitCode !== 0) {
    console.error('eval-file failed:', r.stderr);
    process.exit(1);
  }
  // playwright-cli eval-file output sometimes wraps the return value;
  // strip leading/trailing non-JSON noise.
  const out = r.stdout.trim();
  const start = out.indexOf('{');
  const end   = out.lastIndexOf('}');
  let parsed;
  try { parsed = JSON.parse(start >= 0 ? out.slice(start, end + 1) : out); }
  catch (e) { console.error('Could not parse pageFetch result:', out.slice(0, 1000)); process.exit(1); }
  if (parsed.__concur_error === 'network') {
    console.error('Network error:', parsed.message);
    process.exit(1);
  }
  if (parsed.__concur_error === 'http') {
    if (parsed.status === 401 || parsed.status === 403) {
      console.error(`Auth failed (${parsed.status}). Open ${HOST_WEB} in your browser, log in, and retry.`);
    } else {
      console.error(`HTTP ${parsed.status}:`, parsed.body);
    }
    process.exit(1);
  }
  return parsed.json !== undefined ? parsed.json : parsed.text;
}

// ----------------- GraphQL helpers -----------------

async function graphql(surface, body) {
  const url = surface === 'cds'
    ? `${HOST_API}/cds/graphql`
    : `${HOST_API}/spend-graphql/graphql`;
  const correlationId = crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
  const result = await pageFetch(url, {
    method: 'POST',
    body,
    headers: {
      'concur-correlationId': correlationId,
      'concur-correlationid': correlationId,
    },
  });
  if (result?.errors) {
    console.error('GraphQL errors:', JSON.stringify(result.errors, null, 2));
    process.exit(1);
  }
  return result?.data ?? result;
}

async function callOp(opName, variables = {}, surface = 'spend') {
  const query = await loadOp(opName);
  return graphql(surface, { operationName: opName, query, variables });
}

// ----------------- commands -----------------

const commands = {
  async me() {
    const userId = await getUserId();
    const data = await callOp('GetUserPermissions');
    return { userId, ...data.userPermissions };
  },

  async reports(...args) {
    const opts = parseFlags(args, { status: 'ACTIVE', page: '1', size: '100' });
    const userId = await getUserId();
    const data = await callOp('GetReportsForUser', {
      isAiUser: false,
      filterByStatus: opts.status,
      dateRange: null,
      paging: { page: parseInt(opts.page, 10), size: parseInt(opts.size, 10) },
      sortBy: null,
      sortDirection: null,
      userId,
      contextRole: 'TRAVELER',
    });
    return data.employee.reportsForUser;
  },

  async report(reportId) {
    if (!reportId) { console.error('Usage: concur report <reportId>'); process.exit(1); }
    const userId = await getUserId();
    const main = await callOp('GetReportPageData', {
      reportId, userId, contextRole: 'TRAVELER',
      includeCostObjects: true, includeDetailItemizations: true, includeEntries: true,
      includeExceptions: true, includeGroupSettings: true, includePolicy: true,
      includeSiteSettings: true, includeSummary: true, includeWorkflows: true,
      shouldChangeWarningAlertsToInformation: false,
    });
    return main;
  },

  async expenses(reportId) {
    if (!reportId) { console.error('Usage: concur expenses <reportId>'); process.exit(1); }
    const userId = await getUserId();
    const data = await callOp('GetReportExceptionsAndEntries', {
      reportId, userId, contextRole: 'TRAVELER',
      expenseListDetailFormId: null, includeDetailItemizations: true,
    });
    return data;
  },

  async 'available-receipts'() {
    const userId = await getUserId();
    const data = await callOp('GetAvailableReceipts', {
      userId, contextRole: 'TRAVELER', deleteEbunshoFlagEnabled: false,
    });
    return data;
  },

  async smartexpenses(...args) {
    const opts = parseFlags(args, { size: '25', context: 'TRAVELER' });
    const userId = await getUserId();
    return pageFetch(`${HOST_API}/smartexpense/v4/users/${userId}/context/${opts.context}/smartexpenses?size=${opts.size}`);
  },

  // -- mutations --

  async attendees(sub, ...args) {
    if (!sub) {
      console.error('Usage: concur attendees <list|search|book|add|remove> [args]');
      console.error('  list   <reportId> <expenseId>          — attendees on an entry');
      console.error('  search <terms>                          — GraphQL predictive search (entire org)');
      console.error('  book   [--search=<text>] [--max=N]      — your saved attendee book (returns v3 IDs)');
      console.error('  add    <reportId> <expenseId> <attendeeId> [--amount=N] [--count=N]');
      console.error('  remove <associationId>                  — drop one association (use list to get id)');
      process.exit(1);
    }
    const userId = await getUserId();

    if (sub === 'list') {
      const [reportId, expenseId] = args;
      if (!reportId || !expenseId) { console.error('Usage: concur attendees list <reportId> <expenseId>'); process.exit(1); }
      // 1. map hex expenseId -> v3 EntryID via /expense/entries
      const entries = await pageFetch(`${HOST_API}/api/v3.0/expense/entries?reportID=${reportId}&limit=100`);
      const entry = (entries.Items || []).find(e => e.ExpenseID === expenseId);
      if (!entry) { console.error(`No entry ${expenseId} on report ${reportId}`); process.exit(1); }
      const v3EntryID = entry.ID;

      // 2. paginate associations and filter
      const matches = [];
      let url = `${HOST_API}/api/v3.0/expense/entryattendeeassociations?limit=100`;
      let pages = 0;
      while (url && pages < 50) {
        pages++;
        const data = await pageFetch(url);
        for (const it of (data.Items || [])) if (it.EntryID === v3EntryID) matches.push(it);
        url = data.NextPage || null;
      }

      // 3. resolve names
      const out = [];
      for (const m of matches) {
        const a = await pageFetch(`${HOST_API}/api/v3.0/expense/attendees/${encodeURIComponent(m.AttendeeID)}`);
        out.push({
          associationId: m.ID,
          attendeeId: m.AttendeeID,
          firstName: a.FirstName,
          lastName: a.LastName,
          company: a.Company,
          title: a.Title,
          email: a.EmailAddress,
          attendeeType: a.AttendeeTypeName,
          amount: m.Amount,
          count: m.AssociatedAttendeeCount,
        });
      }
      return { entry: { reportId, expenseId, v3EntryID, vendor: entry.VendorDescription, total: entry.TransactionAmount, currency: entry.TransactionCurrencyCode }, attendeeCount: out.length, attendees: out };
    }

    if (sub === 'search') {
      const terms = args.join(' ').trim();
      if (!terms) { console.error('Usage: concur attendees search <terms>'); process.exit(1); }
      const data = await callOp('GetAttendeesByPredictiveSearch', {
        includeAttendeeDetails: true,
        userId,
        searchTerms: terms,
        includeInactiveEmp: false,
        includeAtnTypeKeys: [1, 2, 3, 2001],
        excludeKeys: [],
        allowedAtnTypeKeys: [1, 2, 3, 2001],
      });
      const list = data?.attendeesByPredictiveSearch?.attendees || [];
      return { count: list.length, results: list.map(a => ({
        firstName: a.firstName,
        lastName: a.lastName,
        atnTypeName: a.atnTypeName,
        emailAddress: a.emailAddress,
        company: a.company,
        atnKey: a.atnKey,
        graphqlId: a.id,
        title: a.title,
        // NOTE: graphqlId/atnKey CANNOT be used directly in `concur attendees add`.
        // Use `concur attendees book --search=<lastName>` instead to get the v3 attendeeId.
      })) };
    }

    if (sub === 'book') {
      const opts = parseFlags(args, { search: '', max: '500' });
      const max = parseInt(opts.max, 10);
      const needle = opts.search.toLowerCase();
      const collected = [];
      let url = `${HOST_API}/api/v3.0/expense/attendees?limit=100`;
      let pages = 0;
      const pageCap = needle ? 200 : 50;  // search needs more pages
      while (url && collected.length < max && pages < pageCap) {
        pages++;
        const data = await pageFetch(url);
        for (const a of (data.Items || [])) {
          if (needle) {
            const hay = [a.FirstName, a.LastName, a.Company, a.EmailAddress, a.Title].filter(Boolean).join(' ').toLowerCase();
            if (!hay.includes(needle)) continue;
          }
          collected.push({
            attendeeId: a.ID,
            firstName: a.FirstName,
            lastName: a.LastName,
            company: a.Company,
            title: a.Title,
            email: a.EmailAddress,
            attendeeType: a.AttendeeTypeName,
            attendeeTypeId: a.AttendeeTypeID,
          });
          if (collected.length >= max) break;
        }
        url = data.NextPage || null;
      }
      return { pages, count: collected.length, attendees: collected };
    }

    if (sub === 'add') {
      const [reportId, expenseId, attendeeId, ...rest] = args;
      if (!reportId || !expenseId || !attendeeId) { console.error('Usage: concur attendees add <reportId> <expenseId> <attendeeId> [--amount=N] [--count=N]'); process.exit(1); }
      const opts = parseFlags(rest, { amount: '', count: '1' });
      // Resolve v3 EntryID
      const entries = await pageFetch(`${HOST_API}/api/v3.0/expense/entries?reportID=${reportId}&limit=100`);
      const entry = (entries.Items || []).find(e => e.ExpenseID === expenseId);
      if (!entry) { console.error(`No entry ${expenseId} on report ${reportId}`); process.exit(1); }
      const body = {
        EntryID: entry.ID,
        AttendeeID: attendeeId,
        Amount: opts.amount === '' ? entry.TransactionAmount / Math.max(1, parseInt(opts.count, 10)) : parseFloat(opts.amount),
        AssociatedAttendeeCount: parseInt(opts.count, 10),
      };
      const result = await pageFetch(`${HOST_API}/api/v3.0/expense/entryattendeeassociations`, { method: 'POST', body });
      return { added: body, response: result };
    }

    if (sub === 'remove') {
      const [associationId] = args;
      if (!associationId) { console.error('Usage: concur attendees remove <associationId>\\n  (use `concur attendees list <reportId> <expenseId>` to find associationId)'); process.exit(1); }
      const result = await pageFetch(`${HOST_API}/api/v3.0/expense/entryattendeeassociations/${encodeURIComponent(associationId)}`, { method: 'DELETE' });
      return { removed: associationId, response: result };
    }

    console.error(`Unknown attendees subcommand: ${sub}`);
    console.error('Try: list, search, book, add, remove');
    process.exit(1);
  },

  async 'change-type'(reportId, expenseId, expenseTypeId, ...args) {
    if (!reportId || !expenseId || !expenseTypeId) {
      console.error('Usage: concur change-type <reportId> <expenseId> <expenseTypeId> [--policy=<policyId>]');
      console.error('Common typeIds: 01000 (Meals & Entertainment w/ Customers), CARRT (Car Rental), HOTEL, AIRFR, MEALS (Daily Meals).');
      console.error('Run `concur policies` to list expense policies and their types.');
      process.exit(1);
    }
    const opts = parseFlags(args, { policy: '' });
    const userId = await getUserId();
    let policyId = opts.policy;
    if (!policyId) {
      const policies = await callOp('GetPolicies', { userId, contextRole: 'TRAVELER' });
      const list = policies?.employee?.expensePolicies?.policies || [];
      const def = list.find(p => p.isDefault) || list[0];
      if (!def) { console.error('No expense policies found'); process.exit(1); }
      policyId = def.id;
    }
    return callOp('UpdateExistingExpenseEntry', {
      taxFields: null,
      userId,
      contextRole: 'TRAVELER',
      isTrexEnabled: true,
      reportId,
      expenseId,
      shouldCopyDownFields: false,
      fields: { expenseTypeId },
      expenseTypeId,
      policyId,
      updateRecentExpenseType: true,
      expenseListDetailFormId: null,
    });
  },

  async 'attach-receipt'(reportId, expenseId, localPath, ...args) {
    if (!reportId || !expenseId || !localPath) {
      console.error('Usage: concur attach-receipt <reportId> <expenseId> <localPath>');
      console.error('Image is auto-converted to JPEG via ImageMagick if it is not already.');
      process.exit(1);
    }
    const opts = parseFlags(args, { 'no-convert': '' });

    // Stat the file
    const stat = await exec(`test -f "${localPath}" && stat -c %s "${localPath}" 2>/dev/null || stat -f %z "${localPath}"`);
    if (stat.exitCode !== 0) { console.error('File not found:', localPath); process.exit(1); }

    // Convert to JPEG unless told otherwise. magick is on PATH; ffmpeg WASM doesn't handle HEIC.
    let jpgPath = localPath;
    if (opts['no-convert'] !== 'true' && !/\.jpe?g$/i.test(localPath)) {
      jpgPath = `/tmp/.concur-receipt-${Date.now()}.jpg`;
      const conv = await exec(`magick "${localPath}" -auto-orient -resize '2048x2048>' -quality 85 "${jpgPath}"`);
      if (conv.exitCode !== 0) {
        console.error('magick conversion failed:', conv.stderr);
        process.exit(1);
      }
    }

    // Base64 the JPEG to ship through the eval-file payload
    const b64r = await exec(`base64 < "${jpgPath}" | tr -d '\\n'`);
    if (b64r.exitCode !== 0) { console.error('base64 failed'); process.exit(1); }
    const b64 = b64r.stdout.trim();

    // Upload via page-context fetch with multipart FormData
    const tabId = await ensureTab();
    const evalFile = `/tmp/.concur-upload-${Date.now()}.js`;
    const filename = jpgPath.split('/').pop();
    const uploadScript = `
(async () => {
  const b64 = ${JSON.stringify(b64)};
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const blob = new Blob([bytes], { type: 'image/jpeg' });
  const fd = new FormData();
  fd.append('file', blob, ${JSON.stringify(filename)});
  const r = await fetch('https://www-us2.api.concursolutions.com/spend-graphql/upload', {
    method: 'POST', credentials: 'include', body: fd,
  });
  const text = await r.text();
  return JSON.stringify({ status: r.status, body: text });
})()
    `.trim();
    await writeFile(evalFile, uploadScript);
    const upRes = await exec(`playwright-cli eval-file ${evalFile} --tab=${tabId}`);
    await exec(`rm -f ${evalFile}`);
    if (jpgPath !== localPath) await exec(`rm -f "${jpgPath}"`);
    if (upRes.exitCode !== 0) { console.error('upload failed:', upRes.stderr); process.exit(1); }

    // Parse upload response
    const out = upRes.stdout.trim();
    const start = out.indexOf('{'), end = out.lastIndexOf('}');
    const wrap = JSON.parse(start >= 0 ? out.slice(start, end + 1) : out);
    if (wrap.status >= 400) {
      console.error(`Upload HTTP ${wrap.status}:`, wrap.body);
      process.exit(1);
    }
    const upBody = JSON.parse(wrap.body);
    const imageId = upBody.imageId;
    if (!imageId) { console.error('No imageId in upload response:', wrap.body); process.exit(1); }

    // Attach via AttachImage mutation
    const userId = await getUserId();
    const attachRes = await callOp('AttachImage', {
      userId, contextRole: 'TRAVELER', reportId, expenseId, imageId,
    });
    return {
      uploaded: { imageId, href: upBody.href },
      attached: attachRes?.employee?.expenseReport?.entry?.attachImage,
    };
  },

  async submit(reportId, ...args) {
    if (!reportId) { console.error('Usage: concur submit <reportId> [--source=WEB] [--approver-validated]'); process.exit(1); }
    const opts = parseFlags(args, { source: 'WEB', 'approver-validated': '' });
    const userId = await getUserId();
    const baseVars = {
      userId,
      contextRole: 'TRAVELER',
      reportSource: opts.source,
      reportId,
      approverValidated: opts['approver-validated'] === 'true',
    };
    // Concur requires a 2-step mutation: validate first, then commit
    const validation = await callOp('SubmitExpenseReport', { ...baseVars, validate: true });
    const vstatus = validation?.CDS_expense?.report?.submit?.status;
    if (vstatus !== 'COMPLETED') {
      console.error('Validation failed:', JSON.stringify(validation, null, 2));
      process.exit(1);
    }
    const commit = await callOp('SubmitExpenseReport', { ...baseVars, validate: false });
    const cstatus = commit?.CDS_expense?.report?.submit?.status;
    return { reportId, validation: vstatus, commit: cstatus };
  },

  // -- v3.0 REST API (public Concur Platform API, cookie-auth friendly) --

  async 'reports-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', user: '', modifiedAfter: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, user: opts.user, modifiedAfter: opts.modifiedAfter });
    return pageFetch(`${HOST_API}/api/v3.0/expense/reports${qs}`);
  },

  async 'report-v3'(reportId) {
    if (!reportId) { console.error('Usage: concur report-v3 <reportId>'); process.exit(1); }
    return pageFetch(`${HOST_API}/api/v3.0/expense/reports/${reportId}`);
  },

  async 'entries-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', reportId: '', user: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, reportID: opts.reportId, user: opts.user });
    return pageFetch(`${HOST_API}/api/v3.0/expense/entries${qs}`);
  },

  async 'attendees-v3'(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset });
    return pageFetch(`${HOST_API}/api/v3.0/expense/attendees${qs}`);
  },

  async digests(...args) {
    const opts = parseFlags(args, { limit: '25', offset: '', user: '' });
    const qs = buildQS({ limit: opts.limit, offset: opts.offset, user: opts.user });
    return pageFetch(`${HOST_API}/api/v3.0/expense/reportdigests${qs}`);
  },

  async locations(...args) {
    const opts = parseFlags(args, { limit: '10', name: '', country: '' });
    const qs = buildQS({ limit: opts.limit, name: opts.name, country: opts.country });
    return pageFetch(`${HOST_API}/api/v3.0/common/locations${qs}`);
  },

  async policies() {
    const userId = await getUserId();
    return callOp('GetPolicies', { userId, contextRole: 'TRAVELER' });
  },

  async 'recent-types'(...args) {
    const opts = parseFlags(args, { policy: '' });
    return callOp('GetRecentExpenseTypes', { policyId: opts.policy || null });
  },

  async cards() {
    const userId = await getUserId();
    return callOp('GetCardAccounts', { userId, contextRole: 'TRAVELER' });
  },

  async messages(...args) {
    const opts = parseFlags(args, { sort: 'timestamp', order: 'descending' });
    return pageFetch(`${HOST_API}/messagenexus/v1/messages?sort=${opts.sort}&order=${opts.order}`);
  },

  async ops() {
    const r = await exec(`ls ${OPS_DIR}`);
    const list = r.stdout.split('\n').filter(Boolean).map(s => s.replace(/\.graphql$/, ''));
    return { count: list.length, operations: list };
  },

  async graphql(opName, varsJson, surface = 'spend') {
    if (!opName) {
      console.error('Usage: concur graphql <operationName> [<variables-json>] [spend|cds]');
      console.error('Run "concur ops" to list available operations.');
      process.exit(1);
    }
    let variables = {};
    if (varsJson) {
      try { variables = JSON.parse(varsJson); }
      catch { console.error('variables must be valid JSON'); process.exit(1); }
    }
    return callOp(opName, variables, surface);
  },

  async tab() {
    const id = await ensureTab();
    return { tabId: id };
  },

  async help() {
    return {
      usage: 'concur <command> [args]',
      commands: Object.keys(commands).filter(c => c !== 'help'),
      examples: [
        'concur me',
        'concur reports                                # GraphQL: active reports (rich)',
        'concur reports-v3                             # REST v3: all reports (history)',
        'concur reports-v3 --limit=50',
        'concur report A1B2C3D4E5F60718293A            # GraphQL: full detail',
        'concur report-v3 A1B2C3D4E5F60718293A         # REST v3: report header',
        'concur entries-v3 --reportId=A1B2C3D4E5F60718293A',
        'concur expenses A1B2C3D4E5F60718293A',
        'concur available-receipts',
        'concur smartexpenses',
        'concur policies',
        'concur ops',
        'concur graphql GetUserPermissions {}',
        'concur graphql GetReportsForUser \'{"userId":"...","contextRole":"TRAVELER","filterByStatus":"ACTIVE","paging":{"page":1,"size":25}}\'',
      ],
    };
  },
};

// ----------------- CLI plumbing -----------------

function parseFlags(args, defaults) {
  const out = { ...defaults };
  for (const a of args) {
    const m = a.match(/^--([\w-]+)(?:=(.*))?$/);
    if (m) out[m[1]] = m[2] ?? 'true';
  }
  return out;
}

function buildQS(obj) {
  const parts = [];
  for (const [k, v] of Object.entries(obj)) {
    if (v === '' || v === null || v === undefined) continue;
    parts.push(`${encodeURIComponent(k)}=${encodeURIComponent(v)}`);
  }
  return parts.length ? `?${parts.join('&')}` : '';
}

const [, , cmd, ...args] = process.argv;

if (!cmd || cmd === '-h' || cmd === '--help') {
  const h = await commands.help();
  console.log(JSON.stringify(h, null, 2));
  process.exit(0);
}

if (!commands[cmd]) {
  console.error(`Unknown command: ${cmd}`);
  console.error(`Run "concur help" for usage.`);
  process.exit(1);
}

try {
  const result = await commands[cmd](...args);
  if (result !== undefined) console.log(JSON.stringify(result, null, 2));
} catch (e) {
  console.error('Error:', e?.message || e);
  process.exit(1);
}
