// LinkedIn API client — generated by secret-sauce
// Posts to and manages the AI Ecoverse company page via Voyager GraphQL API
//
// Usage:
//   linkedin post <text>               Publish a text post
//   linkedin list [--limit N]          List recent posts with engagement stats
//   linkedin comments <activityId>     View comments on a post
//   linkedin comment <activityId> <text>  Reply to a post as the company page
//   linkedin reactions <activityId>    View reactions on a post
//   linkedin profile <vanityName>      Quick preview of a LinkedIn profile
//   linkedin watch --scoop=<name>      Watch for new comments (creates cron poller)
//   linkedin unwatch                   Stop watching for comments
//   linkedin watches                   List active watches
//   linkedin monday [--limit N] [--date Nd]  Monday protocol aggregation
//   linkedin help                      Show this help

// ─── Configuration ───────────────────────────────────────────────────────────

const CONFIG_FILE = '/workspace/skills/linkedin/.config';
const LINKEDIN_DOMAIN = 'www.linkedin.com';
const GRAPHQL_CREATE_QUERY_ID = 'voyagerContentcreationDashShares.279996efa5064c01775d5aff003d9377';
const VIDEO_UPLOAD_METADATA_PATH = '/voyager/api/voyagerVideoDashMediaUploadMetadata?action=upload';
const GRAPHQL_LIST_QUERY_ID = 'voyagerFeedDashOrganizationalPageAdminUpdates.96fdd4f5900fb8a434c2a3286b1952c2';
const GRAPHQL_COMMENTS_QUERY_ID = 'voyagerSocialDashComments.afec6d88d7810d45548797a8dac4fb87';
const COMMENT_CREATE_DECORATION = 'com.linkedin.voyager.dash.deco.social.NormComment-43';
const PROFILE_DECORATION = 'com.linkedin.voyager.dash.deco.identity.profile.FullProfileWithEntities-118';

// Load config — contains company info, OAuth credentials, and auth mode
var config = {};
try {
  var configResult = await exec('cat ' + CONFIG_FILE);
  if (configResult.exitCode === 0 && configResult.stdout.trim()) {
    config = JSON.parse(configResult.stdout.trim());
  }
} catch (_) {}

var COMPANY_URN = config.companyUrn || 'urn:li:fsd_company:122314561';
var COMPANY_ID = config.companyId || '122314561';
var AUTH_MODE = config.auth || 'session'; // 'session' or 'oauth'

// ─── Argument Parsing ────────────────────────────────────────────────────────

const rawArgs = process.argv.slice(2);
const cmd = rawArgs[0] || '';
const positional = [];
const flags = {};

for (var i = 1; i < rawArgs.length; i++) {
  var arg = rawArgs[i];
  if (arg.startsWith('--')) {
    var eq = arg.indexOf('=');
    if (eq !== -1) {
      flags[arg.slice(2, eq)] = arg.slice(eq + 1);
    } else {
      var key = arg.slice(2);
      if (i + 1 < rawArgs.length && !rawArgs[i + 1].startsWith('--')) {
        flags[key] = rawArgs[++i];
      } else {
        flags[key] = 'true';
      }
    }
  } else {
    positional.push(arg);
  }
}

// ─── Input Validation ────────────────────────────────────────────────────────

function validateActivityId(id) {
  // Accept "7463311119181312000" or "urn:li:activity:7463311119181312000"
  if (/^\d+$/.test(id)) return 'urn:li:activity:' + id;
  if (/^urn:li:activity:\d+$/.test(id)) return id;
  console.error('Invalid activityId: must be digits or urn:li:activity:<digits>');
  process.exit(1);
}

function validateVanityName(name) {
  // LinkedIn vanity names: alphanumeric, hyphens, underscores, dots
  if (/^[A-Za-z0-9._-]+$/.test(name)) return name;
  // If it looks like a member URN, allow it
  if (/^ACoA[A-Za-z0-9_-]+$/.test(name)) return name;
  if (/^urn:li:/.test(name)) return name;
  console.error('Invalid profile identifier: must be a vanity name (alphanumeric/hyphens) or member URN');
  process.exit(1);
}

// ─── Tab Management ──────────────────────────────────────────────────────────

var _tabId = null;

async function ensureTab() {
  if (_tabId) return _tabId;

  var list = await exec('playwright-cli tab-list');
  if (list.exitCode !== 0) {
    console.error('Failed to list browser tabs. Ensure the browser is running.');
    process.exit(1);
  }
  // Match tab IDs (hex or other formats)
  var match = list.stdout.match(/\[([^\]]+)\]\s+https?:\/\/[^\s]*linkedin\.com/);
  if (match) {
    _tabId = match[1];
    return _tabId;
  }

  var r = await exec('playwright-cli open https://www.linkedin.com/company/' + COMPANY_ID + '/admin/page-posts/published/');
  if (r.exitCode !== 0) {
    console.error('Failed to open LinkedIn tab:', r.stderr || 'unknown error');
    process.exit(1);
  }
  var m = r.stdout.match(/targetId:\s*([^\s\]]+)/);
  _tabId = m ? m[1] : null;
  if (!_tabId) {
    console.error('Failed to open LinkedIn tab. Ensure LinkedIn is accessible.');
    process.exit(1);
  }

  await new Promise(function(resolve) { setTimeout(resolve, 3000); });
  return _tabId;
}

// ─── CSRF Token ──────────────────────────────────────────────────────────────

async function getCsrfToken(tabId) {
  var r = await exec('playwright-cli cookie-get JSESSIONID --tab=' + tabId);
  if (r.exitCode !== 0) {
    console.error('Failed to read LinkedIn cookies. Is the LinkedIn tab still open?');
    if (r.stderr) console.error('  ' + r.stderr.trim());
    process.exit(1);
  }
  var raw = r.stdout.trim();
  var match = raw.match(/JSESSIONID="([^"]+)"/);
  var token = match ? match[1] : raw.replace(/^"|"$/g, '');
  if (!token || token === 'undefined') {
    console.error('No JSESSIONID cookie found. Please log into LinkedIn in your browser.');
    process.exit(1);
  }
  return token;
}

// ─── Page Context API Helper ─────────────────────────────────────────────────

async function pageContextFetch(tabId, csrfToken, url, options) {
  var method = (options && options.method) || 'GET';
  var body = (options && options.body) ? JSON.stringify(options.body) : 'undefined';

  var jsCode = [
    '(async () => {',
    '  var opts = {',
    '    method: "' + method + '",',
    '    credentials: "include",',
    '    headers: {',
    '      "csrf-token": "' + csrfToken + '",',
    '      "x-restli-protocol-version": "2.0.0",',
    '      "accept": "application/vnd.linkedin.normalized+json+2.1",',
    '      "x-li-lang": "en_US"',
    method === 'POST' ? '      ,"content-type": "application/json; charset=UTF-8"' : '',
    method === 'POST' ? '      ,"x-li-pem-metadata": "Voyager - Sharing - CreateShare=sharing-create-content,Voyager - Organization - Admin=organization-create-post-as-page"' : '',
    '    }',
    body !== 'undefined' ? '    ,body: ' + JSON.stringify(body) : '',
    '  };',
    '  var resp = await fetch("' + url.replace(/"/g, '\\"') + '", opts);',
    '  var text = await resp.text();',
    '  if (!resp.ok) return JSON.stringify({ __error: resp.status, detail: text.substring(0, 500) });',
    '  return text;',
    '})()'
  ].join(' ');

  var result = await exec('playwright-cli eval --tab=' + tabId + ' ' + JSON.stringify(jsCode));
  if (result.exitCode !== 0) {
    throw new Error('Eval failed: ' + result.stderr);
  }

  var raw = result.stdout.trim();
  var parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    // Non-JSON response — likely a login wall or HTML error page
    var preview = raw.substring(0, 200);
    if (preview.includes('<html') || preview.includes('<!DOCTYPE')) {
      console.error('LinkedIn returned HTML instead of JSON. Session may have expired.');
      console.error('Please log into LinkedIn in your browser and try again.');
      process.exit(1);
    }
    throw new Error('Unexpected response (not JSON): ' + preview);
  }

  if (parsed && parsed.__error) {
    if (parsed.__error === 401 || parsed.__error === 403) {
      console.error('Auth failed (' + parsed.__error + '). Please log into LinkedIn in your browser.');
      process.exit(1);
    }
    throw new Error('API error ' + parsed.__error + ': ' + (parsed.detail || '').substring(0, 200));
  }

  return parsed;
}

// ─── Commands ────────────────────────────────────────────────────────────────

// --- POST ---

async function createPost(text) {
  return await createSharePost(text, null);
}

// Refactor of createPost that supports an optional media attachment. When
// mediaInfo is null behaves identically to the legacy text-only path; when
// non-null adds the `media` field on the same share-create mutation. The
// shape of `mediaInfo` differs by category:
//   VIDEO: { category: 'VIDEO', mediaUrn, recipes, nativeMediaSource }
//   IMAGE: { category: 'IMAGE', mediaUrn, altText?, tapTargets? }
// (For images LinkedIn resolves recipes server-side from the asset URN, so
// they are omitted from the payload; tapTargets default to [].)
async function createSharePost(text, mediaInfo) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  var post = {
    allowedCommentersScope: 'ALL',
    intendedShareLifeCycleState: 'PUBLISHED',
    origin: 'ORGANIZATION',
    visibilityDataUnion: { visibilityType: 'ANYONE' },
    commentary: { text: text, attributesV2: [] },
    nonMemberActorUrn: COMPANY_URN
  };
  if (mediaInfo) {
    if (mediaInfo.category === 'IMAGE') {
      // Image shape: LinkedIn resolves recipes server-side from the asset URN,
      // so `recipes` and `nativeMediaSource` are omitted. `tapTargets` is for
      // click-to-tag-people coordinates (out of scope; always [] here).
      post.media = {
        category: 'IMAGE',
        mediaUrn: mediaInfo.mediaUrn,
        tapTargets: mediaInfo.tapTargets || [],
        altText: mediaInfo.altText || ''
      };
    } else {
      post.media = {
        category: mediaInfo.category,
        mediaUrn: mediaInfo.mediaUrn,
        recipes: mediaInfo.recipes,
        nativeMediaSource: mediaInfo.nativeMediaSource
      };
    }
  }

  var payload = {
    variables: { post: post },
    queryId: GRAPHQL_CREATE_QUERY_ID,
    includeWebMetadata: true
  };

  var url = '/voyager/api/graphql?action=execute&queryId=' + GRAPHQL_CREATE_QUERY_ID;
  var data = await pageContextFetch(tabId, csrfToken, url, { method: 'POST', body: payload });

  var shareData = data && data.data && data.data.data && data.data.data.createContentcreationDashShares;
  var shareUrn = (shareData && (shareData.resourceKey || shareData['*entity'])) || 'unknown';

  // Resolve the real activity URN. Strategy:
  //   1. Walk data.included for any entityUrn matching urn:li:activity:<digits>,
  //      preferring the one nearest (by array index) to the new share URN entry.
  //   2. Fallback: query listPosts(5) and match by exact text.
  var activityUrn = null;
  if (data && Array.isArray(data.included)) {
    var shareIdx = -1;
    for (var ii = 0; ii < data.included.length; ii++) {
      var ent = data.included[ii] && data.included[ii].entityUrn;
      if (ent && ent.indexOf(shareUrn) !== -1) { shareIdx = ii; break; }
    }
    var candidates = [];
    for (var ij = 0; ij < data.included.length; ij++) {
      var entJ = data.included[ij] && data.included[ij].entityUrn;
      if (!entJ) continue;
      var am = entJ.match(/urn:li:activity:\d+/);
      if (am) candidates.push({ idx: ij, urn: am[0] });
    }
    if (candidates.length === 1) {
      activityUrn = candidates[0].urn;
    } else if (candidates.length > 1) {
      if (shareIdx >= 0) {
        candidates.sort(function(a, b) { return Math.abs(a.idx - shareIdx) - Math.abs(b.idx - shareIdx); });
      }
      activityUrn = candidates[0].urn;
    }
  }

  // Fallback: look up via listPosts. Never let lookup failure break success path.
  if (!activityUrn) {
    try {
      var listed = await listPosts(5);
      var match = null;
      if (listed && Array.isArray(listed.posts)) {
        for (var lp = 0; lp < listed.posts.length; lp++) {
          var p = listed.posts[lp];
          if (p && p.text === text && p.activityUrn) { match = p; break; }
        }
      }
      if (match) activityUrn = match.activityUrn;
    } catch (_) {}
  }

  var activityId = null;
  if (activityUrn) {
    var actMatch = activityUrn.match(/urn:li:activity:(\d+)/);
    if (actMatch) activityId = actMatch[1];
  }

  var resp = {
    success: true,
    shareUrn: shareUrn,
    url: activityUrn
      ? 'https://www.linkedin.com/feed/update/' + activityUrn
      : 'https://www.linkedin.com/feed/update/' + shareUrn
  };
  if (activityUrn) {
    resp.activityUrn = activityUrn;
    resp.activityId = activityId;
  } else {
    resp.note = "Could not resolve activity ID — run 'linkedin list' to find it.";
  }
  return resp;
}

// --- VIDEO POST ---

// Step 1 of the media upload pipeline: register the upload and obtain the
// asset URN and a singleUploadUrl to PUT the bytes to. Used for both video
// (PR #130, captured 2026-06-04) and image (this PR, captured 2026-06-05;
// HAR: linkedin-context/har/image-upload-2026-06-05.har). The endpoint is
// the same for both — only `mediaUploadType` differs.
//   kind: 'video' | 'image'
async function registerMediaUpload(tabId, csrfToken, kind, fileSize, filename) {
  var mediaUploadType;
  if (kind === 'video') mediaUploadType = 'VIDEO_SHARING';
  else if (kind === 'image') mediaUploadType = 'IMAGE_SHARING';
  else throw new Error('registerMediaUpload: unknown kind: ' + kind);

  var payload = {
    mediaUploadType: mediaUploadType,
    fileSize: fileSize,
    nonMemberActorUrn: COMPANY_URN,
    filename: filename
  };
  var data = await pageContextFetch(tabId, csrfToken, VIDEO_UPLOAD_METADATA_PATH, { method: 'POST', body: payload });
  var value = data && data.data && data.data.value;
  if (!value || !value.urn || !value.singleUploadUrl) {
    throw new Error('registerMediaUpload: unexpected response shape: ' + JSON.stringify(data).substring(0, 400));
  }
  if (value.type && value.type !== 'SINGLE') {
    throw new Error('registerMediaUpload: type=' + value.type + ' (MULTIPART chunked upload not yet supported — file a follow-up issue).');
  }
  return value;
}

// Backward-compat wrapper retained from PR #130.
async function registerVideoUpload(tabId, csrfToken, fileSize, filename) {
  return await registerMediaUpload(tabId, csrfToken, 'video', fileSize, filename);
}

// Step 2: PUT the raw media bytes to the singleUploadUrl from inside the
// LinkedIn page context (so cookies + Origin are correct). The bytes are
// base64-inlined into a temp .js file and decoded into a Blob in-browser.
// Works fine for ~3.4MB; for larger payloads consider MULTIPART (out of scope).
//   contentType: MIME type for the Blob and PUT (e.g. 'video/mp4', 'image/jpeg').
async function uploadMediaBytes(tabId, csrfToken, singleUploadUrl, mediaPath, singleUploadHeaders, contentType) {
  // Read bytes via fs (returns a latin-1 binary string in this runtime) and
  // base64-encode in-process. Avoids the GNU-only `base64 -w0` shell-out.
  var binStr;
  try {
    binStr = await fs.readFile(mediaPath);
  } catch (e) {
    throw new Error('Failed to read media file ' + mediaPath + ': ' + (e && e.message ? e.message : e));
  }
  if (typeof binStr !== 'string') {
    throw new Error('fs.readFile did not return a binary string for ' + mediaPath);
  }
  var b64 = btoa(binStr);

  var extraHeaders = {};
  if (singleUploadHeaders && typeof singleUploadHeaders === 'object') {
    Object.keys(singleUploadHeaders).forEach(function(k) { extraHeaders[k] = singleUploadHeaders[k]; });
  }

  var blobType = contentType || 'application/octet-stream';

  var script = [
    '(async () => {',
    '  const B64 = ' + JSON.stringify(b64) + ';',
    '  const URL_ = ' + JSON.stringify(singleUploadUrl) + ';',
    '  const EXTRA = ' + JSON.stringify(extraHeaders) + ';',
    '  const CSRF = ' + JSON.stringify(csrfToken) + ';',
    '  const TYPE = ' + JSON.stringify(blobType) + ';',
    '  const bin = atob(B64);',
    '  const bytes = new Uint8Array(bin.length);',
    '  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);',
    '  const blob = new Blob([bytes], { type: TYPE });',
    '  const headers = Object.assign({}, EXTRA, { "Csrf-Token": CSRF });',
    '  const resp = await fetch(URL_, { method: "PUT", body: blob, headers: headers, credentials: "include" });',
    '  return JSON.stringify({ status: resp.status, ok: resp.ok });',
    '})()'
  ].join('\n');

  // Write the script to a temp file and run via eval-file — keeps the giant
  // base64 blob out of the shell argv length budget. Use /shared (VFS) so the
  // playwright-cli runner can read the file regardless of host /tmp scoping.
  var tmpDir = '/shared/.cache/linkedin';
  await exec('mkdir -p ' + JSON.stringify(tmpDir));
  var tmpPath = tmpDir + '/media-upload-' + Date.now() + '-' + Math.random().toString(36).slice(2, 8) + '.js';
  await fs.writeFile(tmpPath, script);
  var r = await exec('playwright-cli eval-file ' + JSON.stringify(tmpPath) + ' --tab=' + tabId);
  await exec('rm -f ' + JSON.stringify(tmpPath)).catch(function() {});
  if (r.exitCode !== 0) {
    throw new Error('uploadMediaBytes eval failed: ' + (r.stderr || r.stdout));
  }
  var parsed;
  try { parsed = JSON.parse(r.stdout.trim()); } catch (e) {
    throw new Error('uploadMediaBytes: unexpected eval output: ' + r.stdout.substring(0, 200));
  }
  // LinkedIn's dms-uploads PUT may return 200 or 201 depending on the storage
  // backend variant — accept any 2xx (resp.ok in the eval payload).
  if (!parsed.ok) {
    throw new Error('Media PUT failed with status ' + parsed.status);
  }
  return parsed;
}

// Backward-compat wrapper retained from PR #130.
async function uploadVideoBytes(tabId, csrfToken, singleUploadUrl, videoPath, singleUploadHeaders) {
  return await uploadMediaBytes(tabId, csrfToken, singleUploadUrl, videoPath, singleUploadHeaders, 'video/mp4');
}

async function createVideoPost(text, videoPath) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  // Resolve size + basename via fs.stat — no shell-out, so the path is never
  // interpreted by bash (avoids $(...) command-substitution risk on hostile
  // paths like '/shared/$(rm -rf).mp4').
  var fileSize;
  try {
    var st = await fs.stat(videoPath);
    if (!st || !st.isFile) throw new Error('not a regular file');
    fileSize = st.size;
  } catch (e) {
    throw new Error('Cannot stat video file ' + videoPath + ': ' + (e && e.message ? e.message : e));
  }
  if (!fileSize || fileSize <= 0) throw new Error('Invalid file size for ' + videoPath);
  var filename = videoPath.split('/').pop();

  console.error('[linkedin video] Registering upload for ' + filename + ' (' + fileSize + ' bytes)...');
  var meta = await registerMediaUpload(tabId, csrfToken, 'video', fileSize, filename);
  console.error('[linkedin video] Asset: ' + meta.urn);

  console.error('[linkedin video] Uploading bytes...');
  await uploadMediaBytes(tabId, csrfToken, meta.singleUploadUrl, videoPath, meta.singleUploadHeaders, 'video/mp4');
  console.error('[linkedin video] Upload complete. Creating share...');

  return await createSharePost(text, {
    category: 'VIDEO',
    mediaUrn: meta.urn,
    recipes: meta.recipes,
    nativeMediaSource: 'PRE_RECORDED'
  });
}

// --- IMAGE POST ---

// Map a file extension to an image MIME type. LinkedIn accepts gif/jpeg/jpg/
// png/webp per the composer's <input accept=...> attribute.
var IMAGE_MIME_BY_EXT = {
  jpg: 'image/jpeg',
  jpeg: 'image/jpeg',
  png: 'image/png',
  gif: 'image/gif',
  webp: 'image/webp'
};

function detectImageContentType(imagePath) {
  var dot = imagePath.lastIndexOf('.');
  var ext = dot >= 0 ? imagePath.slice(dot + 1).toLowerCase() : '';
  var mime = IMAGE_MIME_BY_EXT[ext];
  if (!mime) {
    var supportedDotted = Object.keys(IMAGE_MIME_BY_EXT).map(function(e) { return '.' + e; }).join(', ');
    if (!ext) {
      throw new Error('Image file has no extension: ' + imagePath + ' (supported: ' + supportedDotted + ')');
    }
    throw new Error('Unrecognized image extension ".' + ext + '" on ' + imagePath + ' (supported: ' + supportedDotted + ')');
  }
  return mime;
}

async function createImagePost(text, imagePath, options) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var altText = (options && options.altText) || '';

  var contentType = detectImageContentType(imagePath);

  // Resolve size + basename via fs.stat — no shell-out, so the path is never
  // interpreted by bash (avoids $(...) command-substitution risk on hostile
  // paths like '/shared/$(rm -rf).jpg').
  var fileSize;
  try {
    var st = await fs.stat(imagePath);
    if (!st || !st.isFile) throw new Error('not a regular file');
    fileSize = st.size;
  } catch (e) {
    throw new Error('Cannot stat image file ' + imagePath + ': ' + (e && e.message ? e.message : e));
  }
  if (!fileSize || fileSize <= 0) throw new Error('Invalid file size for ' + imagePath);
  var filename = imagePath.split('/').pop();

  console.error('[linkedin image] Registering upload for ' + filename + ' (' + fileSize + ' bytes, ' + contentType + ')...');
  var meta = await registerMediaUpload(tabId, csrfToken, 'image', fileSize, filename);
  console.error('[linkedin image] Asset: ' + meta.urn);

  console.error('[linkedin image] Uploading bytes...');
  await uploadMediaBytes(tabId, csrfToken, meta.singleUploadUrl, imagePath, meta.singleUploadHeaders, contentType);
  console.error('[linkedin image] Upload complete. Creating share...');

  return await createSharePost(text, {
    category: 'IMAGE',
    mediaUrn: meta.urn,
    altText: altText,
    tapTargets: []
  });
}

// --- LIST ---

async function listPosts(limit) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var count = limit || 10;

  var url = '/voyager/api/graphql?includeWebMetadata=true&variables=(organizationalPageFeedUseCase:ADMIN_ORGANIZATIONAL_PAGE_POSTS,organizationalPageIdOrUniversalName:(organizationalPageUUId:' + COMPANY_ID + '),start:0,count:' + count + ')&queryId=' + GRAPHQL_LIST_QUERY_ID;

  var data = await pageContextFetch(tabId, csrfToken, url);

  var posts = [];
  var activityCounts = {};
  var analyticsMap = {};

  // Extract social activity counts and organic analytics
  if (data.included) {
    data.included.forEach(function(item) {
      if (item.entityUrn && item.entityUrn.startsWith('urn:li:fsd_socialActivityCounts:')) {
        var actId = item.entityUrn.replace('urn:li:fsd_socialActivityCounts:', '');
        activityCounts[actId] = {
          comments: item.numComments || 0,
          reposts: item.numShares || 0,
          likes: item.numLikes || 0,
          reactions: item.reactionTypeCounts || []
        };
      }
      // Extract organic analytics (impressions, clicks, engagement rate)
      if (item.organicAnalytics && item.entityUrn) {
        var analyticsMatch = item.entityUrn.match(/urn:li:activity:\d+/);
        if (analyticsMatch) {
          analyticsMap[analyticsMatch[0]] = {
            impressions: item.organicAnalytics.impressions || 0,
            clicks: item.organicAnalytics.clicks || 0,
            clickThroughRate: item.organicAnalytics.clickThroughRate || 0,
            engagementRate: item.organicAnalytics.engagementRate || 0
          };
        }
      }
    });

    // Extract posts with commentary (exclude comments — they have threadUrn or fsd_comment in entityUrn)
    data.included.forEach(function(item) {
      if (item.commentary && item.commentary.text) {
        // Skip comments (they show up in included but aren't posts)
        if (item.entityUrn && item.entityUrn.includes('fsd_comment')) return;
        if (item.threadUrn) return;

        var text = typeof item.commentary.text === 'string' ? item.commentary.text : item.commentary.text.text;
        if (!text) return;

        // Find the activity URN associated with this update
        var activityUrn = '';
        if (item.entityUrn) {
          var actMatch = item.entityUrn.match(/urn:li:activity:\d+/);
          if (actMatch) activityUrn = actMatch[0];
        }

        var stats = activityCounts[activityUrn] || {};

        // Resolve a published timestamp. Check the post item first, then walk
        // included for related update/share/activity entries.
        function pickTs(o) {
          if (!o) return null;
          if (typeof o.firstPublishedAt === 'number') return o.firstPublishedAt;
          if (typeof o.publishedAt === 'number') return o.publishedAt;
          if (typeof o.createdAt === 'number') return o.createdAt;
          if (typeof o.createdTime === 'number') return o.createdTime;
          return null;
        }
        var publishedAt = pickTs(item);
        if (publishedAt === null && activityUrn && data.included) {
          for (var ri = 0; ri < data.included.length; ri++) {
            var rel = data.included[ri];
            if (!rel || !rel.entityUrn) continue;
            if (rel.entityUrn === item.entityUrn) continue;
            if (rel.entityUrn.indexOf(activityUrn) === -1) continue;
            var t = pickTs(rel);
            if (t !== null) { publishedAt = t; break; }
          }
        }
        var publishedAtIso = publishedAt !== null ? new Date(publishedAt).toISOString() : null;

        var analytics = analyticsMap[activityUrn] || {};

        posts.push({
          activityUrn: activityUrn,
          text: text,
          comments: stats.comments || 0,
          reposts: stats.reposts || 0,
          likes: stats.likes || 0,
          impressions: analytics.impressions || null,
          clicks: analytics.clicks || null,
          clickThroughRate: analytics.clickThroughRate || null,
          engagementRate: analytics.engagementRate || null,
          publishedAt: publishedAt,
          publishedAtIso: publishedAtIso,
          url: activityUrn ? 'https://www.linkedin.com/feed/update/' + activityUrn : ''
        });
      }
    });
  }

  return { total: posts.length, posts: posts };
}

// --- COMMENTS ---

async function getComments(activityId) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  activityId = validateActivityId(activityId);

  // LinkedIn RESTLI format: outer parens/commas are literal, but URN colons and inner parens are percent-encoded
  var encodedActivity = activityId.replace(/:/g, '%3A');
  var encodedCompanyUrn = COMPANY_URN.replace(/:/g, '%3A');
  var socialDetailEncoded = 'urn%3Ali%3Afsd_socialDetail%3A%28' + encodedActivity + '%2C' + encodedActivity + '%2Curn%3Ali%3AhighlightedReply%3A-%29';
  var url = '/voyager/api/graphql?includeWebMetadata=true&variables=(count:20,numReplies:3,nonMemberActorUrn:' + encodedCompanyUrn + ',socialDetailUrn:' + socialDetailEncoded + ',sortOrder:RELEVANCE,start:0)&queryId=' + GRAPHQL_COMMENTS_QUERY_ID;

  var data = await pageContextFetch(tabId, csrfToken, url);

  var comments = [];
  if (data.included) {
    data.included.forEach(function(item) {
      if (item.commentary && item.commentary.text && item.commenter) {
        var text = typeof item.commentary.text === 'string' ? item.commentary.text : item.commentary.text.text;
        var commenterName = '';
        var commenterUrn = '';

        // Try to resolve commenter info from included data
        if (item.commenter && item.commenter.actorUrn) {
          commenterUrn = item.commenter.actorUrn;
          // Try to find name in included
          data.included.forEach(function(inc) {
            if (inc.entityUrn === commenterUrn || (inc.entityUrn && inc.entityUrn.includes(commenterUrn))) {
              commenterName = (inc.firstName ? inc.firstName + ' ' + inc.lastName : inc.name) || '';
            }
          });
        }

        comments.push({
          commentUrn: item.entityUrn || '',
          text: text,
          commenter: commenterName || commenterUrn,
          createdAt: item.createdTime || null
        });
      }
    });
  }

  return { activityId: activityId, total: comments.length, comments: comments };
}

// --- COMMENT (create) ---

async function addComment(activityId, text) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  activityId = validateActivityId(activityId);

  var payload = {
    commentary: {
      text: text,
      attributesV2: [],
      '$type': 'com.linkedin.voyager.dash.common.text.TextViewModel'
    },
    threadUrn: activityId,
    nonMemberActorUrn: COMPANY_URN
  };

  var url = '/voyager/api/voyagerSocialDashNormComments?decorationId=' + COMMENT_CREATE_DECORATION;
  var data = await pageContextFetch(tabId, csrfToken, url, { method: 'POST', body: payload });

  var commentUrn = (data && data.data && data.data.entityUrn) || 'created';
  return { success: true, commentUrn: commentUrn, activityId: activityId };
}

// --- REACTIONS ---

async function getReactions(activityId) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  activityId = validateActivityId(activityId);

  // Reactions are included in the feed listing data via socialActivityCounts
  // For detailed per-reactor breakdown, we use the reactors endpoint
  var encodedActivity2 = activityId.replace(/:/g, '%3A');
  var socialDetailEncoded2 = 'urn%3Ali%3Afsd_socialDetail%3A%28' + encodedActivity2 + '%2C' + encodedActivity2 + '%2Curn%3Ali%3AhighlightedReply%3A-%29';
  var url = '/voyager/api/graphql?includeWebMetadata=true&variables=(count:20,socialDetailUrn:' + socialDetailEncoded2 + ',start:0)&queryId=voyagerSocialDashReactors.78aa0bb67da9cc9ca4d58fd093d72e6b';

  try {
    var data = await pageContextFetch(tabId, csrfToken, url);

    var reactors = [];
    if (data.included) {
      data.included.forEach(function(item) {
        if (item.reactorLockup || item.reactionType) {
          reactors.push({
            name: item.title || item.name || '',
            reactionType: item.reactionType || 'LIKE',
            entityUrn: item.entityUrn || ''
          });
        }
        // Also look for profile-like entries that are reactors
        if (item.firstName && item.lastName && !item.commentary) {
          reactors.push({
            name: item.firstName + ' ' + item.lastName,
            headline: item.headline || '',
            entityUrn: item.entityUrn || ''
          });
        }
      });
    }

    return { activityId: activityId, total: reactors.length, reactors: reactors };
  } catch (e) {
    // Fall back to just showing counts from the feed
    var listData = await listPosts(20);
    var post = listData.posts.find(function(p) { return p.activityUrn === activityId; });
    if (post) {
      return { activityId: activityId, likes: post.likes, comments: post.comments, reposts: post.reposts };
    }
    throw e;
  }
}

// --- PROFILE ---

async function getProfile(identifier) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  identifier = validateVanityName(identifier);

  // If it's a URN, use directly. If it's a vanity name, navigate and extract.
  if (identifier.startsWith('ACoA') || identifier.startsWith('urn:li:')) {
    // It's a member URN — query directly
    var memberUrn = identifier.replace('urn:li:fsd_profile:', '').replace('urn:li:member:', '');
    return await fetchProfileByUrn(tabId, csrfToken, memberUrn);
  }

  // It's a vanity name — navigate to the profile and extract data from the page
  var profileUrl = 'https://www.linkedin.com/in/' + encodeURIComponent(identifier) + '/';
  await exec('playwright-cli goto ' + JSON.stringify(profileUrl) + ' --tab=' + tabId);
  await new Promise(function(resolve) { setTimeout(resolve, 3000); });

  // Get the snapshot for structured data
  var snap = await exec('playwright-cli snapshot --tab=' + tabId);
  var lines = snap.stdout.split('\n');

  var profile = { vanityName: identifier, url: profileUrl };

  // Parse key info from accessibility tree
  for (var j = 0; j < lines.length; j++) {
    var line = lines[j];
    if (line.includes('heading') && !profile.name && j < 30) {
      var nameMatch = line.match(/heading "([^"]+)"/);
      if (nameMatch && !nameMatch[1].includes('navigation') && !nameMatch[1].includes('notification')) {
        profile.name = nameMatch[1];
      }
    }
    if (line.includes('text "') && profile.name && !profile.headline) {
      var headlineMatch = line.match(/text "([^"]+)"/);
      if (headlineMatch && headlineMatch[1].length > 5 && headlineMatch[1].length < 200 && !headlineMatch[1].includes('notification')) {
        profile.headline = headlineMatch[1];
      }
    }
  }

  // Also try to extract the member URN from the page to get full data
  var urnResult = await exec('playwright-cli eval --tab=' + tabId + ' "(() => { var html = document.body.innerHTML; var m = html.match(/ACoA[A-Za-z0-9_-]{30,50}/); return m ? m[0] : null; })()"');
  var memberUrnFromPage = urnResult.stdout.trim();

  if (memberUrnFromPage && memberUrnFromPage !== 'null') {
    try {
      var fullProfile = await fetchProfileByUrn(tabId, csrfToken, memberUrnFromPage);
      return Object.assign(profile, fullProfile);
    } catch (e) {
      // Fall back to snapshot data
    }
  }

  return profile;
}

async function fetchProfileByUrn(tabId, csrfToken, memberUrn) {
  var url = '/voyager/api/identity/dash/profiles?q=memberIdentity&memberIdentity=' + memberUrn + '&decorationId=' + PROFILE_DECORATION;
  var data = await pageContextFetch(tabId, csrfToken, url);

  var profile = {};
  if (data.included) {
    // Find main profile object
    data.included.forEach(function(item) {
      if (item.firstName && item.entityUrn && item.entityUrn.includes(memberUrn)) {
        profile.name = item.firstName + ' ' + item.lastName;
        profile.firstName = item.firstName;
        profile.lastName = item.lastName;
        profile.headline = item.headline || '';
        profile.publicIdentifier = item.publicIdentifier || '';
        profile.industryName = item.industryName || '';
        profile.geoLocationName = item.geoLocationName || '';
        profile.summary = item.summary || '';
        profile.url = 'https://www.linkedin.com/in/' + (item.publicIdentifier || memberUrn) + '/';
        profile.memberUrn = memberUrn;
      }
    });

    // Extract positions/experience
    var positions = [];
    data.included.forEach(function(item) {
      if (item.title && item.companyName && item.entityUrn && item.entityUrn.includes('profilePosition')) {
        positions.push({
          title: item.title,
          company: item.companyName,
          current: !item.timePeriod || !item.timePeriod.endDate
        });
      }
    });
    if (positions.length > 0) profile.positions = positions;
  }

  return profile;
}

// --- MONDAY PROTOCOL ---

async function monday() {
  var limit = parseInt(flags['limit'] || '20');
  var dateStr = flags['date'] || '7d';

  // Parse date into a cutoff timestamp
  var dateMatch = dateStr.match(/^(\d+)([dwh])$/);
  var cutoffMs = Date.now();
  if (dateMatch) {
    var n = parseInt(dateMatch[1]);
    var unit = dateMatch[2];
    var multiplier = unit === 'w' ? 7 * 86400000 : unit === 'h' ? 3600000 : 86400000;
    cutoffMs = Date.now() - n * multiplier;
  } else {
    cutoffMs = Date.now() - 7 * 86400000;
  }

  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  var items = [];
  var companyName = config.companyName || 'Company page';

  // Fetch recent posts with engagement
  try {
    var postData = await listPosts(limit);
    for (var k = 0; k < postData.posts.length; k++) {
      var post = postData.posts[k];
      // Include posts that have new comments or reactions
      if (post.comments > 0 || post.likes > 0 || post.reposts > 0) {
        if (typeof post.publishedAt === 'number' && post.publishedAt < cutoffMs) continue;
        var itemDate = post.publishedAtIso || null;
        items.push({
          source: 'linkedin',
          type: 'engagement',
          id: 'linkedin-engagement-' + post.activityUrn,
          title: 'LinkedIn post engagement: ' + post.comments + ' comments, ' + post.likes + ' likes, ' + post.reposts + ' reposts',
          body: post.text,
          url: post.url,
          from: companyName,
          date: itemDate,
          ts: itemDate,
          comments: post.comments,
          likes: post.likes,
          reposts: post.reposts
        });
      }
    }
  } catch (e) {
    console.error('[linkedin monday] WARNING: failed to fetch posts: ' + e.message);
  }

  // Fetch unread comments across recent posts
  try {
    var recentPosts = await listPosts(5);
    for (var m = 0; m < recentPosts.posts.length; m++) {
      var p = recentPosts.posts[m];
      if (p.comments > 0 && p.activityUrn) {
        var commentsData = await getComments(p.activityUrn);
        for (var c = 0; c < commentsData.comments.length; c++) {
          var comment = commentsData.comments[c];
          var commentDate = comment.createdAt ? new Date(comment.createdAt).toISOString() : new Date().toISOString();
          var commentMs = comment.createdAt ? new Date(comment.createdAt).getTime() : Date.now();

          // Apply --date cutoff: skip comments older than the window
          if (commentMs < cutoffMs) continue;

          items.push({
            source: 'linkedin',
            type: 'comment',
            id: 'linkedin-comment-' + (comment.commentUrn || c),
            title: 'Comment on ' + companyName + ' post from ' + (comment.commenter || 'someone'),
            body: comment.text,
            url: p.url,
            from: comment.commenter || 'unknown',
            date: commentDate,
            ts: commentDate
          });
        }
      }
    }
  } catch (e) {
    console.error('[linkedin monday] WARNING: failed to fetch comments: ' + e.message);
  }

  return items;
}

// ─── Watch (cron-based comment polling) ──────────────────────────────────────

const WATCH_STATE_FILE = '/workspace/skills/linkedin/.watch-state.json';
const WATCH_CONFIG_FILE = '/workspace/skills/linkedin/.watch-config.json';

async function loadWatchState() {
  try {
    var r = await exec('cat ' + WATCH_STATE_FILE);
    if (r.exitCode === 0 && r.stdout.trim()) return JSON.parse(r.stdout.trim());
  } catch (_) {}
  return { commentCounts: {}, lastCheck: null };
}

async function saveWatchState(state) {
  await fs.writeFile(WATCH_STATE_FILE, JSON.stringify(state, null, 2));
}

async function loadWatchConfig() {
  try {
    var r = await exec('cat ' + WATCH_CONFIG_FILE);
    if (r.exitCode === 0 && r.stdout.trim()) return JSON.parse(r.stdout.trim());
  } catch (_) {}
  return null;
}

async function saveWatchConfig(config) {
  await fs.writeFile(WATCH_CONFIG_FILE, JSON.stringify(config, null, 2));
}

async function setupWatch(scoop, interval) {
  var cronInterval = interval || '*/5 * * * *'; // default: every 5 minutes

  // Check for existing watch
  var existing = await loadWatchConfig();
  if (existing && !flags.force) {
    console.error('Already watching (scoop: ' + existing.scoop + ', cron: ' + existing.cronId + ').');
    console.error('Use --force to replace.');
    process.exit(1);
  }

  // Clean up old cron if exists
  if (existing && existing.cronId) {
    await exec('crontask delete ' + existing.cronId).catch(function() {});
  }

  // Create SLICC webhook routed to target scoop
  var whResult = await exec('webhook create --scoop=' + scoop + ' --name=linkedin-comments');
  if (whResult.exitCode !== 0) {
    console.error('Failed to create webhook:', whResult.stderr);
    process.exit(1);
  }
  var webhookInfo = whResult.stdout.trim();
  var webhookUrl = '';
  var webhookId = '';
  try {
    var parsed = JSON.parse(webhookInfo);
    webhookUrl = parsed.url;
    webhookId = parsed.id;
  } catch (_) {
    // Try to extract URL from output
    var urlMatch = webhookInfo.match(/https?:\/\/\S+/);
    webhookUrl = urlMatch ? urlMatch[0] : webhookInfo;
    webhookId = webhookInfo;
  }

  // Create a cron task that runs linkedin _poll
  var cronResult = await exec('crontask create --name=linkedin-comment-poll --scoop=' + scoop + ' --cron="' + cronInterval + '"');
  var cronId = '';
  if (cronResult.exitCode === 0) {
    try {
      var cronParsed = JSON.parse(cronResult.stdout.trim());
      cronId = cronParsed.id || cronResult.stdout.trim();
    } catch (_) {
      cronId = cronResult.stdout.trim();
    }
  }

  var config = {
    scoop: scoop,
    webhookUrl: webhookUrl,
    webhookId: webhookId,
    cronId: cronId,
    cronInterval: cronInterval,
    createdAt: new Date().toISOString()
  };
  await saveWatchConfig(config);

  // Initialize state with current comment counts
  var postData = await listPosts(10);
  var commentCounts = {};
  postData.posts.forEach(function(p) {
    if (p.activityUrn) commentCounts[p.activityUrn] = p.comments;
  });
  await saveWatchState({ commentCounts: commentCounts, lastCheck: new Date().toISOString() });

  return config;
}

async function teardownWatch() {
  var config = await loadWatchConfig();
  if (!config) {
    console.error('No active watch.');
    process.exit(1);
  }

  // Delete webhook
  if (config.webhookId) {
    await exec('webhook delete ' + config.webhookId).catch(function() {});
  }

  // Delete cron task
  if (config.cronId) {
    await exec('crontask delete ' + config.cronId).catch(function() {});
  }

  // Remove config and state files
  await fs.rm(WATCH_CONFIG_FILE).catch(function() {});
  await fs.rm(WATCH_STATE_FILE).catch(function() {});

  return { stopped: true, was: config };
}

async function pollForNewComments() {
  // Called by the cron task — checks for new comments and fires webhooks
  var config = await loadWatchConfig();
  if (!config) return { skipped: true, reason: 'no watch configured' };

  var state = await loadWatchState();
  var postData = await listPosts(10);
  var newComments = [];

  for (var idx = 0; idx < postData.posts.length; idx++) {
    var post = postData.posts[idx];
    if (!post.activityUrn) continue;

    var prevCount = state.commentCounts[post.activityUrn] || 0;
    var currentCount = post.comments;

    if (currentCount > prevCount) {
      // New comments detected — fetch them
      try {
        var commentsData = await getComments(post.activityUrn);
        // Take only the new ones (assume they're at the top)
        var newCount = currentCount - prevCount;
        var recent = commentsData.comments.slice(0, newCount);
        recent.forEach(function(c) {
          newComments.push({
            activityUrn: post.activityUrn,
            postText: post.text.substring(0, 100),
            postUrl: post.url,
            commentText: c.text,
            commenter: c.commenter,
            commentUrn: c.commentUrn
          });
        });
      } catch (e) {
        console.error('[linkedin poll] Failed to fetch comments for ' + post.activityUrn + ': ' + e.message);
      }
    }

    state.commentCounts[post.activityUrn] = currentCount;
  }

  state.lastCheck = new Date().toISOString();
  await saveWatchState(state);

  // Fire webhook for each new comment
  if (newComments.length > 0 && config.webhookUrl) {
    for (var ci = 0; ci < newComments.length; ci++) {
      var payload = {
        type: 'linkedin-comment',
        event: 'new-comment',
        data: newComments[ci]
      };
      await exec('curl -s -X POST -H "Content-Type: application/json" -d ' + JSON.stringify(JSON.stringify(payload)) + ' ' + JSON.stringify(config.webhookUrl)).catch(function() {});
    }
  }

  return { checked: postData.posts.length, newComments: newComments.length, comments: newComments };
}

// ─── Messaging Commands ──────────────────────────────────────────────────────

const INBOX_QUERY_ID = 'messengerConversations.0d5e6781bbee71c3e51c8843c6519f48';
const MESSAGES_QUERY_ID = 'messengerMessages.5846eeb71c981f11e0134cb6626cc314';
const SEARCH_CONTACTS_QUERY_ID = 'voyagerMessagingDashMessagingTypeahead.7f566173ac0c94b510b3dc2b2a6763d4';
const FIND_CONVERSATION_QUERY_ID = 'messengerConversations.9c3ab648b616451570c715e4a184465e';

// Cache for the signed-in viewer's profile URN (used as mailboxUrn for messaging)
var _viewerProfileUrn = null;

async function getMailboxUrn(tabId, csrfToken) {
  if (_viewerProfileUrn) return _viewerProfileUrn;

  var data = await pageContextFetch(tabId, csrfToken, '/voyager/api/me');
  var miniUrn = data && data.miniProfile && data.miniProfile.entityUrn;
  if (!miniUrn || typeof miniUrn !== 'string') {
    console.error('Could not determine viewer profile URN from /voyager/api/me. Please log into LinkedIn in your browser.');
    process.exit(1);
  }
  // fs_miniProfile and fsd_profile use the same identity token after the colon
  _viewerProfileUrn = miniUrn.replace('urn:li:fs_miniProfile:', 'urn:li:fsd_profile:');
  return _viewerProfileUrn;
}

function generateUUID() {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
    var r = Math.random() * 16 | 0;
    var v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

function formatTimestamp(ms) {
  if (!ms) return '';
  var d = new Date(ms);
  var now = new Date();
  var diffMs = now - d;
  var diffMins = Math.floor(diffMs / 60000);
  if (diffMins < 1) return 'just now';
  if (diffMins < 60) return diffMins + 'm ago';
  var diffHours = Math.floor(diffMins / 60);
  if (diffHours < 24) return diffHours + 'h ago';
  var diffDays = Math.floor(diffHours / 24);
  if (diffDays < 7) return diffDays + 'd ago';
  return d.toISOString().split('T')[0];
}

async function messagingFetch(tabId, csrfToken, url, options) {
  var method = (options && options.method) || 'GET';
  var body = (options && options.body) ? JSON.stringify(options.body) : 'undefined';

  var jsCode = [
    '(async () => {',
    '  var opts = {',
    '    method: "' + method + '",',
    '    credentials: "include",',
    '    headers: {',
    '      "csrf-token": "' + csrfToken + '",',
    '      "x-restli-protocol-version": "2.0.0",',
    '      "accept": "' + ((options && options.accept) || (method === 'POST' ? 'application/json' : 'application/graphql')) + '",',
    '      "x-li-lang": "en_US"',
    method === 'POST' ? '      ,"content-type": "application/json; charset=UTF-8"' : '',
    method === 'POST' ? '      ,"x-li-page-instance": "urn:li:page:d_flagship3_messaging;slicc"' : '',
    '    }',
    body !== 'undefined' ? '    ,body: ' + JSON.stringify(body) : '',
    '  };',
    '  var resp = await fetch("' + url.replace(/"/g, '\\"') + '", opts);',
    '  var text = await resp.text();',
    '  if (!resp.ok) return JSON.stringify({ __error: resp.status, detail: text.substring(0, 500) });',
    '  return text;',
    '})()'
  ].join(' ');

  var evalResult = await exec('playwright-cli eval --tab=' + tabId + ' ' + JSON.stringify(jsCode));
  if (evalResult.exitCode !== 0) {
    throw new Error('Eval failed: ' + evalResult.stderr);
  }

  var raw = evalResult.stdout.trim();
  var parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (e) {
    var preview = raw.substring(0, 200);
    if (preview.includes('<html') || preview.includes('<!DOCTYPE')) {
      console.error('LinkedIn returned HTML instead of JSON. Session may have expired.');
      process.exit(1);
    }
    throw new Error('Unexpected response (not JSON): ' + preview);
  }

  if (parsed && parsed.__error) {
    if (parsed.__error === 401 || parsed.__error === 403) {
      console.error('Auth failed (' + parsed.__error + '). Please log into LinkedIn in your browser.');
      process.exit(1);
    }
    throw new Error('API error ' + parsed.__error + ': ' + (parsed.detail || '').substring(0, 200));
  }

  return parsed;
}

// --- INBOX ---

async function getInbox(options) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var limit = (options && options.limit) || 20;
  var unreadOnly = (options && options.unread) || false;

  var mailboxUrn = await getMailboxUrn(tabId, csrfToken);
  var encodedMailbox = encodeURIComponent(mailboxUrn);
  var url = '/voyager/api/voyagerMessagingGraphQL/graphql?queryId=' + INBOX_QUERY_ID + '&variables=(mailboxUrn:' + encodedMailbox + ')';

  var data = await messagingFetch(tabId, csrfToken, url);

  var conversations = [];
  var elements = [];

  // Navigate response structure
  if (data && data.data && data.data.messengerConversationsBySyncToken && data.data.messengerConversationsBySyncToken.elements) {
    elements = data.data.messengerConversationsBySyncToken.elements;
  }

  for (var ci = 0; ci < elements.length && conversations.length < limit; ci++) {
    var conv = elements[ci];
    if (!conv) continue;

    var isUnread = conv.read === false || (conv.unreadCount && conv.unreadCount > 0);
    if (unreadOnly && !isUnread) continue;

    // Extract participants
    var participants = [];
    if (conv.conversationParticipants && Array.isArray(conv.conversationParticipants)) {
      conv.conversationParticipants.forEach(function(p) {
        if (p && p.participantType && p.participantType.member) {
          var member = p.participantType.member;
          var name = '';
          if (member.firstName && member.firstName.text) name += member.firstName.text;
          if (member.lastName && member.lastName.text) name += (name ? ' ' : '') + member.lastName.text;
          if (name) participants.push(name);
        }
      });
    }

    // Extract last message preview
    var lastMessage = '';
    var lastSender = '';
    if (conv.messages && Array.isArray(conv.messages) && conv.messages.length > 0) {
      var lastMsg = conv.messages[0];
      if (lastMsg && lastMsg.body && lastMsg.body.text) lastMessage = lastMsg.body.text;
      if (lastMsg && lastMsg.sender && lastMsg.sender.participantType && lastMsg.sender.participantType.member) {
        var senderMember = lastMsg.sender.participantType.member;
        if (senderMember.firstName && senderMember.firstName.text) lastSender = senderMember.firstName.text;
      }
    }

    conversations.push({
      conversationUrn: conv.entityUrn || '',
      participants: participants,
      lastMessage: lastMessage.substring(0, 120),
      lastSender: lastSender,
      unread: isUnread,
      unreadCount: conv.unreadCount || 0,
      lastActivityAt: conv.lastActivityAt || null,
      lastActivityAgo: formatTimestamp(conv.lastActivityAt)
    });
  }

  if (flags['json'] === 'true') {
    return { total: conversations.length, conversations: conversations };
  }

  // Human-readable output
  var output = [];
  output.push('\x1b[1mInbox' + (unreadOnly ? ' (unread only)' : '') + '\x1b[0m  \u2014  ' + conversations.length + ' conversations\n');
  conversations.forEach(function(c) {
    var unreadMarker = c.unread ? '\x1b[33m\u25cf\x1b[0m ' : '  ';
    var names = c.participants.join(', ') || '(unknown)';
    var preview = c.lastMessage ? (c.lastSender ? c.lastSender + ': ' : '') + c.lastMessage : '(no messages)';
    output.push(unreadMarker + '\x1b[1m' + names + '\x1b[0m  \x1b[2m' + c.lastActivityAgo + '\x1b[0m');
    output.push('  ' + preview);
    output.push('  \x1b[2m' + c.conversationUrn + '\x1b[0m');
    output.push('');
  });

  console.log(output.join('\n'));
  return null; // already printed
}

// --- MESSAGES ---

async function getMessages(conversationUrn, options) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var limit = (options && options.limit) || 20;

  // LinkedIn requires (, ), and , to be percent-encoded inside variable values
  var encodedConv = encodeURIComponent(conversationUrn).replace(/\(/g, '%28').replace(/\)/g, '%29').replace(/,/g, '%2C').replace(/=/g, '%3D');
  var url = '/voyager/api/voyagerMessagingGraphQL/graphql?queryId=' + MESSAGES_QUERY_ID + '&variables=(conversationUrn:' + encodedConv + ')';

  var data = await messagingFetch(tabId, csrfToken, url);

  var messages = [];
  var elements = [];

  if (data && data.data && data.data.messengerMessagesBySyncToken && data.data.messengerMessagesBySyncToken.elements) {
    elements = data.data.messengerMessagesBySyncToken.elements;
  }

  for (var mi = 0; mi < elements.length && messages.length < limit; mi++) {
    var msg = elements[mi];
    if (!msg) continue;

    var senderName = '';
    if (msg.sender && msg.sender.participantType && msg.sender.participantType.member) {
      var member = msg.sender.participantType.member;
      if (member.firstName && member.firstName.text) senderName += member.firstName.text;
      if (member.lastName && member.lastName.text) senderName += (senderName ? ' ' : '') + member.lastName.text;
    }

    var msgText = '';
    if (msg.body && msg.body.text) msgText = msg.body.text;

    messages.push({
      sender: senderName,
      text: msgText,
      deliveredAt: msg.deliveredAt || null,
      deliveredAgo: formatTimestamp(msg.deliveredAt)
    });
  }

  // Messages come newest-first from API; reverse for chronological display
  messages.reverse();

  if (flags['json'] === 'true') {
    return { conversationUrn: conversationUrn, total: messages.length, messages: messages };
  }

  // Human-readable output
  var output = [];
  output.push('\x1b[1mConversation\x1b[0m  \x1b[2m' + conversationUrn + '\x1b[0m\n');
  messages.forEach(function(m) {
    output.push('\x1b[1m' + (m.sender || 'Unknown') + '\x1b[0m  \x1b[2m' + m.deliveredAgo + '\x1b[0m');
    output.push('  ' + m.text);
    output.push('');
  });

  console.log(output.join('\n'));
  return null; // already printed
}

// --- SEND MESSAGE ---

async function sendMessage(conversationUrn, messageText) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var mailboxUrn = await getMailboxUrn(tabId, csrfToken);

  var payload = {
    message: {
      body: { attributes: [], text: messageText },
      renderContentUnions: [],
      conversationUrn: conversationUrn,
      originToken: generateUUID()
    },
    mailboxUrn: mailboxUrn,
    dedupeByClientGeneratedToken: false
  };

  var url = '/voyager/api/voyagerMessagingDashMessengerMessages?action=createMessage';
  await messagingFetch(tabId, csrfToken, url, { method: 'POST', body: payload });

  return { success: true, conversationUrn: conversationUrn, message: messageText.substring(0, 80) };
}

// --- SEARCH CONTACTS ---

async function searchContacts(query) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);

  var encodedQuery = encodeURIComponent(query);
  var url = '/voyager/api/graphql?includeWebMetadata=true&variables=(keyword:' + encodedQuery + ',types:List(CONNECTIONS,GROUP_THREADS,PEOPLE,COWORKERS))&queryId=' + SEARCH_CONTACTS_QUERY_ID;

  var data = await messagingFetch(tabId, csrfToken, url, { accept: "application/vnd.linkedin.normalized+json+2.1" });

  var contacts = [];

  // Navigate the GraphQL response — look for typeahead results in included or data
  if (data && data.included && Array.isArray(data.included)) {
    data.included.forEach(function(item) {
      if (!item) return;
      // Look for profile-like items with firstName/lastName
      if (item.firstName && item.lastName && item.entityUrn && item.entityUrn.includes('fsd_profile')) {
        contacts.push({
          name: item.firstName + ' ' + item.lastName,
          profileUrn: item.entityUrn,
          headline: item.headline || ''
        });
      }
      // Also handle items with title.text pattern (typeahead results)
      if (item.title && item.title.text && item.entityUrn) {
        var urn = '';
        if (item.entityUrn.includes('fsd_profile')) {
          urn = item.entityUrn;
        } else if (item.memberProfileUrn) {
          urn = item.memberProfileUrn;
        } else if (item.targetUrn) {
          urn = item.targetUrn;
        }
        if (urn && !contacts.find(function(c) { return c.profileUrn === urn; })) {
          contacts.push({
            name: item.title.text,
            profileUrn: urn,
            headline: (item.subtitle && item.subtitle.text) || ''
          });
        }
      }
    });
  }

  // Also check data.data structure for typeahead results
  if (data && data.data) {
    var walkTypeahead = function(obj) {
      if (!obj || typeof obj !== 'object') return;
      if (Array.isArray(obj)) { obj.forEach(walkTypeahead); return; }
      if (obj.title && obj.title.text && (obj.memberProfileUrn || obj.targetUrn || obj.entityUrn)) {
        var pUrn = obj.memberProfileUrn || obj.targetUrn || obj.entityUrn;
        if (!contacts.find(function(c) { return c.profileUrn === pUrn; })) {
          contacts.push({
            name: obj.title.text,
            profileUrn: pUrn,
            headline: (obj.subtitle && obj.subtitle.text) || ''
          });
        }
      }
      Object.keys(obj).forEach(function(k) { walkTypeahead(obj[k]); });
    };
    walkTypeahead(data.data);
  }

  if (flags['json'] === 'true') {
    return { query: query, total: contacts.length, contacts: contacts };
  }

  // Human-readable output
  var output = [];
  output.push('\x1b[1mSearch results for "' + query + '"\x1b[0m  \u2014  ' + contacts.length + ' contacts\n');
  contacts.forEach(function(c) {
    output.push('  \x1b[1m' + c.name + '\x1b[0m' + (c.headline ? '  \x1b[2m' + c.headline + '\x1b[0m' : ''));
    output.push('  \x1b[2m' + c.profileUrn + '\x1b[0m');
    output.push('');
  });

  console.log(output.join('\n'));
  return null; // already printed
}

// --- DM (find or create conversation + send) ---

async function directMessage(profileUrn, messageText) {
  var tabId = await ensureTab();
  var csrfToken = await getCsrfToken(tabId);
  var mailboxUrn = await getMailboxUrn(tabId, csrfToken);

  // Normalize the profile URN
  if (!profileUrn.startsWith('urn:li:')) {
    profileUrn = 'urn:li:fsd_profile:' + profileUrn;
  }

  // Find or create the conversation
  var encodedMailbox = encodeURIComponent(mailboxUrn);
  var encodedRecipient = encodeURIComponent(profileUrn);
  var url = '/voyager/api/voyagerMessagingGraphQL/graphql?queryId=' + FIND_CONVERSATION_QUERY_ID + '&variables=(mailboxUrn:' + encodedMailbox + ',recipients:List(' + encodedRecipient + '))';

  var data = await messagingFetch(tabId, csrfToken, url);

  // Extract the conversation URN from the response
  var conversationUrn = null;
  if (data && data.data) {
    var walkForConv = function(obj) {
      if (conversationUrn) return;
      if (!obj || typeof obj !== 'object') return;
      if (Array.isArray(obj)) { obj.forEach(walkForConv); return; }
      if (obj.entityUrn && obj.entityUrn.includes('msg_conversation')) {
        conversationUrn = obj.entityUrn;
        return;
      }
      Object.keys(obj).forEach(function(k) { walkForConv(obj[k]); });
    };
    walkForConv(data.data);
  }
  // Also check included
  if (!conversationUrn && data && data.included) {
    for (var di = 0; di < data.included.length; di++) {
      if (data.included[di] && data.included[di].entityUrn && data.included[di].entityUrn.includes('msg_conversation')) {
        conversationUrn = data.included[di].entityUrn;
        break;
      }
    }
  }

  if (!conversationUrn) {
    throw new Error('Could not find or create conversation with ' + profileUrn + '. They may not accept messages.');
  }

  // Now send the message
  await sendMessage(conversationUrn, messageText);
  return { success: true, conversationUrn: conversationUrn, profileUrn: profileUrn, message: messageText.substring(0, 80) };
}

// ─── CLI Dispatch ────────────────────────────────────────────────────────────

if (!cmd || cmd === 'help') {
  console.log('Usage: linkedin <command> [args] [--flags]');
  console.log('');
  console.log('Setup:');
  console.log('  setup <companyId> [--name=N]  Configure which company page to manage');
  console.log('  auth setup --client-id=... --client-secret=...   Configure OAuth credentials');
  console.log('  auth login                   Initiate OAuth flow (enables headless operation)');
  console.log('  auth status                  Show current auth configuration');
  console.log('');
  console.log('Posting & content:');
  console.log('  post <text>                  Publish a text post to the company page');
  console.log('  post <text> --video=<path>   Publish a post with a video attached');
  console.log('  post <text> --image=<path> [--alt="..."]  Publish a post with an image attached');
  console.log('  video <path> "<text>"        Publish a post with a video (alt form)');
  console.log('  image <path> "<text>" [--alt="..."]   Publish a post with an image (alt form)');
  console.log('  list [--limit N]             List recent posts with engagement stats');
  console.log('');
  console.log('Engagement:');
  console.log('  comments <activityId>        View comments on a post');
  console.log('  comment <activityId> <text>  Reply to a post as the company page');
  console.log('  reactions <activityId>       View reactions/likes on a post');
  console.log('  profile <vanityName|urn>     Quick preview of a LinkedIn profile');
  console.log('');
  console.log('Messaging:');
  console.log('  inbox [--unread] [--limit N]              List recent conversations');
  console.log('  messages <conversationUrn> [--limit N]    Show messages in a thread');
  console.log('  send <conversationUrn> <text>             Send a message to a conversation');
  console.log('  search-contacts <query>                   Search for messaging recipients');
  console.log('  dm <profileUrn> <text>                    DM a person (find/create conversation)');
  console.log('');
  console.log('Monitoring:');
  console.log('  watch --scoop=<name>         Watch for new comments (polls, fires webhook)');
  console.log('  unwatch                      Stop watching for comments');
  console.log('  watches                      Show active watch status');
  console.log('  monday [--limit N] [--date Nd|Nw|Nh]  Monday protocol: fetch inbox (filters comments and dated posts)');
  console.log('');
  console.log('Examples:');
  console.log('  linkedin setup 122314561 --name="AI Ecoverse"');
  console.log('  linkedin post "Hello world! #AIEcoverse"');
  console.log('  linkedin post "Demo of the new speck skill" --video=/shared/clips/speck-demo.mp4');
  console.log('  linkedin video /shared/clips/speck-demo.mp4 "Demo of the new speck skill"');
  console.log('  linkedin post "Meet gh-reaper" --image=/shared/media/hero.jpg --alt="gh-reaper hero banner"');
  console.log('  linkedin image /shared/media/hero.jpg "Meet gh-reaper" --alt="gh-reaper hero banner"');
  console.log('  linkedin list --limit 5');
  console.log('  linkedin comments 7463311119181312000');
  console.log('  linkedin comment 7463311119181312000 "Thanks for the feedback!"');
  console.log('  linkedin profile klimetschek');
  console.log('  linkedin watch --scoop=linkedin-responder');
  console.log('  linkedin monday --limit 20 --date 3d');
  console.log('  linkedin inbox --unread');
  console.log('  linkedin messages "urn:li:msg_conversation:..."');
  console.log('  linkedin send "urn:li:msg_conversation:..." "Hello!"');
  console.log('  linkedin search-contacts "karl"');
  console.log('  linkedin dm "urn:li:fsd_profile:ACoAA..." "Hey, quick question..."');
  process.exit(cmd === 'help' ? 0 : 1);
}

var result;

if (cmd === 'post') {
  var text = positional.join(' ');
  if (!text) { console.error('Usage: linkedin post <text> [--video=<path> | --image=<path> [--alt="<altText>"]]'); process.exit(1); }
  if (flags['video'] && flags['image']) {
    console.error('Cannot combine --video and --image (one media item per post). For multi-image carousels, file a follow-up issue.');
    process.exit(1);
  }
  if (flags['video']) {
    result = await createVideoPost(text, flags['video']);
  } else if (flags['image']) {
    result = await createImagePost(text, flags['image'], { altText: flags['alt'] || '' });
  } else {
    result = await createPost(text);
  }
} else if (cmd === 'video') {
  var videoPath = positional[0];
  var videoText = positional.slice(1).join(' ');
  if (!videoPath || !videoText) { console.error('Usage: linkedin video <path> "<text>"'); process.exit(1); }
  result = await createVideoPost(videoText, videoPath);
} else if (cmd === 'image') {
  var imagePath = positional[0];
  var imageText = positional.slice(1).join(' ');
  if (!imagePath || !imageText) { console.error('Usage: linkedin image <path> "<text>" [--alt="<altText>"]'); process.exit(1); }
  result = await createImagePost(imageText, imagePath, { altText: flags['alt'] || '' });
} else if (cmd === 'list') {
  result = await listPosts(parseInt(flags['limit'] || '10'));
} else if (cmd === 'comments') {
  var actId = positional[0];
  if (!actId) { console.error('Usage: linkedin comments <activityId>'); process.exit(1); }
  result = await getComments(actId);
} else if (cmd === 'comment') {
  var actId2 = positional[0];
  var commentText = positional.slice(1).join(' ');
  if (!actId2 || !commentText) { console.error('Usage: linkedin comment <activityId> <text>'); process.exit(1); }
  result = await addComment(actId2, commentText);
} else if (cmd === 'reactions') {
  var actId3 = positional[0];
  if (!actId3) { console.error('Usage: linkedin reactions <activityId>'); process.exit(1); }
  result = await getReactions(actId3);
} else if (cmd === 'profile') {
  var ident = positional[0];
  if (!ident) { console.error('Usage: linkedin profile <vanityName|memberUrn>'); process.exit(1); }
  result = await getProfile(ident);
} else if (cmd === 'inbox') {
  result = await getInbox({ limit: parseInt(flags['limit'] || '20'), unread: flags['unread'] === 'true' });
} else if (cmd === 'messages') {
  var convUrn = positional[0];
  if (!convUrn) { console.error('Usage: linkedin messages <conversationUrn> [--limit N]'); process.exit(1); }
  result = await getMessages(convUrn, { limit: parseInt(flags['limit'] || '20') });
} else if (cmd === 'send') {
  var sendConvUrn = positional[0];
  var sendText = positional.slice(1).join(' ');
  if (!sendConvUrn || !sendText) { console.error('Usage: linkedin send <conversationUrn> "message text"'); process.exit(1); }
  result = await sendMessage(sendConvUrn, sendText);
} else if (cmd === 'search-contacts') {
  var searchQuery = positional.join(' ');
  if (!searchQuery) { console.error('Usage: linkedin search-contacts <query>'); process.exit(1); }
  result = await searchContacts(searchQuery);
} else if (cmd === 'dm') {
  var dmProfileUrn = positional[0];
  var dmText = positional.slice(1).join(' ');
  if (!dmProfileUrn || !dmText) { console.error('Usage: linkedin dm <profileUrn> "message text"'); process.exit(1); }
  result = await directMessage(dmProfileUrn, dmText);
} else if (cmd === 'watch') {
  var scoop = flags['scoop'] || positional[0];
  if (!scoop) { console.error('Usage: linkedin watch --scoop=<name> [--interval="*/5 * * * *"]'); process.exit(1); }
  var interval = flags['interval'] || null;
  result = await setupWatch(scoop, interval);
} else if (cmd === 'unwatch') {
  result = await teardownWatch();
} else if (cmd === 'watches') {
  var watchCfg = await loadWatchConfig();
  if (!watchCfg) { console.log('No active watches.'); process.exit(0); }
  var watchState = await loadWatchState();
  result = { config: watchCfg, state: { lastCheck: watchState.lastCheck, trackedPosts: Object.keys(watchState.commentCounts).length } };
} else if (cmd === '_poll') {
  // Internal: called by cron task to check for new comments
  result = await pollForNewComments();
} else if (cmd === 'monday') {
  result = await monday();
} else if (cmd === 'setup') {
  // Interactive setup: configure company page and auth
  var companyId = positional[0] || flags['company-id'];
  var companyName = flags['name'] || '';
  if (!companyId) {
    console.error('Usage: linkedin setup <companyId> [--name="Company Name"]');
    console.error('');
    console.error('Find your company ID: go to your LinkedIn page admin URL');
    console.error('  https://www.linkedin.com/company/XXXXX/admin/ \u2190 XXXXX is the ID');
    process.exit(1);
  }
  config.companyId = companyId;
  config.companyUrn = 'urn:li:fsd_company:' + companyId;
  if (companyName) config.companyName = companyName;
  config.auth = config.auth || 'session';
  await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2));
  result = { configured: true, companyId: companyId, companyUrn: config.companyUrn, auth: config.auth };
} else if (cmd === 'auth') {
  // OAuth configuration
  var subCmd = positional[0];
  if (subCmd === 'setup') {
    var clientId = flags['client-id'];
    var clientSecret = flags['client-secret'];
    if (!clientId || !clientSecret) {
      console.error('Usage: linkedin auth setup --client-id=<ID> --client-secret=<SECRET>');
      console.error('');
      console.error('Register an app at https://www.linkedin.com/developers/apps');
      console.error('Request "Community Management API" product for company page posting.');
      process.exit(1);
    }
    config.oauth = config.oauth || {};
    config.oauth.clientId = clientId;
    config.oauth.clientSecret = clientSecret;
    await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2));
    result = { oauth: 'configured', clientId: clientId, nextStep: 'Run: linkedin auth login' };
  } else if (subCmd === 'login') {
    // Initiate OAuth flow using oauth-token --intercept
    var oauthConfig = config.oauth || {};
    if (!oauthConfig.clientId) {
      console.error('No OAuth client configured. Run: linkedin auth setup --client-id=... --client-secret=...');
      process.exit(1);
    }
    var scopes = 'w_member_social openid profile';
    if (oauthConfig.scopes && oauthConfig.scopes.includes('w_organization_social')) {
      scopes += ' w_organization_social r_organization_social';
    }
    var authUrl = 'https://www.linkedin.com/oauth/v2/authorization?response_type=code&client_id=' + oauthConfig.clientId + '&redirect_uri=http://localhost/callback&scope=' + encodeURIComponent(scopes) + '&state=slicc_linkedin';
    
    console.log('Initiating OAuth flow...');
    console.log('Authorize URL: ' + authUrl);
    
    var interceptResult = await exec('oauth-token --intercept --authorize-url ' + JSON.stringify(authUrl) + ' --redirect-pattern "http://localhost/*"');
    if (interceptResult.exitCode !== 0) {
      console.error('OAuth intercept failed:', interceptResult.stderr);
      process.exit(1);
    }
    
    // Extract the code from the redirect URL
    var redirectUrl = interceptResult.stdout.trim();
    var codeMatch = redirectUrl.match(/[?&]code=([^&]+)/);
    if (!codeMatch) {
      console.error('No authorization code in redirect:', redirectUrl);
      process.exit(1);
    }
    
    // Exchange code for token
    var tokenResp = await fetch('https://www.linkedin.com/oauth/v2/accessToken', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: 'grant_type=authorization_code&code=' + codeMatch[1] + '&redirect_uri=http://localhost/callback&client_id=' + oauthConfig.clientId + '&client_secret=' + oauthConfig.clientSecret
    });
    
    if (!tokenResp.ok) {
      var errText = await tokenResp.text();
      console.error('Token exchange failed:', errText);
      process.exit(1);
    }
    
    var tokenData = await tokenResp.json();
    config.oauth.accessToken = tokenData.access_token;
    config.oauth.refreshToken = tokenData.refresh_token || null;
    config.oauth.tokenExpiry = Date.now() + (tokenData.expires_in * 1000);
    config.auth = 'oauth';
    await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2));
    
    result = { authenticated: true, expiresIn: tokenData.expires_in + 's', mode: 'oauth' };
  } else if (subCmd === 'status') {
    result = {
      mode: config.auth || 'session',
      oauth: config.oauth ? {
        clientId: config.oauth.clientId || null,
        hasToken: !!config.oauth.accessToken,
        tokenExpiry: config.oauth.tokenExpiry ? new Date(config.oauth.tokenExpiry).toISOString() : null,
        scopes: config.oauth.scopes || []
      } : null
    };
  } else {
    console.error('Usage: linkedin auth <setup|login|status>');
    process.exit(1);
  }
} else {
  console.error('Unknown command: ' + cmd);
  console.error('Run "linkedin help" for usage.');
  process.exit(1);
}

if (result !== null && result !== undefined) {
  console.log(JSON.stringify(result, null, 2));
}
