mutation CreateSameRoomRateMutation($reportId: String!, $expenseId: String!, $userId: String!, $contextRole: ContextRoleType!, $roomRateObject: RoomRateAndTax!, $taxFields: [TaxField!] = null, $roomRateExpenseTypeId: String!, $isTrexEnabled: Boolean!, $expenseListDetailFormId: String) {
  createSameRoomRateItemizations(
    reportId: $reportId
    expenseId: $expenseId
    userId: $userId
    contextRole: $contextRole
    roomRateObject: $roomRateObject
    taxFields: $taxFields
    roomRateExpenseTypeId: $roomRateExpenseTypeId
    expenseListDetailFormId: $expenseListDetailFormId
  ) {
    status {
      success
      __typename
    }
    reportDetails @include(if: $isTrexEnabled) {
      ...ExpenseReportDetailsFragment
      __typename
    }
    entry @include(if: $isTrexEnabled) {
      ...EreExpenseEntrySummaryFragment
      __typename
    }
    entryExceptions @include(if: $isTrexEnabled) {
      ...EreEntryExceptionsFragment
      __typename
    }
    expenseTypeFilters @include(if: $isTrexEnabled) {
      shouldFilterCashAdvanceExpenseTypes
      shouldFilterCompanyCarExpenseType
      shouldFilterPersonalCarExpenseType
      __typename
    }
    reportEntryDetails @include(if: $isTrexEnabled) {
      ...EntryDetailsForList
      __typename
    }
    reportExceptions @include(if: $isTrexEnabled) {
      ...ReportExceptionsFragment
      __typename
    }
    itemizationDetails @include(if: $isTrexEnabled) {
      ...ItemizationDetailsFragment
      __typename
    }
    __typename
  }
}

fragment EreEntryExceptionsFragment on EntryExceptions {
  reportId
  expenseId
  attendeesExceptionLevel
  transactionAmount {
    value
    currencyCode
    __typename
  }
  transactionDate
  expenseType {
    id
    code
    name
    meta {
      isJapanPublicTransportation
      __typename
    }
    __typename
  }
  countOfExceptions
  hasBlockingExceptions
  entryExceptions {
    allocationId
    exceptionCode
    expenseId
    isBlocking
    message
    parameters {
      entryExceptionAttendees {
        lastName
        firstName
        entryAmount
        crnCode
        totalExpensed
        totalAuthorized
        __typename
      }
      missingFields {
        missingSpecialParentField
        fields
        fieldIds
        __typename
      }
      __typename
    }
    parentExpenseId
    __typename
  }
  itemizationsExceptions {
    reportId
    expenseId
    attendeesExceptionLevel
    itemizationId
    transactionAmount {
      value
      currencyCode
      __typename
    }
    transactionDate
    expenseType {
      id
      code
      name
      meta {
        isJapanPublicTransportation
        __typename
      }
      __typename
    }
    countOfExceptions
    hasBlockingExceptions
    exceptions {
      allocationId
      exceptionCode
      expenseId
      isBlocking
      message
      parameters {
        entryExceptionAttendees {
          lastName
          firstName
          entryAmount
          crnCode
          totalExpensed
          totalAuthorized
          __typename
        }
        missingFields {
          missingSpecialParentField
          fields
          fieldIds
          __typename
        }
        __typename
      }
      parentExpenseId
      __typename
    }
    __typename
  }
  __typename
}

fragment ExpenseEntrySummaryFragment on ExpenseEntrySummary {
  allocationState
  approvedAmount {
    value
    currencyCode
    __typename
  }
  attendeeCount
  claimedAmount {
    value
    currencyCode
    __typename
  }
  eReceiptImageId
  expenseSourceIdentifiers {
    eReceiptId
    expenseCaptureImageId
    jptRouteId
    personalCardTransactionId
    quickExpenseId
    segmentId
    segmentTypeId
    tripId
    creditCardTransaction {
      id
      type
      __typename
    }
    __typename
  }
  expenseType {
    id
    code
    name
    meta {
      isJapanPublicTransportation
      __typename
    }
    __typename
  }
  id
  isImageRequired
  isPaperReceiptRequired
  isPersonalExpense
  jptRouteId
  location {
    city
    countryCode
    countrySubDivisionCode
    id
    name
    __typename
  }
  meta {
    canDelete
    hasAffidavit
    hasAllocation
    hasAttendees
    hasBlockingExceptions
    hasComments
    hasExceptions
    hasItemizations
    hasReceiptImage
    hasSource
    hasXmlReceipt
    hasSourceCreditCard
    hasSourceEReceipt
    hasSourceItinerary
    hasSourceExpenseIt
    hasSourceMobile
    hasSourcePersonalCard
    __typename
  }
  parentExpenseId
  paymentType {
    id
    code
    name
    __typename
  }
  receiptImageId
  rpeKey
  transactionAmount {
    value
    currencyCode
    __typename
  }
  postedAmount {
    value
    currencyCode
    __typename
  }
  transactionDate
  vendor {
    id
    description
    name
    __typename
  }
  __typename
}

fragment AmountValueFragment on AmountValue {
  amountValue: value {
    value
    currencyCode
    __typename
  }
  __typename
}

fragment BooleanValueFragment on BooleanValue {
  booleanValue: value
  isValid
  __typename
}

fragment DateValueFragment on DateValue {
  dateValue: value
  isValid
  __typename
}

fragment ExchangeRateValueFragment on ExchangeRateValue {
  value
  operation
  __typename
}

fragment ExpenseAmountFragment on ExpenseAmount {
  expenseAmountValue: value
  __typename
}

fragment FloatValueFragment on FloatValue {
  floatValue: value
  __typename
}

fragment IntegerValueFragment on IntegerValue {
  integerValue: value
  __typename
}

fragment ListItemValueFragment on ListItemValue {
  code
  id
  listItemValue: value
  __typename
}

fragment ListValueFragment on ListValue {
  isValid
  listValue: value {
    code
    id
    value
    __typename
  }
  __typename
}

fragment LocationValueFragment on LocationListValue {
  isValid
  locationValue: value {
    id
    name
    city
    value
    countryCode
    countrySubDivisionCode
    __typename
  }
  __typename
}

fragment StringValueFragment on StringValue {
  stringValue: value
  __typename
}

fragment EntryDetailsForList on ReportEntryDetails {
  expenseId
  summary {
    ...ExpenseEntrySummaryFragment
    __typename
  }
  values {
    fieldName
    formFieldId
    value {
      ...AmountValueFragment
      ...BooleanValueFragment
      ...DateValueFragment
      ...ExchangeRateValueFragment
      ...ExpenseAmountFragment
      ...FloatValueFragment
      ...IntegerValueFragment
      ...ListItemValueFragment
      ...ListValueFragment
      ...LocationValueFragment
      ...StringValueFragment
      __typename
    }
    __typename
  }
  __typename
}

fragment EntryExceptionFragment on ExpenseEntryException {
  allocationId
  exceptionCode
  expenseId
  isBlocking
  message
  parentExpenseId
  parameters {
    entryExceptionAttendees {
      lastName
      firstName
      entryAmount
      crnCode
      totalExpensed
      totalAuthorized
      __typename
    }
    missingFields {
      missingSpecialParentField
      fields
      fieldIds
      __typename
    }
    __typename
  }
  __typename
}

fragment EntryExceptionsFragment on EntryExceptions {
  reportId
  expenseId
  attendeesExceptionLevel
  countOfExceptions
  transactionAmount {
    value
    currencyCode
    __typename
  }
  transactionDate
  expenseType {
    id
    code
    name
    meta {
      isJapanPublicTransportation
      __typename
    }
    __typename
  }
  entryExceptions {
    ...EntryExceptionFragment
    __typename
  }
  itemizations {
    reportId
    expenseId
    attendeesExceptionLevel
    countOfExceptions
    transactionAmount {
      value
      currencyCode
      __typename
    }
    transactionDate
    expenseType {
      id
      code
      name
      meta {
        isJapanPublicTransportation
        __typename
      }
      __typename
    }
    entryExceptions {
      ...EntryExceptionFragment
      __typename
    }
    itemizations {
      expenseId
      __typename
    }
    __typename
  }
  __typename
}

fragment ReportExceptionsFragment on ReportExceptions {
  reportId
  countOfExceptions
  hasBlockingExceptions
  reportExceptions {
    allocationId
    exceptionCode
    expenseId
    parentExpenseId
    isBlocking
    message
    parameters {
      entryExceptionAttendees {
        lastName
        firstName
        entryAmount
        crnCode
        totalExpensed
        totalAuthorized
        __typename
      }
      missingFields {
        missingSpecialParentField
        fields
        fieldIds
        __typename
      }
      __typename
    }
    __typename
  }
  entryExceptions {
    ...EntryExceptionsFragment
    __typename
  }
  __typename
}

fragment EreExpenseEntrySummaryFragment on ExpenseEntrySummary {
  ...ExpenseEntrySummaryFragment
  cctReceiptImageId
  travel {
    hotelCheckinDate
    hotelCheckoutDate
    __typename
  }
  itemizations {
    id
    attendeeCount
    allocationState
    isPersonalExpense
    approvedAmount {
      value
      currencyCode
      __typename
    }
    meta {
      canDelete
      hasAllocation
      hasAttendees
      hasComments
      hasExceptions
      hasBlockingExceptions
      __typename
    }
    expenseType {
      id
      code
      name
      __typename
    }
    rpeKey
    transactionAmount {
      value
      currencyCode
      __typename
    }
    transactionDate
    __typename
  }
  __typename
}

fragment ExpenseTypeFragment on ExpenseType {
  id
  name
  itemizationType
  text
  header
  parentName
  code
  visibilityCode
  itemizeStyle
  shouldAddUserAsDefaultAttendee
  allowEditAttendeeAmount
  allowEditAttendeeCount
  shouldDisplayAttendeeAmounts
  itemizationWizardId
  meta {
    isTravelAllowanceExpense
    canCombineExpense
    isItemizationAllowed
    isItemizationRequired
    hasItemizationWizard
    isJapanPublicTransportation
    __typename
  }
  __typename
}

fragment ExpenseReportDetailsFragment on ExpenseReportDetails {
  id
  allocationFormId
  reportType
  userId
  policy {
    id
    allowReceiptAffidavits
    receiptAffidavitExplanation
    receiptAffidavitAcceptance
    expenseListDetailFormId
    meta {
      canShowReceipts
      canUploadImagesToExpenses
      __typename
    }
    __typename
  }
  expenseTypes {
    ...ExpenseTypeFragment
    __typename
  }
  meta {
    isApproved
    canReopen
    isReopened
    isSubmitted
    canAddExpense
    canAllocateExpenses
    isReceiptImageAvailable
    __typename
  }
  name
  claimedAmount {
    value
    currencyCode
    __typename
  }
  approvedAmount {
    value
    currencyCode
    __typename
  }
  reportTotal {
    value
    currencyCode
    __typename
  }
  currencyCode
  countryCode
  taxConfigId
  __typename
}

fragment ItemizationDetailsFragment on ExpenseEntryItemizationSummary {
  id
  expenseType {
    id
    name
    code
    __typename
  }
  transactionDate
  transactionAmount {
    value
    currencyCode
    __typename
  }
  approvedAmount {
    value
    currencyCode
    __typename
  }
  meta {
    hasExceptions
    hasBlockingExceptions
    hasAllocation
    hasAttendees
    hasComments
    __typename
  }
  __typename
}
