// build.mjs — bundle @ai-ecoverse/kev.js (kev-entry.mjs) -> kev-bundle.cjs.
//
// Run locally or in CI:  npm install && npm run build
//
// The skill ships the committed kev-bundle.cjs, so installing it builds
// nothing; this script regenerates the bundle when the kev.js pin in
// package.json changes. onnxruntime-web stays outside the bundle: `intent
// pull` installs the pinned copy and kev-runtime.js imports it at run time.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as esbuild from 'esbuild';

const here = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(join(here, 'package.json'), 'utf8'));
const name = '@ai-ecoverse/kev.js';

await esbuild.build({
  entryPoints: [join(here, 'kev-entry.mjs')],
  outfile: join(here, 'kev-bundle.cjs'),
  bundle: true,
  platform: 'browser',
  format: 'cjs',
  legalComments: 'none',
  banner: {
    js: `// GENERATED by build.mjs from ${name}@${pkg.dependencies[name]}: do not edit; run npm run build.`,
  },
  logLevel: 'info',
});
