// ServiceNow (Adobe ESC) API client — generated by secret-sauce
// Uses eval-file pattern for page-context API calls via Angular $http
// Dynamic user resolution — run `servicenow login` to authenticate.

const CONFIG_FILE = '/shared/servicenow/.config.json';
const TICKET_WIDGET = 'a54beb3a87f10010e0ef0cf888cb0bba';

// Defaults (can be overridden in config)
const DEFAULTS = {
  domain: 'adobe.service-now.com',
  portal_id: '70cd9f3b734b13001fdae9c54cf6a72f',
  coveo_org: 'adobev2prod9e382h1q',
  coveo_search_hub: 'ServiceNowESC_MainSearch'
};

let _config = null;
let _tabId = null;

async function loadConfig() {
  if (_config) return _config;
  try {
    const raw = await fs.readFile(CONFIG_FILE, 'utf8');
    _config = JSON.parse(raw);
    return _config;
  } catch (e) {
    return null;
  }
}

async function saveConfig(config) {
  _config = config;
  await fs.writeFile(CONFIG_FILE, JSON.stringify(config, null, 2));
}

function getDomain() {
  return (_config && _config.domain) || DEFAULTS.domain;
}

function getPortalId() {
  return (_config && _config.portal_id) || DEFAULTS.portal_id;
}

function getCoveoOrg() {
  return (_config && _config.coveo_org) || DEFAULTS.coveo_org;
}

function getCoveoSearchHub() {
  return (_config && _config.coveo_search_hub) || DEFAULTS.coveo_search_hub;
}

function getUserSysId() {
  if (_config && _config.user_sys_id) return _config.user_sys_id;
  return null;
}

async function ensureTab() {
  const domain = getDomain();
  const list = await exec('playwright-cli tab-list');
  if (list.exitCode !== 0) {
    console.error('Failed to list browser tabs: ' + list.stderr);
    process.exit(1);
  }

  if (_tabId && list.stdout.includes(_tabId)) return _tabId;
  _tabId = null;

  const re = new RegExp('\\[([^\\]]+)\\]\\s+https?://[^\\s]*' + domain.replace(/\./g, '\\.'));
  const match = list.stdout.match(re);
  if (match) {
    _tabId = match[1];
    // Check if the tab is on the ESC portal (has Angular). If not, navigate there.
    const angularCheck = await exec('playwright-cli eval "typeof angular" --tab=' + _tabId);
    if (angularCheck.stdout.trim() !== 'object') {
      await exec('playwright-cli navigate "https://' + domain + '/esc" --tab=' + _tabId);
      await new Promise(resolve => setTimeout(resolve, 4000));
    }
    return _tabId;
  }

  const r = await exec('playwright-cli open https://' + domain + '/esc');
  if (r.exitCode !== 0) {
    console.error('Failed to open ServiceNow tab: ' + r.stderr);
    process.exit(1);
  }
  const m = r.stdout.match(/\[([^\]]+)\]/);
  _tabId = m ? m[1] : null;
  if (!_tabId) {
    console.error('Could not determine tab ID from: ' + r.stdout);
    process.exit(1);
  }
  await new Promise(resolve => setTimeout(resolve, 4000));
  return _tabId;
}

// Ensure user is authenticated — if no config, prompt to run login
async function ensureAuth() {
  const config = await loadConfig();
  if (!config || !config.user_sys_id) {
    console.error('Not logged in. Run `servicenow login` first to authenticate.');
    process.exit(1);
  }
  return config;
}

// Evaluate JS in the ServiceNow page context via temp file
async function evalInPage(jsCode) {
  const tabId = await ensureTab();
  const tmpFile = '/shared/.sn_eval_' + Date.now() + '_' + Math.random().toString(36).slice(2) + '.js';
  await fs.writeFile(tmpFile, jsCode);
  const result = await exec('playwright-cli eval-file ' + tmpFile + ' --tab=' + tabId);
  await fs.rm(tmpFile).catch(() => {});

  if (result.exitCode !== 0) {
    if (result.stderr.includes('angular') || result.stderr.includes('injector')) {
      console.error('Session expired or page not loaded. Log into adobe.service-now.com and try again.');
      process.exit(1);
    }
    throw new Error('Eval failed: ' + result.stderr);
  }

  const stdout = result.stdout.trim();
  if (!stdout) return null;
  try {
    let data = JSON.parse(stdout);
    if (typeof data === 'string') data = JSON.parse(data);
    return data;
  } catch (e) {
    return stdout;
  }
}

// Detect if the user is logged in by checking if Angular is loaded and $http works
async function checkLoggedIn() {
  const tabId = await ensureTab();
  const tmpFile = '/shared/.sn_login_check_' + Date.now() + '.js';
  const code = [
    'new Promise(function(r) {',
    '  try {',
    '    var inj = angular.element(document.body).injector();',
    '    if (!inj) { r(JSON.stringify({logged_in: false, reason: "no_angular"})); return; }',
    '    var h = inj.get("$http");',
    '    h.get("/api/now/table/sys_user?sysparm_query=user_name=javascript:gs.getUserName()&sysparm_fields=sys_id,user_name,name,email&sysparm_limit=1").then(function(resp) {',
    '      var users = resp.data.result || [];',
    '      if (users.length > 0) {',
    '        r(JSON.stringify({logged_in: true, user: users[0]}));',
    '      } else {',
    '        r(JSON.stringify({logged_in: false, reason: "no_user"}));',
    '      }',
    '    }).catch(function(e) {',
    '      r(JSON.stringify({logged_in: false, reason: "api_error", status: e.status}));',
    '    });',
    '  } catch(e) {',
    '    r(JSON.stringify({logged_in: false, reason: "exception", msg: e.message}));',
    '  }',
    '})'
  ].join('\n');
  await fs.writeFile(tmpFile, code);
  const result = await exec('playwright-cli eval-file ' + tmpFile + ' --tab=' + tabId);
  await fs.rm(tmpFile).catch(function() {});
  if (result.exitCode !== 0) return { logged_in: false, reason: 'eval_failed' };
  try {
    return JSON.parse(result.stdout.trim());
  } catch (e) {
    return { logged_in: false, reason: 'parse_failed' };
  }
}

// Extract Coveo config from the portal page (org, token, search hub)
async function detectCoveoConfig() {
  const portalId = getPortalId();
  const data = await spGet('/api/now/sp/page?id=adb_esc_my_requests&portal_id=' + portalId);
  const containers = data.result && data.result.containers || [];
  for (const c of containers) {
    for (const row of (c.rows || [])) {
      for (const col of (row.columns || [])) {
        for (const w of (col.widgets || [])) {
          const coveo = w.widget && w.widget.data && w.widget.data.coveo;
          if (coveo && coveo.accessToken) {
            return {
              coveo_org: coveo.organizationId || null,
              coveo_search_hub: coveo.searchHub || null
            };
          }
        }
      }
    }
  }
  return null;
}

// SP GET via Angular $http
async function spGet(path) {
  const code = [
    'new Promise(function(resolve) {',
    '  var h = angular.element(document.body).injector().get("$http");',
    '  h.get("' + path.replace(/"/g, '\\"') + '").then(function(resp) {',
    '    resolve(JSON.stringify(resp.data));',
    '  }).catch(function(e) {',
    '    resolve(JSON.stringify({__error: e.status || 500, detail: e.data || "unknown"}));',
    '  });',
    '})'
  ].join('\n');

  const data = await evalInPage(code);
  if (data && data.__error) {
    if (data.__error === 401 || data.__error === 403) {
      console.error('Session expired. Log into adobe.service-now.com and try again.');
      process.exit(1);
    }
    throw new Error('SP API error ' + data.__error + ': ' + JSON.stringify(data.detail));
  }
  return data;
}

// SP POST via Angular $http
async function spPost(path, body) {
  const bodyJson = JSON.stringify(body).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  const code = [
    'new Promise(function(resolve) {',
    '  var h = angular.element(document.body).injector().get("$http");',
    '  var payload = JSON.parse("' + bodyJson + '");',
    '  h.post("' + path.replace(/"/g, '\\"') + '", payload).then(function(resp) {',
    '    resolve(JSON.stringify(resp.data));',
    '  }).catch(function(e) {',
    '    resolve(JSON.stringify({__error: e.status || 500, detail: e.data || "unknown"}));',
    '  });',
    '})'
  ].join('\n');

  const data = await evalInPage(code);
  if (data && data.__error) {
    if (data.__error === 401 || data.__error === 403) {
      console.error('Session expired. Log into adobe.service-now.com and try again.');
      process.exit(1);
    }
    throw new Error('SP API error ' + data.__error + ': ' + JSON.stringify(data.detail));
  }
  return data;
}

// Get Coveo search token from portal page
async function getCoveoToken() {
  const portalId = getPortalId();
  const data = await spGet('/api/now/sp/page?id=adb_esc_my_requests&portal_id=' + portalId);
  const containers = data.result && data.result.containers || [];
  for (const c of containers) {
    for (const row of (c.rows || [])) {
      for (const col of (row.columns || [])) {
        for (const w of (col.widgets || [])) {
          const coveo = w.widget && w.widget.data && w.widget.data.coveo;
          if (coveo && coveo.accessToken) return coveo.accessToken;
        }
      }
    }
  }
  throw new Error('Could not extract Coveo token from portal page');
}

// Table API via Angular $http (works for lookups and listing)
async function tableGet(table, query, fields, limit) {
  limit = limit || 10;
  var url = '/api/now/table/' + table + '?sysparm_query=' + encodeURIComponent(query);
  if (fields) url += '&sysparm_fields=' + encodeURIComponent(fields);
  url += '&sysparm_limit=' + limit;
  const data = await spGet(url);
  return data.result || [];
}

// Coveo KB search
async function coveoSearch(query, numResults) {
  numResults = numResults || 10;
  const token = await getCoveoToken();
  const coveoOrg = getCoveoOrg();
  const searchHub = getCoveoSearchHub();
  const url = 'https://' + coveoOrg + '.org.coveo.com/rest/search/v2?organizationId=' + coveoOrg;
  const resp = await fetch(url, {
    method: 'POST',
    headers: {
      'Authorization': 'Bearer ' + token,
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    },
    body: JSON.stringify({
      q: query,
      numberOfResults: numResults,
      searchHub: searchHub,
      fieldsToInclude: ['sn_kb_article', 'sntitle', 'snshort_description', 'sysid', 'snnumber']
    })
  });
  if (!resp.ok) {
    const text = await resp.text();
    throw new Error('Coveo search failed (' + resp.status + '): ' + text);
  }
  return resp.json();
}

// Resolve INC/RITM/REQ number to sys_id via Table API
async function resolveNumber(numberOrId) {
  if (/^[a-f0-9]{32}$/i.test(numberOrId)) {
    // sys_id without a ticket number — try each table in order
    for (const table of ['incident', 'sc_req_item', 'sc_request']) {
      const results = await tableGet(table, 'sys_id=' + numberOrId, 'sys_id', 1);
      if (results.length > 0) return { sys_id: numberOrId, table };
    }
    console.error('Could not find a record for sys_id ' + numberOrId + '. Use a ticket number (INC/RITM/REQ) for reliable lookup.');
    process.exit(1);
  }
  var table = 'incident';
  if (numberOrId.startsWith('RITM')) table = 'sc_req_item';
  else if (numberOrId.startsWith('REQ')) table = 'sc_request';

  const results = await tableGet(table, 'number=' + numberOrId, 'sys_id', 1);
  if (results.length > 0) {
    return { sys_id: results[0].sys_id, table: table };
  }
  console.error('Could not resolve ' + numberOrId + '. Ticket not found.');
  process.exit(1);
}

// Extract widgets from page response
function extractWidgets(pageData) {
  const widgets = [];
  const containers = pageData.result && pageData.result.containers || [];
  for (const c of containers) {
    for (const row of (c.rows || [])) {
      for (const col of (row.columns || [])) {
        for (const w of (col.widgets || [])) {
          if (w.widget) widgets.push(w.widget);
        }
      }
    }
  }
  return widgets;
}

function findWidget(widgets, name) {
  return widgets.find(function(w) { return w.name === name; });
}

function stripHtml(html) {
  if (!html) return '';
  return html.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&nbsp;/g, ' ').replace(/\r\n/g, '\n').trim();
}

// --- Commands ---

async function cmdLogin(args) {
  // Parse optional --domain flag
  var domain = DEFAULTS.domain;
  for (var i = 0; i < args.length; i++) {
    if (args[i].startsWith('--domain=')) {
      domain = args[i].split('=')[1];
    }
  }
  if (!/^[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(\.[a-zA-Z0-9]([a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(domain)) {
    console.error('Invalid domain: "' + domain + '". Provide a plain hostname like "mycompany.service-now.com".');
    process.exit(1);
  }

  // Save domain early so ensureTab uses it
  var config = (await loadConfig()) || {};
  config.domain = domain;
  await saveConfig(config);

  console.log('Opening ServiceNow at ' + domain + '...');
  console.log('Please complete SSO login in the browser if prompted.');

  // Open the tab
  await ensureTab();

  // Poll for login completion (check every 3 seconds, up to 2 minutes)
  var maxAttempts = 40;
  var attempt = 0;
  var loginResult = null;

  while (attempt < maxAttempts) {
    attempt++;
    await new Promise(function(resolve) { setTimeout(resolve, 3000); });
    loginResult = await checkLoggedIn();
    if (loginResult.logged_in) break;
    if (attempt % 5 === 0) {
      console.log('Waiting for login... (' + (attempt * 3) + 's)');
    }
  }

  if (!loginResult || !loginResult.logged_in) {
    console.error('Login timed out after 2 minutes. Please try again.');
    process.exit(1);
  }

  var user = loginResult.user;
  console.log('Logged in as: ' + user.name + ' (' + user.email + ')');

  // Detect Coveo config from the portal
  var coveoConfig = null;
  try {
    coveoConfig = await detectCoveoConfig();
  } catch (e) {
    // Non-fatal — Coveo might not be available
  }

  // Save full config
  config.domain = domain;
  config.user_sys_id = user.sys_id;
  config.user_name = user.user_name;
  config.user_display_name = user.name;
  config.user_email = user.email;
  if (coveoConfig) {
    if (coveoConfig.coveo_org) config.coveo_org = coveoConfig.coveo_org;
    if (coveoConfig.coveo_search_hub) config.coveo_search_hub = coveoConfig.coveo_search_hub;
  }
  config.logged_in_at = new Date().toISOString();
  await saveConfig(config);

  console.log('Configuration saved to ' + CONFIG_FILE);
  console.log('');
  console.log('You can now use:');
  console.log('  servicenow tickets       — list your open tickets');
  console.log('  servicenow kb "query"    — search the knowledge base');
}

async function cmdWhoami() {
  var config = await loadConfig();
  if (!config || !config.user_sys_id) {
    console.log('Not logged in. Run `servicenow login` to authenticate.');
    return;
  }
  console.log(JSON.stringify({
    name: config.user_display_name,
    email: config.user_email,
    username: config.user_name,
    sys_id: config.user_sys_id,
    domain: config.domain,
    logged_in_at: config.logged_in_at
  }, null, 2));
}

async function cmdTickets(args) {
  await ensureAuth();
  var userSysId = getUserSysId();

  // Parse flags
  var stateFilter = '1,2,3'; // Default: New, In Progress, On Hold
  var stateExplicit = false;
  var tableFilter = null; // null means show both incidents + requests
  for (var i = 0; i < args.length; i++) {
    if (args[i].startsWith('--state=')) {
      var stateMap = { 'new': '1', 'in-progress': '2', 'on-hold': '3', 'resolved': '6', 'closed': '7', 'all': '1,2,3,6,7' };
      var val = args[i].split('=')[1];
      stateFilter = stateMap[val] || val;
      stateExplicit = true;
    }
    if (args[i] === '--incidents') tableFilter = 'incident';
    if (args[i] === '--requests') tableFilter = 'sc_req_item';
    if (args[i].startsWith('--table=')) tableFilter = args[i].split('=')[1];
  }

  var stateLabels = { '1': 'New', '2': 'In Progress', '3': 'On Hold', '6': 'Resolved', '7': 'Closed' };
  var allTickets = [];

  // Incidents
  if (!tableFilter || tableFilter === 'incident') {
    var incQuery = 'caller_id=' + userSysId + '^stateIN' + stateFilter + '^ORDERBYDESCsys_created_on';
    var incFields = 'number,short_description,state,priority,sys_id,sys_created_on';
    var incidents = await tableGet('incident', incQuery, incFields, 20);
    incidents.forEach(function(r) {
      allTickets.push({
        number: r.number,
        type: 'Incident',
        description: r.short_description,
        state: stateLabels[r.state] || r.state,
        priority: r.priority,
        created: r.sys_created_on,
        sys_id: r.sys_id
      });
    });
  }

  // Request Items
  if (!tableFilter || tableFilter === 'sc_req_item') {
    var ritmStateClause = stateExplicit ? '^stateIN' + stateFilter : '^stateNOT IN3,4,7';
    var ritmQuery = 'request.requested_for=' + userSysId + ritmStateClause + '^ORDERBYDESCsys_created_on';
    var ritmFields = 'number,short_description,state,sys_id,sys_created_on';
    var ritms = await tableGet('sc_req_item', ritmQuery, ritmFields, 20);
    ritms.forEach(function(r) {
      allTickets.push({
        number: r.number,
        type: 'Request',
        description: r.short_description,
        state: r.state === '1' ? 'Open' : r.state === '2' ? 'Work in Progress' : r.state,
        priority: '',
        created: r.sys_created_on,
        sys_id: r.sys_id
      });
    });
  }

  if (allTickets.length === 0) {
    console.log('No tickets found matching the criteria.');
    return;
  }

  console.log(JSON.stringify(allTickets, null, 2));
}

async function cmdGet(numberOrId) {
  if (!numberOrId) {
    console.error('Usage: servicenow get <INC_NUMBER or sys_id>');
    process.exit(1);
  }
  await ensureAuth();
  const resolved = await resolveNumber(numberOrId);

  // Get ticket page
  const portalId = getPortalId();
  const pageData = await spGet('/api/now/sp/page?id=ticket&table=' + resolved.table + '&sys_id=' + resolved.sys_id + '&portal_id=' + portalId);
  const widgets = extractWidgets(pageData);
  const header = findWidget(widgets, 'ADB Standard Ticket Header');
  const headerData = header && header.data;

  // Get conversation
  const convData = await spPost('/api/now/sp/widget/' + TICKET_WIDGET + '?id=ticket&sys_id=' + resolved.sys_id + '&table=' + resolved.table, {
    sys_id: resolved.sys_id,
    isPosting: false
  });
  const stream = convData.result && convData.result.data && convData.result.data.stream;

  const stateField = headerData && headerData.headerFields && headerData.headerFields.find(function(f) { return f.name === 'state'; });
  const createdField = headerData && headerData.headerFields && headerData.headerFields.find(function(f) { return f.name === 'sys_created_on'; });
  const updatedField = headerData && headerData.headerFields && headerData.headerFields.find(function(f) { return f.name === 'sys_updated_on'; });

  const result = {
    number: headerData && headerData.number && headerData.number.display_value,
    title: headerData && headerData.title,
    state: stateField && stateField.display_value,
    created: createdField && createdField.display_value,
    updated: updatedField && updatedField.display_value,
    fields: headerData && headerData.fields && headerData.fields.map(function(f) {
      var obj = {};
      obj[f.label] = f.display_value;
      return obj;
    }),
    comments: stream && stream.entries && stream.entries.map(function(e) {
      return {
        author: e.name,
        date: e.sys_created_on_adjusted,
        type: e.field_label || e.element,
        text: e.element === 'attachment' ? '[Attachment: ' + (e.attachment && e.attachment.file_name || 'unknown') + ']' : stripHtml(e.value).substring(0, 500)
      };
    }) || []
  };
  console.log(JSON.stringify(result, null, 2));
}

async function cmdComment(numberOrId, message) {
  if (!numberOrId || !message) {
    console.error('Usage: servicenow comment <INC_NUMBER> <MESSAGE>');
    process.exit(1);
  }
  await ensureAuth();
  const resolved = await resolveNumber(numberOrId);
  await spPost('/api/now/sp/widget/' + TICKET_WIDGET + '?id=ticket&sys_id=' + resolved.sys_id + '&table=' + resolved.table, {
    sys_id: resolved.sys_id,
    isPosting: true,
    journalEntry: message,
    journalEntryField: 'comments',
    table: resolved.table
  });
  console.log('Comment posted on ' + numberOrId + '.');
}

async function cmdWorknote(numberOrId, message) {
  if (!numberOrId || !message) {
    console.error('Usage: servicenow worknote <INC_NUMBER> <MESSAGE>');
    process.exit(1);
  }
  await ensureAuth();
  const resolved = await resolveNumber(numberOrId);
  await spPost('/api/now/sp/widget/' + TICKET_WIDGET + '?id=ticket&sys_id=' + resolved.sys_id + '&table=' + resolved.table, {
    sys_id: resolved.sys_id,
    isPosting: true,
    journalEntry: message,
    journalEntryField: 'work_notes',
    table: resolved.table
  });
  console.log('Work note posted on ' + numberOrId + '.');
}

async function cmdKb(query) {
  if (!query) {
    console.error('Usage: servicenow kb <SEARCH_QUERY>');
    process.exit(1);
  }
  await ensureAuth();
  const search = await coveoSearch(query, 10);
  if (!search.results || search.results.length === 0) {
    console.log('No KB articles found.');
    return;
  }
  const articles = search.results.map(function(r) {
    return {
      title: r.title,
      number: (r.raw && (r.raw.sn_kb_article || r.raw.snnumber)) || '',
      excerpt: (r.excerpt || '').replace(/<[^>]+>/g, '').trim().substring(0, 200)
    };
  });
  console.log(JSON.stringify(articles, null, 2));
}

async function cmdKbArticle(kbNumber) {
  if (!kbNumber) {
    console.error('Usage: servicenow kb-article <KB_NUMBER>');
    process.exit(1);
  }
  await ensureAuth();
  const portalId = getPortalId();
  const pageData = await spGet('/api/now/sp/page?id=adb_esc_kb_article&sysparm_article=' + kbNumber + '&portal_id=' + portalId);
  const widgets = extractWidgets(pageData);
  const articleWidget = findWidget(widgets, 'ADB: KB Article Page');
  const article = articleWidget && articleWidget.data;

  if (!article || !article.number) {
    console.error('KB article ' + kbNumber + ' not found.');
    process.exit(1);
  }

  const result = {
    number: article.number,
    title: article.short_description,
    issue: stripHtml(article.issue_or_question),
    applies_to: stripHtml(article.applies_to),
    solution: stripHtml(article.solution_or_steps),
    additional_info: stripHtml(article.additional_information),
    modified: article.modified_on,
    views: article.sys_view_count
  };
  console.log(JSON.stringify(result, null, 2));
}

async function cmdMonday(args) {
  await ensureAuth();
  var userSysId = getUserSysId();
  var domain = getDomain();

  // Parse monday protocol flags
  var limit = 50;
  var date = '7d';
  for (var i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) { limit = parseInt(args[i + 1]); i++; }
    if (args[i] === '--date' && args[i + 1]) { date = args[i + 1]; i++; }
    if (args[i].startsWith('--limit=')) limit = parseInt(args[i].split('=')[1]);
    if (args[i].startsWith('--date=')) date = args[i].split('=')[1];
  }
  if (isNaN(limit) || limit < 1) {
    console.error('--limit must be a positive integer');
    process.exit(1);
  }

  // Parse date filter (e.g. "7d" -> 7 days ago)
  var daysBack = 7;
  var dateMatch = date.match(/^(\d+)d$/);
  if (dateMatch) daysBack = parseInt(dateMatch[1]);
  var cutoff = new Date(Date.now() - daysBack * 24 * 60 * 60 * 1000);
  var cutoffStr = cutoff.toISOString().replace('T', ' ').replace(/\.\d+Z$/, '');

  var items = [];

  // Fetch up to the full limit from each source; merge and slice after sorting
  // Fetch incidents (open + recently updated)
  var incQuery = 'caller_id=' + userSysId + '^sys_updated_on>=' + cutoffStr + '^ORDERBYDESCsys_updated_on';
  var incFields = 'number,short_description,state,priority,sys_id,sys_created_on,sys_updated_on,assignment_group,comments';
  var incidents = await tableGet('incident', incQuery, incFields, limit);

  var stateLabels = { '1': 'New', '2': 'In Progress', '3': 'On Hold', '6': 'Resolved', '7': 'Closed' };

  for (var inc of incidents) {
    items.push({
      id: 'sn-inc-' + inc.sys_id,
      source: 'servicenow',
      type: 'incident',
      title: inc.short_description || inc.number,
      subtitle: inc.number + ' (' + (stateLabels[inc.state] || inc.state) + ')',
      url: 'https://' + domain + '/esc?id=ticket&table=incident&sys_id=' + inc.sys_id,
      ts: inc.sys_updated_on ? inc.sys_updated_on.replace(' ', 'T') + 'Z' : inc.sys_created_on.replace(' ', 'T') + 'Z',
      body: inc.short_description || '',
      participants: [],
      meta: {
        state: stateLabels[inc.state] || inc.state,
        priority: inc.priority,
        number: inc.number
      }
    });
  }

  // Fetch open request items (recently updated)
  var ritmQuery = 'request.requested_for=' + userSysId + '^sys_updated_on>=' + cutoffStr + '^ORDERBYDESCsys_updated_on';
  var ritmFields = 'number,short_description,state,sys_id,sys_created_on,sys_updated_on';
  var ritms = await tableGet('sc_req_item', ritmQuery, ritmFields, limit);

  for (var ritm of ritms) {
    var ritmState = ritm.state === '1' ? 'Open' : ritm.state === '2' ? 'Work in Progress' : ritm.state === '3' ? 'Closed Complete' : ritm.state;
    items.push({
      id: 'sn-ritm-' + ritm.sys_id,
      source: 'servicenow',
      type: 'request',
      title: ritm.short_description || ritm.number,
      subtitle: ritm.number + ' (' + ritmState + ')',
      url: 'https://' + domain + '/esc?id=ticket&table=sc_req_item&sys_id=' + ritm.sys_id,
      ts: ritm.sys_updated_on ? ritm.sys_updated_on.replace(' ', 'T') + 'Z' : ritm.sys_created_on.replace(' ', 'T') + 'Z',
      body: ritm.short_description || '',
      participants: [],
      meta: {
        state: ritmState,
        number: ritm.number
      }
    });
  }

  // Sort by ts descending and limit
  items.sort(function(a, b) {
    return new Date(b.ts).getTime() - new Date(a.ts).getTime();
  });
  items = items.slice(0, limit);

  console.log(JSON.stringify(items, null, 2));
}

async function cmdCreate(args) {
  await ensureAuth();
  var userSysId = getUserSysId();

  // Parse flags
  var title = '';
  var description = '';
  var category = '';
  var subcategory = '';
  var attachments = [];

  for (var i = 0; i < args.length; i++) {
    if (args[i] === '--title' && args[i + 1]) { title = args[++i]; continue; }
    if (args[i].startsWith('--title=')) { title = args[i].split('=').slice(1).join('='); continue; }
    if (args[i] === '--description' && args[i + 1]) { description = args[++i]; continue; }
    if (args[i].startsWith('--description=')) { description = args[i].split('=').slice(1).join('='); continue; }
    if (args[i] === '--category' && args[i + 1]) { category = args[++i]; continue; }
    if (args[i].startsWith('--category=')) { category = args[i].split('=').slice(1).join('='); continue; }
    if (args[i] === '--subcategory' && args[i + 1]) { subcategory = args[++i]; continue; }
    if (args[i].startsWith('--subcategory=')) { subcategory = args[i].split('=').slice(1).join('='); continue; }
    if (args[i] === '--attach' && args[i + 1]) { attachments.push(args[++i]); continue; }
    if (args[i].startsWith('--attach=')) { attachments.push(args[i].split('=').slice(1).join('=')); continue; }
    // Positional: first is title, rest is description
    if (!title) { title = args[i]; continue; }
    if (!description) { description = args.slice(i).join(' '); break; }
  }

  if (!title) {
    console.error('Usage: servicenow create --title "Short description" [--description "Details"] [--category Software] [--subcategory Email] [--attach /path/to/file]');
    process.exit(1);
  }

  var payload = {
    caller_id: userSysId,
    short_description: title
  };
  if (description) payload.description = description;
  if (category) payload.category = category;
  if (subcategory) payload.subcategory = subcategory;

  var code = [
    'new Promise(function(resolve) {',
    '  var h = angular.element(document.body).injector().get("$http");',
    '  h.post("/api/now/table/incident", ' + JSON.stringify(payload).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + ').then(function(resp) {',
    '    resolve(JSON.stringify({number: resp.data.result.number, sys_id: resp.data.result.sys_id}));',
    '  }).catch(function(e) {',
    '    resolve(JSON.stringify({__error: e.status || 500, detail: e.data || "unknown"}));',
    '  });',
    '})'
  ].join('\n');

  var result = await evalInPage(code);
  if (result && result.__error) {
    console.error('Failed to create incident: ' + JSON.stringify(result));
    process.exit(1);
  }

  console.log('Created ' + result.number + ' — ' + title);

  // Attach files if specified
  for (var file of attachments) {
    await attachFile(result.sys_id, 'incident', file);
    var fileName = file.split('/').pop();
    console.log('  Attached: ' + fileName);
  }

  console.log(JSON.stringify(result, null, 2));
}

async function attachFile(sysId, table, filePath) {
  var fileName = filePath.split('/').pop();
  var ext = fileName.split('.').pop().toLowerCase();
  var mimeMap = { png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif', pdf: 'application/pdf', txt: 'text/plain' };
  var mime = mimeMap[ext] || 'application/octet-stream';

  var code = [
    '(async function() {',
    '  var h = angular.element(document.body).injector().get("$http");',
    '  var resp = await fetch("' + filePath.replace(/"/g, '\\"') + '");',
    '  if (!resp.ok) return JSON.stringify({__error: "fetch_failed", status: resp.status});',
    '  var blob = await resp.blob();',
    '  var result = await h({',
    '    method: "POST",',
    '    url: "/api/now/attachment/file?table_name=' + table + '&table_sys_id=' + sysId + '&file_name=' + encodeURIComponent(fileName) + '",',
    '    headers: { "Content-Type": "' + mime + '" },',
    '    data: blob,',
    '    transformRequest: angular.identity',
    '  });',
    '  return JSON.stringify({ok: true, sys_id: result.data.result.sys_id});',
    '})()'
  ].join('\n');

  var result = await evalInPage(code);
  if (result && result.__error) {
    console.error('Failed to attach ' + fileName + ': ' + JSON.stringify(result));
  }
  return result;
}

async function cmdAttach(args) {
  if (args.length < 2) {
    console.error('Usage: servicenow attach <NUMBER> <FILE_PATH> [<FILE_PATH>...]');
    process.exit(1);
  }
  await ensureAuth();
  var numberOrId = args[0];
  var files = args.slice(1);
  var resolved = await resolveNumber(numberOrId);

  for (var file of files) {
    var result = await attachFile(resolved.sys_id, resolved.table, file);
    var fileName = file.split('/').pop();
    if (result && result.ok) {
      console.log('Attached ' + fileName + ' to ' + numberOrId);
    } else {
      console.error('Failed to attach ' + fileName);
    }
  }
}

function showHelp() {
  console.log('ServiceNow — API client\n');
  console.log('Setup:');
  console.log('  login [--domain=DOMAIN]      Authenticate with ServiceNow (opens browser)');
  console.log('  whoami                       Show current user info\n');
  console.log('Tickets:');
  console.log('  tickets [--incidents|--requests] [--state=STATE]');
  console.log('                               List your open tickets');
  console.log('  create --title "..." [--description "..."] [--category ...] [--attach FILE]');
  console.log('                               Create a new incident');
  console.log('  get <NUMBER>                 Get ticket details + comments');
  console.log('  comment <NUMBER> <MSG>       Post a customer-visible comment');
  console.log('  worknote <NUMBER> <MSG>      Post an internal work note');
  console.log('  attach <NUMBER> <FILE> [...] Attach file(s) to a ticket\n');
  console.log('Knowledge Base:');
  console.log('  kb <QUERY>                   Search Knowledge Base');
  console.log('  kb-article <KB_NUMBER>       Get full KB article content\n');
  console.log('Monday Protocol:');
  console.log('  monday [--limit N] [--date Nd]');
  console.log('                               Output items in monday aggregator format\n');
  console.log('States: new, in-progress, on-hold, resolved, closed, all');
  console.log('Default domain: ' + DEFAULTS.domain);
  console.log('');
  console.log('Examples:');
  console.log('  servicenow login');
  console.log('  servicenow login --domain=mycompany.service-now.com');
  console.log('  servicenow tickets');
  console.log('  servicenow create --title "VPN broken" --description "Details..." --attach /tmp/screenshot.png');
  console.log('  servicenow get INC3616952');
  console.log('  servicenow attach INC3616952 /path/to/screenshot.png');
  console.log('  servicenow comment INC3616952 "Please provide an update"');
  console.log('  servicenow kb "VPN GlobalProtect"');
  console.log('  servicenow kb-article KB0023295');
  console.log('  servicenow monday --limit 20 --date 7d');
}

// --- Main ---
const rawArgs = process.argv.slice(2);
const cmd = rawArgs[0];
const args = rawArgs.slice(1);

// Load config early (non-fatal if missing — login will create it)
await loadConfig();

if (!cmd || cmd === 'help' || cmd === '--help') {
  showHelp();
  process.exit(cmd ? 0 : 1);
}

switch (cmd) {
  case 'login':
    await cmdLogin(args);
    break;
  case 'whoami':
    await cmdWhoami();
    break;
  case 'tickets':
    await cmdTickets(args);
    break;
  case 'get':
    await cmdGet(args[0]);
    break;
  case 'comment':
    await cmdComment(args[0], args.slice(1).join(' '));
    break;
  case 'worknote':
    await cmdWorknote(args[0], args.slice(1).join(' '));
    break;
  case 'kb':
    await cmdKb(args.join(' '));
    break;
  case 'kb-article':
    await cmdKbArticle(args[0]);
    break;
  case 'create':
  case 'new':
    await cmdCreate(args);
    break;
  case 'attach':
    await cmdAttach(args);
    break;
  case 'monday':
    await cmdMonday(args);
    break;
  default:
    console.error('Unknown command: ' + cmd);
    showHelp();
    process.exit(1);
}
