#!/bin/sh
# ---------------------------------------------------------------------------
# Build the github-dashboard sprinkle.
#
#   ./build.sh          (from the deployed sprinkle directory, or scripts/build.sh
#                        from the skill repository — it detects which layout it is in)
#
# That is the whole command. It needs esbuild and node on PATH and NOTHING
# from the network: the two dependencies are vendored under src/vendor/.
#
# What it does:
#   1. bundles src/markdown.js (+ vendored marked and DOMPurify) with esbuild
#      into ONE classic <script> body, format=iife, global name GHMarkdown;
#   2. splices that between the GHD-BUNDLE markers already present in
#      github-dashboard.shtml, in place, so the live artifact stays a single
#      self-contained .shtml at the same path;
#   3. verifies the result: markers intact, bundle non-empty, no top-level
#      await, the module script still parses.
#
# format=iife is not an aesthetic choice. A sprinkle module's TOP-LEVEL AWAIT
# blocks the iframe load event (harmless at 31 records, fatal at 101), and an
# iife emitted into a CLASSIC script cannot contain one: top-level await is a
# syntax error outside a module, so the check below is a real guarantee rather
# than a hope.
#
# Refreshing the vendored libraries (the only step that needs a network):
#   ipk install marked@18.0.14 dompurify@3.4.15   # in a scratch dir
#   cp node_modules/marked/lib/marked.esm.js      src/vendor/marked.esm.js
#   cp node_modules/dompurify/dist/purify.es.mjs  src/vendor/purify.es.mjs
#   then re-run ./build.sh and re-run the XSS fixtures (tests/xss-fixtures.json).
# ---------------------------------------------------------------------------
set -eu

# TWO LAYOUTS, ONE SCRIPT. The same file must build in both places, or the
# public copy and the deployed copy drift and only one of them is ever tested:
#   A. deployed sprinkle  — this script sits NEXT TO the panel
#      (/shared/sprinkles/github-dashboard/)
#   B. skill repository   — this script sits in scripts/, the panel in
#      assets/sprinkle/, sources in src/, fixtures in tests/
SELF="$(cd "$(dirname "$0")" && pwd)"
if [ -f "$SELF/github-dashboard.shtml" ]; then
  BASE="$SELF"
  PANEL="github-dashboard.shtml"
else
  BASE="$(cd "$SELF/.." && pwd)"
  PANEL="assets/sprinkle/github-dashboard.shtml"
fi
cd "$BASE"
ENTRY=src/markdown.js
OUT=.build/markdown.bundle.js

test -f "$PANEL" || { echo "build: $PANEL missing" >&2; exit 2; }
test -f "$ENTRY" || { echo "build: $ENTRY missing" >&2; exit 2; }
grep -q 'GHD-BUNDLE:START' "$PANEL" || { echo "build: GHD-BUNDLE:START marker missing from $PANEL" >&2; exit 2; }
grep -q 'GHD-BUNDLE:END' "$PANEL" || { echo "build: GHD-BUNDLE:END marker missing from $PANEL" >&2; exit 2; }

mkdir -p .build
esbuild "$ENTRY" \
  --bundle \
  --format=iife \
  --target=es2022 \
  --minify \
  --platform=browser \
  --outfile="$OUT"

test -s "$OUT" || { echo "build: bundle is empty" >&2; exit 3; }
node --check "$OUT" || { echo "build: bundle does not parse as a classic script" >&2; exit 3; }

BEFORE=$(wc -c < "$PANEL")
node - "$PANEL" "$OUT" <<'SPLICE'
const fs = require('fs');
const [panelPath, bundlePath] = process.argv.slice(2);
const panel = fs.readFileSync(panelPath, 'utf8');
const bundle = fs.readFileSync(bundlePath, 'utf8').replace(/\s+$/, '');
if (/<\/script/i.test(bundle)) throw new Error('bundle contains </script — refusing to splice');
const START = '<!-- GHD-BUNDLE:START';
const END = '<!-- GHD-BUNDLE:END -->';
const a = panel.indexOf(START);
const b = panel.indexOf(END);
if (a < 0 || b < 0 || b < a) throw new Error('markers missing or out of order');
const head =
  START +
  ' generated by ./build.sh — DO NOT EDIT BY HAND.\n' +
  '         Source: src/markdown.js + src/vendor/{marked.esm.js,purify.es.mjs}.\n' +
  '         Rebuild: cd /shared/sprinkles/github-dashboard && ./build.sh -->\n' +
  '    <script>' + bundle + '</script>\n    ';
fs.writeFileSync(panelPath, panel.slice(0, a) + head + panel.slice(b));
SPLICE

AFTER=$(wc -c < "$PANEL")
BUNDLE_BYTES=$(wc -c < "$OUT")

# The module script must still parse: extract it and run node --check.
node - "$PANEL" <<'CHECK'
const fs = require('fs');
const s = fs.readFileSync(process.argv[2], 'utf8');
const m = s.match(/<script type="module">([\s\S]*?)<\/script>/);
if (!m) throw new Error('module script not found');
fs.writeFileSync('.build/module.mjs', m[1]);
// TOP-LEVEL await test, done properly: a regex on indentation cannot tell a
// module-top-level await from one inside an async function. Wrapping the body
// in a NON-async function can: a top-level await then becomes a SyntaxError,
// while awaits nested in async functions stay legal. (The panel's module uses
// no import/export, checked, so the wrap is valid.)
fs.writeFileSync('.build/module-tla-probe.js', '(function(){\n' + m[1] + '\n});');
CHECK
node --check .build/module-tla-probe.js 2>/dev/null || { echo "build: TOP-LEVEL AWAIT (or a non-wrappable construct) in the module script" >&2; exit 3; }
node --input-type=module --check < .build/module.mjs || { echo "build: module script does not parse" >&2; exit 3; }

# The XSS acceptance gate, as a STANDALONE page. The fixtures must be
# re-runnable by someone who does not have my probe harness:
#   open /shared/sprinkles/github-dashboard/tests/xss-gate.html
# and the verdict is on screen (and in the tab title). It runs the SAME bundle
# the panel ships. The runner lives in tests/gate-runner.js and is inlined
# VERBATIM — it used to be a nested string in this file, and one collapsed
# escaping level wrote a raw control byte into the page, which silently broke
# the whole runner. Generators that quote code inside code are not worth it.
node - tests/xss-gate.html "$OUT" tests/xss-fixtures.json tests/gate-runner.js <<'GATE'
const fs = require("fs");
const [outPath, bundlePath, fixturesPath, runnerPath] = process.argv.slice(2);
const bundle = fs.readFileSync(bundlePath, "utf8");
const runner = fs.readFileSync(runnerPath, "utf8");
const fixtures = fs.readFileSync(fixturesPath, "utf8");
const CLOSE = "<" + "/" + "script" + ">";
const OPEN = "<" + "script" + ">";
// A fixture body legitimately contains </script>; escaped as <\\/ inside the
// JSON string it cannot close the element, and JSON.parse restores it.
const jsonSafe = fixtures.split("</").join("<\\/");
for (const [name, src] of [["bundle", bundle], ["runner", runner]]) {
  if (src.toLowerCase().includes("</script")) throw new Error(name + " contains a closing script tag");
  for (const ch of src) if (ch.charCodeAt(0) < 9) throw new Error(name + " contains a raw control byte");
}
const html = [
  "<!DOCTYPE html>",
  "<html lang=\"en\"><head><meta charset=\"utf-8\" />",
  "<title>github-dashboard markdown XSS gate</title>",
  "<style>body{font:13px/1.5 ui-monospace,monospace;padding:16px;background:#fff;color:#111}#verdict{font-size:16px;font-weight:700;margin:12px 0}.good{color:#0a7}.bad{color:#c22}.row{white-space:pre-wrap}</style>",
  "</head><body>",
  "<h1 style=\"font-size:15px\">Markdown XSS acceptance gate</h1>",
  "<p>Generated by build.sh from src/markdown.js, tests/xss-fixtures.json and tests/gate-runner.js. Runs the same bundle the panel ships.</p>",
  "<div id=\"verdict\">running…</div><div id=\"out\"></div>",
  "<script type=\"application/json\" id=\"fixtures\">" + jsonSafe + CLOSE,
  OPEN + bundle + CLOSE,
  OPEN + runner + CLOSE,
  "</body></html>",
].join("\n");
fs.writeFileSync(outPath, html);
GATE
printf 'build: gate page tests/xss-gate.html (%s B) — open it to re-run the fixtures\n' "$(wc -c < tests/xss-gate.html)"
printf 'build: bundle %s B -> panel %s B (was %s B)\n' "$BUNDLE_BYTES" "$AFTER" "$BEFORE"
printf 'build: bundle sha256 %s\n' "$(sha256sum "$OUT" | cut -d' ' -f1)"
printf 'build: panel  md5    %s\n' "$(md5sum "$PANEL" | cut -d' ' -f1)"
