// wiki.jsh — CLI for the LLM wiki knowledge base at /mnt/kb
const WIKI_ROOT='/mnt/kb',RAW_DIR=WIKI_ROOT+'/_raw',CATS=['people','work','creative','tech','taste','life','events','places','projects'];
const args=process.argv.slice(2),sub=(args[0]||'').toLowerCase();
function en(e){return typeof e==='string'?e:e.name}
async function catDirs(cs){const r=[];for(const c of cs){try{const es=await fs.readDir(WIKI_ROOT+'/'+c);for(const e of es){const n=en(e);if(n&&n.endsWith('.md'))r.push({cat:c,file:n,path:WIKI_ROOT+'/'+c+'/'+n})}}catch(_){}}return r}
function t(f){return f.replace(/\.md$/,'').replace(/-/g,' ')}
async function find(name){let c=null,s=name;if(name.includes('/')){const p=name.split('/');c=p[0];s=p.slice(1).join('/')}s=s.replace(/\.md$/,'');const ds=c?[c]:CATS;for(const d of ds){const p=WIKI_ROOT+'/'+d+'/'+s+'.md';if(await fs.exists(p))return{cat:d,file:s+'.md',path:p}}const l=s.toLowerCase();for(const d of ds){try{const es=await fs.readDir(WIKI_ROOT+'/'+d);for(const e of es){const n=en(e);if(n&&n.replace(/\.md$/,'').toLowerCase()===l)return{cat:d,file:n,path:WIKI_ROOT+'/'+d+'/'+n}}}catch(_){}}return null}
function wl(c){const r=/\[\[([^\]]+)\]\]/g,ls=[];let m;while((m=r.exec(c))!==null)ls.push(m[1]);return ls}

async function cmdSearch(){const term=args.slice(1).join(' ');if(!term){console.error('Usage: wiki search <term>');process.exit(1)}const lo=term.toLowerCase(),pages=await catDirs(CATS);let h=0;for(const p of pages){if(h>=20)break;const nm=p.file.toLowerCase().includes(lo);let lm=null;try{const c=await fs.readFile(p.path);for(const line of c.split('\n'))if(line.toLowerCase().includes(lo)){lm=line.trim();break}}catch(_){continue}if(nm||lm){console.log('  '+p.cat+'/'+p.file+'  —  '+(lm||t(p.file)));h++}}if(!h)console.log('No results for "'+term+'".');else console.log('\n'+h+' result'+(h===1?'':'s')+'.')}

async function cmdList(){const c=args[1]?args[1].toLowerCase():null;if(c&&!CATS.includes(c)){console.error('Unknown category: '+c+'\nCategories: '+CATS.join(', '));process.exit(1)}const pages=await catDirs(c?[c]:CATS);if(!pages.length){console.log(c?'No pages in '+c+'.':'No wiki pages found.');return}let cur=null;for(const p of pages){if(p.cat!==cur){if(cur)console.log('');console.log(p.cat+'/');cur=p.cat}console.log('  '+t(p.file)+'  ('+p.cat+'/'+p.file+')')}console.log('\n'+pages.length+' page'+(pages.length===1?'':'s')+' total.')}

async function cmdRead(){const name=args.slice(1).join(' ');if(!name){console.error('Usage: wiki read <note-name>');process.exit(1)}const n=await find(name);if(!n){console.error('Page not found: '+name);process.exit(1)}try{const c=await fs.readFile(n.path);console.log('['+n.cat+'/'+n.file+']\n');console.log(c)}catch(e){console.error('Error: '+e.message);process.exit(1)}}

async function cmdStats(){console.log('Wiki pages by category:');let tot=0;for(const c of CATS){try{const es=await fs.readDir(WIKI_ROOT+'/'+c);const md=es.filter(e=>{const n=en(e);return n&&n.endsWith('.md')});if(md.length)console.log('  '+c.padEnd(12)+' '+md.length);tot+=md.length}catch(_){}}console.log('  '+'total'.padEnd(12)+' '+tot);let rc=0,ea=null,la=null;try{const re=await fs.readDir(RAW_DIR);const mf=re.map(e=>en(e)).filter(n=>n&&n.endsWith('.md'));rc=mf.length;const ds=[];for(const f of mf){const m=f.match(/^(\d{4}-\d{2}-\d{2})_/);if(m)ds.push(m[1])}ds.sort();if(ds.length){ea=ds[0];la=ds[ds.length-1]}}catch(_){}console.log('\nRaw source files: '+rc);if(ea&&la)console.log('  Date range: '+ea+' to '+la);let tl=0;const pages=await catDirs(CATS);for(const p of pages){try{tl+=wl(await fs.readFile(p.path)).length}catch(_){}}console.log('\nTotal wikilinks: '+tl)}

async function cmdLinks(){const name=args.slice(1).join(' ');if(!name){console.error('Usage: wiki links <note-name>');process.exit(1)}const n=await find(name);if(!n){console.error('Page not found: '+name);process.exit(1)}let ob=[];try{ob=[...new Set(wl(await fs.readFile(n.path)))]}catch(e){console.error('Error: '+e.message);process.exit(1)}console.log('Links for: '+n.cat+'/'+n.file+'\n');console.log('Outbound ('+ob.length+'):');if(!ob.length)console.log('  (none)');else for(const l of ob.sort())console.log('  -> [['+l+']]');const nm=n.file.replace(/\.md$/,''),pages=await catDirs(CATS),ib=[];for(const p of pages){if(p.path===n.path)continue;try{if(wl(await fs.readFile(p.path)).some(l=>l===nm))ib.push(p.cat+'/'+p.file)}catch(_){}}console.log('\nInbound ('+ib.length+'):');if(!ib.length)console.log('  (none)');else for(const r of ib.sort())console.log('  <- '+r)}

async function cmdOrphans(){const pages=await catDirs(CATS),linked=new Set();for(const p of pages){try{for(const l of wl(await fs.readFile(p.path)))linked.add(l)}catch(_){}}const orph=[];for(const p of pages){const s=p.file.replace(/\.md$/,'');if(!linked.has(s))orph.push(p.cat+'/'+p.file)}if(!orph.length){console.log('No orphan pages found.');return}console.log('Orphan pages ('+orph.length+'):\n');for(const o of orph)console.log('  '+o)}

async function cmdRecent(){const n=parseInt(args[1],10)||10;try{const es=await fs.readDir(RAW_DIR);const mf=es.map(e=>en(e)).filter(n=>n&&n.endsWith('.md'));const d=[];for(const f of mf){const m=f.match(/^(\d{4}-\d{2}-\d{2})_(.+?)_[0-9a-f]+\.md$/);if(m)d.push({date:m[1],title:m[2].replace(/-/g,' '),file:f})}d.sort((a,b)=>b.date.localeCompare(a.date));const s=d.slice(0,n);console.log(s.length+' most recent raw sources:\n');for(const e of s){console.log('  '+e.date+'  '+e.title);console.log('             '+e.file)}}catch(e){console.error('Error: '+e.message);process.exit(1)}}

async function cmdLog(){const n=parseInt(args[1],10)||10;const lp=WIKI_ROOT+'/log.md';try{if(!(await fs.exists(lp))){console.log('log.md does not exist yet.');return}const c=await fs.readFile(lp),lines=c.split('\n'),entries=[];let cur=null;for(const l of lines){if(l.startsWith('## ')){if(cur)entries.push(cur);cur={heading:l,body:[]}}else if(cur)cur.body.push(l)}if(cur)entries.push(cur);if(!entries.length){console.log('No log entries found.');return}const s=entries.slice(-n);console.log('Last '+s.length+' log entr'+(s.length===1?'y':'ies')+':\n');for(const e of s){console.log(e.heading);for(const b of e.body.filter(l=>l.trim()).slice(0,3))console.log('  '+b.trim());console.log('')}}catch(e){console.error('Error: '+e.message);process.exit(1)}}

function cmdHelp(){console.log('wiki — LLM wiki knowledge base CLI\n\nUsage: wiki <command> [args]\n\nCommands:\n  search <term>      Search wiki pages by title and content (max 20 results)\n  list [category]    List all wiki pages, optionally filtered by category\n  read <note>        Display a wiki page (accepts name, name.md, or category/name)\n  stats              Pages per category, raw file count, date range, wikilink count\n  links <note>       Show inbound and outbound wikilinks for a note\n  orphans            Find pages with zero inbound links\n  recent [n]         Show N most recent raw source files (default 10)\n  log [n]            Show last N log.md entries (default 10)\n  help               Show this help\n\nCategories: '+CATS.join(', ')+'\nWiki root:  '+WIKI_ROOT)}

switch(sub){case 'search':await cmdSearch();break;case 'list':await cmdList();break;case 'read':await cmdRead();break;case 'stats':await cmdStats();break;case 'links':await cmdLinks();break;case 'orphans':await cmdOrphans();break;case 'recent':await cmdRecent();break;case 'log':await cmdLog();break;case 'help':cmdHelp();break;default:cmdHelp();break}
