// TikTok web API client -- generated by secret-sauce.
//
// TikTok's web app protects its own JSON API (/api/*) with anti-bot request
// signatures (X-Bogus / X-Gnarly / X-Dynosaur / msToken). These are injected
// automatically by TikTok's own `webmssdk` bundle, which hooks window.fetch and
// XMLHttpRequest on the page. So the ONLY reliable way to call the API is to
// issue the fetch() from inside a real, logged-in www.tiktok.com tab -- the
// webmssdk interceptor then signs the outbound request for us. We do that via
// browser.evalAsync (page-context eval). Direct Node fetch() would be rejected.
//
// Direct messages (DMs) are delivered over an encrypted "Frontier" WebSocket,
// not REST, so conversation history / send are handled through the rendered DOM
// (playwright-cli), not the API.

const { exec } = require('sliccy:exec');
const browser = require('sliccy:browser');
const fs = require('fs');

const TT_DOMAIN = 'www.tiktok.com';
const TMP_DIR = '/workspace/skills/tiktok/.tmp';

// ---------------------------------------------------------------------------
// Tab management
// ---------------------------------------------------------------------------

let _tab = null;

async function findTab() {
  if (_tab) return _tab;
  // Prefer a main web-app page (root / profile / video / search / messages).
  // Explicitly avoid tiktokstudio, ads, and other sub-apps whose page
  // app-context is structured differently (no webapp user, wrong appId).
  let tab = await browser.findTab({ urlMatch: /www\.tiktok\.com\/(@|foryou|search|explore|following|friends|messages|explore|$|\?)/ });
  if (!tab) tab = await browser.findTab({ urlMatch: /www\.tiktok\.com\/(?!tiktokstudio|ads|business)/ });
  if (!tab) tab = await browser.findTab({ domain: TT_DOMAIN });
  if (!tab) tab = await browser.findTab({ urlMatch: /(^|\.)tiktok\.com/ });
  if (!tab) {
    console.error('Error: No TikTok tab found. Open https://www.tiktok.com in your browser (logged in) and try again.');
    process.exit(1);
  }
  _tab = tab;
  return _tab;
}

// A CDP session dies when the tab is closed or its target is recycled. Every
// eval below addresses the tab by targetId, so once that happens EVERY call
// fails with -32001 until the process restarts. Reloading cannot help: the
// target id itself is gone, so recovery means a brand-new tab.
const DEAD_SESSION_RE = /-32001|Session with given id not found|Target closed|No target with given id|Inspected target/i;

function isDeadSession(text) {
  return !!text && DEAD_SESSION_RE.test(String(text));
}

// Open a fresh tab and adopt it, reading the target id straight out of
// `playwright-cli open` so we never re-adopt the dead tab that is still listed.
async function openFreshTab(url) {
  const target = url && /tiktok\.com/.test(url) ? url : 'https://www.tiktok.com/';
  _tab = null;
  let stdout = '';
  try {
    const r = await exec('playwright-cli open ' + target);
    stdout = (r && r.stdout) || '';
  } catch (e) {
    return await findTab();
  }
  const m = /targetId:\s*([0-9A-Za-z]+)/.exec(stdout);
  if (m) {
    _tab = { targetId: m[1], url: target };
    // Deliberately NOT `open --fg`: that returns a target id whose CDP session
    // is not attachable yet (-32001). Open in the background, then foreground it
    // by index, which is attachable and lets the player decode.
    await sleep(800);
    await focusTab(_tab);
    return _tab;
  }
  return await findTab();
}

// A hidden tab never decodes video: the <video> element exists but reports
// readyState 0 and duration NaN for as long as the tab stays in the background,
// so any frame capture fails. Bringing the tab to the front fixes it. tab-list
// is 1-based by line, which is what tab-select expects.
async function focusTab(tab) {
  if (!tab || !tab.targetId) return false;
  try {
    const r = await exec('playwright-cli tab-list');
    const lines = String((r && r.stdout) || '').split('\n').filter((l) => l.trim());
    for (let i = 0; i < lines.length; i++) {
      if (lines[i].indexOf(tab.targetId) !== -1) {
        await exec('playwright-cli tab-select ' + (i + 1));
        await sleep(700);
        return true;
      }
    }
  } catch (e) {}
  return false;
}

// Run `playwright-cli eval-file` against a tab, recovering once from a dead
// session. The output file is truncated first: pwEval/pwEvalAsync reuse fixed
// filenames, so a leftover result from an earlier call would otherwise be read
// back as a fresh success.
async function evalFileOnTab(tab, exprFile, outFile) {
  async function once(t) {
    try { fs.writeFileSync(outFile, ''); } catch (e) {}
    let stderr = '';
    let failed = null;
    try {
      const r = await exec('playwright-cli eval-file ' + exprFile + ' --tab=' + t.targetId + ' --output=' + outFile);
      stderr = (r && r.stderr) || '';
    } catch (e) {
      failed = (e && e.message) ? e.message : String(e);
    }
    let out = '';
    try { out = fs.readFileSync(outFile, 'utf8'); } catch (e) {}
    return { out: out, stderr: stderr, failed: failed, tab: t };
  }

  let res = await once(tab);
  if (!res.out && isDeadSession(res.stderr + ' ' + (res.failed || ''))) {
    const fresh = await openFreshTab(tab && tab.url);
    if (fresh && fresh.targetId && fresh.targetId !== tab.targetId) res = await once(fresh);
  }
  return res;
}

// ---------------------------------------------------------------------------
// API helper -- page-context fetch, auto-signed by webmssdk
// ---------------------------------------------------------------------------

// Core signed request. Runs a fetch from inside the TikTok tab's MAIN world
// (via `playwright-cli eval-file`), where TikTok's webmssdk hooks window.fetch
// to inject the anti-bot signature (X-Bogus/X-Gnarly/msToken). browser.evalAsync
// runs an isolated world without that hook, so signature-required endpoints
// reject with 10201/HTTP 400 -- that's why we shell out to eval-file here.
//
// opts: { url, method='GET', query={}, body=null, useCommon=true }
//   - url: a path ('/api/...') or absolute URL. Any existing query string is kept.
//   - query: extra query params merged in (after the common params).
//   - body: object -> JSON-stringified POST/PUT body.
//   - useCommon: prepend the standard TikTok web params (aid=1988, device_id,
//     region, odinId, ...) read live from the page app-context.
// Returns { status, bodyText, data } where data is parsed JSON or null.
async function signedRequest(opts) {
  const { url, method = 'GET', query = {}, body = null, useCommon = true } = opts;
  let tab = await findTab();
  const expr = `
    (async () => {
      let ctx = {};
      try {
        const el = document.getElementById('__UNIVERSAL_DATA_FOR_REHYDRATION__');
        if (el) ctx = JSON.parse(el.textContent).__DEFAULT_SCOPE__['webapp.app-context'] || {};
      } catch (e) {}
      const nav = navigator;
      const uid = (ctx.user && (ctx.user.uid || ctx.user.userId)) || '';
      const os = /Mac/.test(nav.platform) ? 'mac' : /Win/.test(nav.platform) ? 'windows' : 'linux';
      const base = {
        aid: '1988',
        app_name: 'tiktok_web',
        app_language: ctx.language || 'en',
        channel: 'tiktok_web',
        device_platform: 'web_pc',
        region: ctx.region || 'US',
        priority_region: ctx.region || '',
        os: os,
        cookie_enabled: String(nav.cookieEnabled),
        screen_width: String(screen.width),
        screen_height: String(screen.height),
        browser_language: nav.language || 'en-US',
        browser_platform: nav.platform || 'MacIntel',
        browser_name: 'Mozilla',
        browser_online: String(nav.onLine),
        device_id: String(ctx.wid || ctx.webId || ''),
        odinId: String(uid),
        user_is_login: String(!!uid),
        webcast_language: ctx.language || 'en',
        tz_name: Intl.DateTimeFormat().resolvedOptions().timeZone || 'UTC',
        from_page: 'fyp'
      };
      const useCommon = ${JSON.stringify(useCommon)};
      const query = ${JSON.stringify(query)};
      const merged = useCommon ? Object.assign({}, base, query) : query;
      const qs = new URLSearchParams(merged).toString();
      let u = ${JSON.stringify(url)};
      if (qs) u += (u.indexOf('?') === -1 ? '?' : '&') + qs;
      const init = { method: ${JSON.stringify(method)}, credentials: 'include', headers: { accept: 'application/json, text/plain, */*' } };
      const bodyObj = ${JSON.stringify(body)};
      if (bodyObj != null) { init.headers['content-type'] = 'application/json'; init.body = typeof bodyObj === 'string' ? bodyObj : JSON.stringify(bodyObj); }
      const r = await fetch(u, init);
      const text = await r.text();
      return JSON.stringify({ __ttStatus: r.status, __ttBody: text });
    })()
  `;
  // eval-file needs a file in the VFS; use a fixed per-command pair (overwritten
  // each call) so the .tmp dir never accumulates cruft.
  if (typeof fs.mkdirSync === 'function') { try { fs.mkdirSync(TMP_DIR, { recursive: true }); } catch (e) {} }
  const exprFile = `${TMP_DIR}/req.js`;
  const outFile = `${TMP_DIR}/res.json`;

  async function runOnce() {
    try {
      fs.writeFileSync(exprFile, expr);
      const r = await evalFileOnTab(tab, exprFile, outFile);
      tab = r.tab;
      if (!r.out) return { fail: r.failed || 'no-output', stderr: r.stderr };
      return { env: JSON.parse(r.out) };
    } catch (e) {
      return { fail: e && e.message ? e.message : String(e) };
    }
  }

  let res = await runOnce();
  // A 200 with an empty body is TikTok's soft anti-abuse throttle. Back off once.
  const isThrottled = (r) => r.env && r.env.__ttStatus === 200 && !r.env.__ttBody;
  if (res.fail === 'no-output' || isThrottled(res)) {
    await new Promise((r) => setTimeout(r, 3000));
    res = await runOnce();
  }

  if (res.fail && !res.env) {
    console.error('Page eval failed:', res.fail);
    if (res.stderr) console.error(res.stderr.trim());
    console.error('The TikTok tab may have navigated or lost its context.');
    console.error('Open a NEW www.tiktok.com tab and retry — reloading the old one cannot revive a dead');
    console.error('CDP session, because the target id is gone. `playwright-cli tab-list` shows live tabs.');
    process.exit(1);
  }
  const status = res.env.__ttStatus;
  const bodyText = res.env.__ttBody;
  let data = null;
  if (bodyText) { try { data = JSON.parse(bodyText); } catch (e) {} }
  return { status, bodyText, data };
}

// Convenience wrapper: GET a path with common params, return parsed JSON or exit
// with a clear message on the common failure modes.
async function apiGet(path, params = {}) {
  const { status, bodyText, data } = await signedRequest({ url: path, query: params });
  if (status === 401 || status === 403) {
    console.error(`Error: TikTok returned HTTP ${status}. Your session may have expired -- log into www.tiktok.com in your browser and try again.`);
    process.exit(1);
  }
  if (!bodyText) {
    console.error(`Error: TikTok returned an empty body (HTTP ${status}). TikTok is throttling this session (too many requests in a short window). Wait ~30s and retry, or reload www.tiktok.com.`);
    process.exit(1);
  }
  if (data == null) {
    console.error(`Error: could not parse TikTok response (HTTP ${status}): ${bodyText.slice(0, 200)}`);
    process.exit(1);
  }
  if (data.status_code === 10201) {
    console.error('Error: TikTok rejected the request signature (status 10201). Make sure the active tab is a fully-loaded www.tiktok.com page (not /messages or a login page), then retry.');
    process.exit(1);
  }
  return data;
}

function num(n) {
  n = Number(n) || 0;
  if (n >= 1e9) return (n / 1e9).toFixed(1) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(1) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'K';
  return String(n);
}

function ts(sec) {
  if (!sec) return '';
  try { return new Date(Number(sec) * 1000).toISOString().replace('T', ' ').slice(0, 16); }
  catch (e) { return String(sec); }
}

// ---------------------------------------------------------------------------
// Commands
// ---------------------------------------------------------------------------

async function cmdWhoami() {
  const tab = await findTab();
  const raw = await browser.evalAsync(tab, `
    (() => {
      try {
        const el = document.getElementById('__UNIVERSAL_DATA_FOR_REHYDRATION__');
        const ctx = JSON.parse(el.textContent).__DEFAULT_SCOPE__['webapp.app-context'] || {};
        const u = ctx.user || {};
        return JSON.stringify({ loggedIn: !!(u.uid), uniqueId: u.uniqueId, nickName: u.nickName, uid: u.uid, secUid: u.secUid, region: u.region || ctx.region, isPrivate: u.isPrivateAccount });
      } catch (e) { return JSON.stringify({ error: String(e) }); }
    })()
  `.trim().replace(/\n/g, ' '));
  const u = typeof raw === 'string' ? JSON.parse(raw) : raw;
  if (u.error || !u.loggedIn) {
    console.error('Not logged in to TikTok, or the app-context could not be read. Open www.tiktok.com and sign in.');
    process.exit(1);
  }
  console.log(JSON.stringify(u, null, 2));
  return u;
}

async function cmdSearch(args, flags) {
  const keyword = args.join(' ').trim();
  if (!keyword) { console.error('Usage: tiktok search <query> [--type=general|video|user] [--count=N] [--cursor=N]'); process.exit(1); }
  const type = flags.type || 'general';
  const count = flags.count || '12';
  const cursor = flags.cursor || '0';

  if (type === 'user') {
    const d = await apiGet('/api/search/user/full/', { keyword, count, cursor, from_page: 'search' });
    const list = d.user_list || [];
    console.log(`Users matching "${keyword}" (${list.length}):\n`);
    for (const u of list) {
      const info = u.user_info || {};
      console.log(`@${info.unique_id}  "${info.nickname || ''}"`);
      console.log(`  followers: ${num(info.follower_count)}   secUid: ${info.sec_uid}`);
      if (info.signature) console.log(`  ${info.signature.replace(/\n/g, ' ').slice(0, 80)}`);
      console.log('');
    }
    console.log(`cursor: ${d.cursor}   has_more: ${d.has_more}`);
    return;
  }

  if (type === 'video') {
    const d = await apiGet('/api/search/item/full/', { keyword, count, cursor, offset: cursor, from_page: 'search' });
    const list = d.item_list || [];
    printVideoList(list.map((it) => it), `Videos matching "${keyword}"`);
    console.log(`cursor: ${d.cursor}   has_more: ${d.has_more}`);
    return;
  }

  // general: mixed feed of items + users
  const d = await apiGet('/api/search/general/full/', {
    keyword, count, cursor, offset: cursor, from_page: 'search',
    web_search_code: '{"tiktok":{"client_params_x":{"search_engine":{"ies_mt_user_live_video_card_use_libra":1,"mt_search_general_user_live_card":1}},"search_server":{}}}'
  });
  const data = d.data || [];
  console.log(`Search results for "${keyword}" (${data.length}):\n`);
  for (const row of data) {
    if (row.item) {
      const it = row.item;
      const s = it.statsV2 || it.stats || {};
      console.log(`[video] ${it.id}  @${it.author && it.author.uniqueId}`);
      console.log(`  ${(it.desc || '').replace(/\n/g, ' ').slice(0, 80)}`);
      console.log(`  ▶ ${num(s.playCount)}  ❤ ${num(s.diggCount)}  💬 ${num(s.commentCount)}  ↪ ${num(s.shareCount)}`);
    } else if (row.user_list && row.user_list[0]) {
      const info = row.user_list[0].user_info || {};
      console.log(`[user] @${info.unique_id}  "${info.nickname || ''}"  followers: ${num(info.follower_count)}`);
    }
    console.log('');
  }
  console.log(`cursor: ${d.cursor}   has_more: ${d.has_more}`);
}

function printVideoList(items, title) {
  console.log(`${title} (${items.length}):\n`);
  for (const it of items) {
    const s = it.statsV2 || it.stats || {};
    console.log(`${it.id}  @${it.author && (it.author.uniqueId || it.author.unique_id)}`);
    console.log(`  ${(it.desc || '').replace(/\n/g, ' ').slice(0, 80)}`);
    console.log(`  ▶ ${num(s.playCount)}  ❤ ${num(s.diggCount)}  💬 ${num(s.commentCount)}  ↪ ${num(s.shareCount)}  🔖 ${num(s.collectCount)}   posted: ${ts(it.createTime)}`);
    console.log('');
  }
}

async function cmdVideo(args) {
  const id = (args[0] || '').replace(/[^0-9]/g, '');
  if (!id) { console.error('Usage: tiktok video <videoId>   (numeric id, e.g. from a tiktok.com/@user/video/<id> URL)'); process.exit(1); }
  const d = await apiGet('/api/item/detail/', { itemId: id });
  const it = d.itemInfo && d.itemInfo.itemStruct;
  if (!it) { console.error(`No video found for id ${id} (status_code=${d.status_code}, msg="${d.status_msg || ''}").`); process.exit(1); }
  const s = it.statsV2 || it.stats || {};
  const a = it.author || {};
  console.log(`Video ${it.id}`);
  console.log(`  author:   @${a.uniqueId}  "${a.nickname || ''}"`);
  console.log(`  desc:     ${(it.desc || '').replace(/\n/g, ' ')}`);
  console.log(`  posted:   ${ts(it.createTime)}`);
  console.log(`  duration: ${it.video && it.video.duration}s`);
  console.log('  --- stats ---');
  console.log(`  plays:    ${num(s.playCount)}  (${s.playCount})`);
  console.log(`  likes:    ${num(s.diggCount)}  (${s.diggCount})`);
  console.log(`  comments: ${num(s.commentCount)}  (${s.commentCount})`);
  console.log(`  shares:   ${num(s.shareCount)}  (${s.shareCount})`);
  console.log(`  saves:    ${num(s.collectCount)}  (${s.collectCount})`);
  if (s.repostCount != null) console.log(`  reposts:  ${num(s.repostCount)}  (${s.repostCount})`);
  console.log(`  url:      https://www.tiktok.com/@${a.uniqueId}/video/${it.id}`);
}

async function cmdComments(args, flags) {
  const id = (args[0] || '').replace(/[^0-9]/g, '');
  if (!id) { console.error('Usage: tiktok comments <videoId> [--count=N] [--cursor=N]'); process.exit(1); }
  const d = await apiGet('/api/comment/list/', { aweme_id: id, count: flags.count || '20', cursor: flags.cursor || '0' });
  const comments = d.comments || [];
  console.log(`Comments on ${id} (${comments.length} of ${d.total}):\n`);
  for (const c of comments) {
    const u = c.user || {};
    console.log(`@${u.unique_id}  ❤ ${num(c.digg_count)}   ${ts(c.create_time)}`);
    console.log(`  ${(c.text || '').replace(/\n/g, ' ')}`);
    console.log('');
  }
  console.log(`cursor: ${d.cursor}   has_more: ${d.has_more}`);
}

// Reads the logged-in user's own secUid from the page app-context. Used to
// default the profile-list commands when no secUid is given -- handy since the
// Liked / Favorites tabs are usually only visible for your own account.
async function ownSecUid() {
  const tab = await findTab();
  const raw = await browser.evalAsync(tab, `
    (() => { try { const el=document.getElementById('__UNIVERSAL_DATA_FOR_REHYDRATION__'); const c=JSON.parse(el.textContent).__DEFAULT_SCOPE__['webapp.app-context']||{}; return JSON.stringify({secUid:(c.user&&c.user.secUid)||''}); } catch(e){ return JSON.stringify({secUid:''}); } })()
  `.trim().replace(/\n/g, ' '));
  const o = typeof raw === 'string' ? JSON.parse(raw) : raw;
  return o.secUid || '';
}

// The four profile tabs share the same item_list shape (itemList/cursor/hasMore).
const PROFILE_TABS = {
  posted: { path: '/api/post/item_list/', label: 'Posted videos' },
  reposts: { path: '/api/repost/item_list/', label: 'Reposted videos' },
  liked: { path: '/api/favorite/item_list/', label: 'Liked videos' },
  favorites: { path: '/api/user/collect/item_list/', label: 'Favorited videos' },
};

// Shared implementation for posted/reposts/liked/favorites. `tabKey` selects the
// endpoint. secUid defaults to the logged-in user when omitted.
async function profileList(tabKey, args, flags) {
  const t = PROFILE_TABS[tabKey];
  let secUid = args[0];
  if (!secUid) {
    secUid = await ownSecUid();
    if (!secUid) {
      console.error(`Usage: tiktok ${tabKey} [<secUid>] [--count=N] [--cursor=N]`);
      console.error('No secUid given and could not read your own from the page. Get one via "tiktok search <name> --type=user".');
      process.exit(1);
    }
  }
  const d = await apiGet(t.path, {
    secUid,
    count: flags.count || '15',
    cursor: flags.cursor || '0',
    coverFormat: '2',
  });
  const items = d.itemList || [];
  if (!items.length) {
    console.log(`${t.label} (0) for secUid ${secUid.slice(0, 16)}...`);
    console.log('(Empty — this tab has no videos, or Liked/Favorites are private and only visible on your own account.)');
    return;
  }
  printVideoList(items, `${t.label} for secUid ${secUid.slice(0, 16)}...`);
  console.log(`cursor: ${d.cursor}   hasMore: ${d.hasMore}`);
}

async function cmdUserVideos(args, flags) { return profileList('posted', args, flags); }
async function cmdReposts(args, flags) { return profileList('reposts', args, flags); }
async function cmdLiked(args, flags) { return profileList('liked', args, flags); }
async function cmdFavorites(args, flags) { return profileList('favorites', args, flags); }

async function cmdNoticeCount() {
  const d = await apiGet('/api/notice/count/', {});
  const counts = d.notice_count || [];
  const names = {
    0: 'all', 1: 'system', 2: 'likes', 3: 'comments', 4: 'mentions',
    6: 'followers', 7: 'from-tiktok', 12: 'account-updates', 13: 'promotions',
    20: 'video-updates', 36: 'shop'
  };
  console.log('Unread notification counts by group:\n');
  for (const c of counts) {
    if (!c.count) continue;
    console.log(`  ${String(c.group).padEnd(4)} ${(names[c.group] || 'group ' + c.group).padEnd(18)} ${c.count}`);
  }
  const total = counts.find((c) => c.group === 0);
  console.log(`\n  total (group 0): ${total ? total.count : 0}`);
}

async function cmdNotifications(args, flags) {
  const group = flags.group || '500'; // 500 = combined "All activity" feed
  const count = Number(flags.count || '20');
  const markRead = flags['mark-read'] ? 1 : 0;
  const maxTime = flags.cursor ? Number(flags.cursor) : 0;
  const groupList = JSON.stringify([{ count, is_mark_read: markRead, group: Number(group), max_time: maxTime, min_time: 0 }]);
  const d = await apiGet('/api/notice/multi/', { group_list: groupList, from_page: 'activity' });
  const lists = d.notice_lists || [];
  const notices = (lists[0] && lists[0].notice_list) || [];

  const typeName = {
    1: 'system', 2: 'like', 3: 'comment', 6: 'follow', 12: 'update',
    41: 'suggested-account', 43: 'like', 44: 'friend-joined', 45: 'mention',
    56: 'reply', 62: 'comment', 74: 'follow-request', 82: 'mention', 87: 'tag'
  };

  console.log(`Notifications (group ${group}, ${notices.length}):\n`);
  for (const n of notices) {
    const label = typeName[n.type] || `type ${n.type}`;
    const read = n.has_read ? ' ' : '•';
    let who = '';
    let text = '';
    const dg = n.digg || n.comment || n.follow || n.at || n.mention || {};
    const from = dg.from_user || (dg.user_list && dg.user_list[0]) || n.from_user;
    if (from) who = '@' + (from.unique_id || from.uid || '');
    if (n.comment && n.comment.comment) text = n.comment.comment.text || '';
    if (dg.content) text = dg.content;
    console.log(`${read} [${label}] ${who}  ${ts(n.create_time)}`);
    if (text) console.log(`    ${text.replace(/\n/g, ' ').slice(0, 100)}`);
  }
  console.log(`\nhas_more: ${lists[0] && lists[0].has_more}`);
  if (notices.length) console.log(`next --cursor (max_time): ${notices[notices.length - 1].create_time}`);
  if (markRead) console.log('(marked as read)');
}

// ---------------------------------------------------------------------------
// Direct messages -- DOM based (Frontier WebSocket has no REST equivalent)
// ---------------------------------------------------------------------------

function targetId() {
  return findTab().then((t) => t.targetId);
}

async function ensureMessagesPage() {
  const tab = await findTab();
  const url = await browser.eval(tab, "location.pathname");
  if (!String(url).startsWith('/messages')) {
    await exec(`playwright-cli goto https://www.tiktok.com/messages --tab=${tab.targetId}`).catch(() => {});
    // goto acts on the active tab; fall back to in-page navigation which is reliable.
    await browser.eval(tab, "location.href = 'https://www.tiktok.com/messages'");
    await new Promise((r) => setTimeout(r, 5000));
  }
  return tab;
}

// Reads the rendered conversation list from the messages page DOM. Returns
// [{ name, preview, time, unread }]. Shared by `conversations` and `monday`.
async function readConversationsDom() {
  const tab = await ensureMessagesPage();
  const raw = await browser.evalAsync(tab, `
    (async () => {
      const rows = [...document.querySelectorAll('[class*="DivItemWrapper"]')];
      const out = [];
      for (const row of rows) {
        const ps = row.querySelectorAll('p');
        if (!ps.length) continue;
        const name = (ps[0] && ps[0].textContent || '').trim();
        if (!name) continue;
        const preview = (row.querySelector('p p') && row.querySelector('p p').textContent || '').trim();
        const times = [...row.querySelectorAll('*')].map(e => e.childNodes.length===1 && e.childNodes[0].nodeType===3 ? e.textContent.trim() : '').filter(t => /\\d{1,2}\\/\\d{1,2}\\/\\d{4}/.test(t));
        const badge = (row.querySelector('[class*="Badge"], sup, [class*="unread"]') || {}).textContent || '';
        out.push({ name, preview: preview.slice(0, 120), time: times[0] || '', unread: (badge || '').trim() });
      }
      return JSON.stringify(out);
    })()
  `.trim().replace(/\n/g, ' '));
  return typeof raw === 'string' ? JSON.parse(raw) : raw;
}

async function cmdConversations() {
  const list = await readConversationsDom();
  if (!list.length) {
    console.log('No conversations found (the messages list may still be loading, or you have no DMs).');
    return;
  }
  console.log(`Conversations (${list.length}):\n`);
  for (const c of list) {
    const u = c.unread && c.unread !== '0' ? ` [${c.unread} unread]` : '';
    console.log(`${c.name}${u}   ${c.time}`);
    if (c.preview) console.log(`  ${c.preview}`);
    console.log('');
  }
}

async function openConversation(tab, name) {
  const raw = await browser.evalAsync(tab, `
    (async () => {
      const rows = [...document.querySelectorAll('[class*="DivItemWrapper"]')];
      const target = rows.find(r => {
        const p = r.querySelector('p');
        return p && p.textContent.trim() === ${JSON.stringify(name)};
      }) || rows.find(r => {
        const p = r.querySelector('p');
        return p && p.textContent.trim().toLowerCase().includes(${JSON.stringify(name.toLowerCase())});
      });
      if (!target) return JSON.stringify({ ok: false });
      target.click();
      return JSON.stringify({ ok: true });
    })()
  `.trim().replace(/\n/g, ' '));
  const res = typeof raw === 'string' ? JSON.parse(raw) : raw;
  if (!res.ok) {
    console.error(`Conversation "${name}" not found. Run "tiktok conversations" to see available names.`);
    process.exit(1);
  }
  await new Promise((r) => setTimeout(r, 2500));
}

async function cmdReadMessages(args) {
  const name = args.join(' ').trim();
  if (!name) { console.error('Usage: tiktok read-messages "<conversation name>"'); process.exit(1); }
  const tab = await ensureMessagesPage();
  await openConversation(tab, name);
  const raw = await browser.evalAsync(tab, `
    (async () => {
      const items = [...document.querySelectorAll('[class*="DivMessageContent"], [class*="MessageItem"], [class*="DivChatItem"]')];
      let bubbles = items.map(el => (el.textContent || '').trim()).filter(Boolean);
      if (!bubbles.length) {
        const pane = document.querySelector('[class*="DivChatBox"], [class*="DivMessageList"], main');
        if (pane) bubbles = [...pane.querySelectorAll('p')].map(p => p.textContent.trim()).filter(Boolean);
      }
      return JSON.stringify(bubbles.slice(-40));
    })()
  `.trim().replace(/\n/g, ' '));
  const msgs = typeof raw === 'string' ? JSON.parse(raw) : raw;
  console.log(`Conversation with "${name}" (last ${msgs.length} messages):\n`);
  for (const m of msgs) console.log(`  ${m.replace(/\n/g, ' ')}`);
}

async function cmdSendMessage(args) {
  const name = args[0];
  const text = args.slice(1).join(' ');
  if (!name || !text) { console.error('Usage: tiktok send-message "<conversation name>" "<message text>"'); process.exit(1); }
  const tab = await ensureMessagesPage();
  // Sending requires the tab to be foregrounded so CDP key events are delivered.
  await exec(`playwright-cli tab-select 1`).catch(() => {});
  await openConversation(tab, name);
  // Focus the composer, type, and send.
  const focused = await browser.evalAsync(tab, `
    (async () => {
      const box = document.querySelector('[contenteditable="true"], textarea, [data-e2e="message-input-area"] [contenteditable]');
      if (!box) return JSON.stringify({ ok: false });
      box.focus();
      return JSON.stringify({ ok: true });
    })()
  `.trim().replace(/\n/g, ' '));
  const f = typeof focused === 'string' ? JSON.parse(focused) : focused;
  if (!f.ok) { console.error('Could not find the message composer. The conversation may not have opened.'); process.exit(1); }
  const { stdout } = await exec(`playwright-cli type ${JSON.stringify(text)}`);
  await new Promise((r) => setTimeout(r, 500));
  await exec(`playwright-cli press Enter`);
  await new Promise((r) => setTimeout(r, 1500));
  // Verify the composer cleared (best-effort).
  const check = await browser.evalAsync(tab, `
    (() => {
      const box = document.querySelector('[contenteditable="true"], textarea');
      return JSON.stringify({ remaining: box ? (box.textContent || box.value || '').trim() : null });
    })()
  `.trim().replace(/\n/g, ' '));
  const c = typeof check === 'string' ? JSON.parse(check) : check;
  if (c.remaining) {
    console.error(`Message may not have sent -- composer still shows: "${c.remaining}". Try running with the TikTok tab in the foreground.`);
    process.exit(1);
  }
  console.log(`Sent to "${name}": ${text}`);
}

// ---------------------------------------------------------------------------
// Raw API escape hatch (like `gh api`)
// ---------------------------------------------------------------------------

async function cmdApi(positional, flags, rawRest) {
  let path = positional[0];
  if (!path) {
    console.error('Usage: tiktok api <path> [--method=GET] [--query k=v ...] [--data \'<json>\'] [--bare] [--raw] [--include]');
    console.error('');
    console.error('Calls any TikTok endpoint from the logged-in, signed page context.');
    console.error('By default the standard web params (aid=1988, device_id, region, ...) are');
    console.error('prepended and the JSON response is pretty-printed. Examples:');
    console.error("  tiktok api /api/item/detail/ --query itemId=7210798564014837035");
    console.error("  tiktok api /api/comment/list/ -q aweme_id=123 -q count=5");
    console.error("  tiktok api /tiktok/v1/analytics/insights/ --bare \\");
    console.error("    --query 'type_requests=[{\"insight_type\":121,\"data_date_range\":1}]' --query time_offset=7200");
    process.exit(1);
  }
  const method = String(flags.method || flags.X || 'GET').toUpperCase();

  // Collect repeated --query / -q k=v (parseArgs keeps only the last, so re-scan).
  const query = {};
  for (let i = 0; i < rawRest.length; i++) {
    let kv = null;
    if ((rawRest[i] === '--query' || rawRest[i] === '-q') && i + 1 < rawRest.length) kv = rawRest[++i];
    else if (rawRest[i].startsWith('--query=')) kv = rawRest[i].slice('--query='.length);
    else if (rawRest[i].startsWith('-q=')) kv = rawRest[i].slice(3);
    if (kv) {
      const eq = kv.indexOf('=');
      if (eq !== -1) query[kv.slice(0, eq)] = kv.slice(eq + 1);
    }
  }

  let body = null;
  const rawBody = flags.data != null ? flags.data : (flags.d != null ? flags.d : null);
  if (rawBody != null && rawBody !== true) {
    try { body = JSON.parse(rawBody); } catch (e) { body = rawBody; }
  }
  const useCommon = !flags.bare;

  const { status, bodyText, data } = await signedRequest({ url: path, method, query, body, useCommon });
  if (flags.include || flags.i) console.error(`HTTP ${status}`);
  if (data != null && !flags.raw) console.log(JSON.stringify(data, null, 2));
  else console.log(bodyText || '');
  // process.exitCode is ignored by this runtime; exit explicitly or a failed
  // call reports success.
  if (status >= 400 || (data && data.status_code && data.status_code !== 0)) process.exit(1);
}

// ---------------------------------------------------------------------------
// TikTok Studio (creator analytics)
// ---------------------------------------------------------------------------

const STUDIO_RANGE = { '7d': 1, '28d': 2, '60d': 3, '365d': 4, '7': 1, '28': 2, '60': 3, '365': 4 };
// insight_type -> label (overview metrics)
const STUDIO_OVERVIEW = [
  [121, 'Video views', 'analytics_overview_views'],
  [122, 'Profile views', 'analytics_overview_profile_views'],
  [123, 'Likes', 'analytics_overview_likes'],
  [124, 'Comments', 'analytics_overview_comments'],
  [125, 'Shares', 'analytics_overview_shares'],
  [140, 'New followers', 'analytics_viewer_new_viewer'],
];

function metricSeries(m) {
  if (!m) return null;
  const listNode = m.list || m.new_viewer_list;
  const arr = listNode && Array.isArray(listNode.value) ? listNode.value : [];
  const total = arr.reduce((s, e) => s + (Number(e && e.value) || 0), 0);
  const delta = m.delta_change && m.delta_change.value != null ? Number(m.delta_change.value) : null;
  return { total, delta, days: arr.length };
}

async function cmdStudio(positional, flags) {
  const sub = positional[0] || 'analytics';
  if (sub === 'user') return studioUser();
  if (sub !== 'analytics' && sub !== 'overview') {
    console.error(`Unknown studio subcommand: ${sub}. Use "analytics" or "user".`);
    process.exit(1);
  }
  const rangeKey = String(flags.range || '7d').toLowerCase();
  const dr = STUDIO_RANGE[rangeKey] || 1;
  const rangeLabel = { 1: '7 days', 2: '28 days', 3: '60 days', 4: '365 days' }[dr];

  const typeReqs = STUDIO_OVERVIEW.map(([t]) => ({ insight_type: t, data_date_range: dr }));
  const d = await signedRequest({
    url: '/tiktok/v1/analytics/insights/',
    query: { type_requests: JSON.stringify(typeReqs), time_offset: '7200', is_dark_mode: 'false' },
  });
  if (!d.bodyText) {
    console.error('Error: TikTok returned an empty body (throttled). Wait ~30s and retry, or reload the tab.');
    process.exit(1);
  }
  if (!d.data) { console.error(`Error: could not parse analytics response (HTTP ${d.status}).`); process.exit(1); }
  if (d.data.status_code && d.data.status_code !== 0) {
    console.error(`Error: analytics request failed (status_code ${d.data.status_code}). Make sure you are logged in as a creator and the active tab is www.tiktok.com.`);
    process.exit(1);
  }

  const uid = (d.data && d.data.extra && d.data.extra.logid) ? '' : '';
  console.log(`TikTok Studio analytics — last ${rangeLabel}\n`);
  for (const [, label, key] of STUDIO_OVERVIEW) {
    const s = metricSeries(d.data[key]);
    if (!s) { console.log(`  ${label.padEnd(16)} n/a`); continue; }
    const deltaStr = s.delta == null ? '' : `  (Δ ${s.delta >= 0 ? '+' : ''}${num(s.delta)})`;
    console.log(`  ${label.padEnd(16)} ${num(s.total)}${deltaStr}`);
  }
  console.log(`\n(Totals summed over the ${rangeLabel} window. Use "tiktok api /tiktok/v1/analytics/insights/ ..." for per-day series or other insight_types.)`);
}

async function studioUser() {
  const { status, bodyText, data } = await signedRequest({ url: '/tiktokstudio/api/web/user', useCommon: false });
  if (!bodyText) { console.error('Error: empty response (throttled or not on a studio-capable session). Retry shortly.'); process.exit(1); }
  if (!data) { console.error(`Error: could not parse response (HTTP ${status}): ${bodyText.slice(0, 160)}`); process.exit(1); }
  const base = data.userBaseInfo && data.userBaseInfo.UserProfile && data.userBaseInfo.UserProfile.UserBase;
  console.log(JSON.stringify({
    userId: data.userId,
    isPrivate: data.userExtra && data.userExtra.isPrivate,
    isVerified: data.userExtra && data.userExtra.isVerified,
    bio: data.userExtra && data.userExtra.profileBio,
    region: base && base.Region && base.Region.Region,
    csrfToken: data['tt-csrf-token'] ? '(present)' : undefined,
  }, null, 2));
}

// ---------------------------------------------------------------------------
// Monday protocol -- unified inbox JSON (notifications + unread DMs)
// ---------------------------------------------------------------------------

function mondayFlagsFrom(flags) {
  const limit = parseInt(flags.limit || '50', 10);
  const date = flags.date || '7d';
  const m = String(date).match(/^(\d+)([dwh])$/);
  let oldest = Math.floor(Date.now() / 1000) - 7 * 86400;
  if (m) {
    const n = parseInt(m[1], 10);
    const mult = m[2] === 'w' ? 7 * 86400 : m[2] === 'h' ? 3600 : 86400;
    oldest = Math.floor(Date.now() / 1000) - n * mult;
  }
  return { limit, oldest };
}

const NOTICE_TYPE = {
  1: 'system', 2: 'like', 3: 'comment', 6: 'follow', 12: 'update', 31: 'comment',
  41: 'suggested-account', 43: 'like', 44: 'friend-joined', 45: 'mention',
  56: 'reply', 62: 'comment', 74: 'follow-request', 82: 'mention', 87: 'tag',
};

async function cmdMonday(positional, flags) {
  const { limit, oldest } = mondayFlagsFrom(flags);
  const items = [];

  // 1. Activity feed (notifications), group 500 = all activity.
  try {
    const groupList = JSON.stringify([{ count: Math.min(limit, 50), is_mark_read: 0, group: 500, max_time: 0, min_time: 0 }]);
    const d = await apiGet('/api/notice/multi/', { group_list: groupList, from_page: 'activity' });
    const notices = (d.notice_lists && d.notice_lists[0] && d.notice_lists[0].notice_list) || [];
    for (const n of notices) {
      if (n.create_time && n.create_time < oldest) continue;
      const label = NOTICE_TYPE[n.type] || `type-${n.type}`;
      const dg = n.digg || n.comment || n.follow || n.at || n.mention || {};
      const from = dg.from_user || (dg.user_list && dg.user_list[0]) || n.from_user || {};
      const handle = from.unique_id || from.uid || '';
      let bodyText = '';
      if (n.comment && n.comment.comment) bodyText = n.comment.comment.text || '';
      if (dg.content) bodyText = dg.content;
      items.push({
        source: 'tiktok',
        type: label === 'comment' || label === 'reply' ? 'comment' : (label === 'mention' || label === 'tag' ? 'mention' : 'notification'),
        id: `tiktok-notice-${n.nid_str || n.nid || n.create_time}`,
        title: `${label}${handle ? ' from @' + handle : ''}`,
        body: (bodyText || '').replace(/\n/g, ' ').slice(0, 300),
        url: 'https://www.tiktok.com/notifications',
        from: handle ? '@' + handle : '',
        date: n.create_time ? new Date(n.create_time * 1000).toISOString() : '',
        unread: !n.has_read,
        repo: null,
        number: null,
      });
    }
  } catch (e) {
    console.error(`[tiktok monday] WARNING: failed to fetch notifications: ${e && e.message ? e.message : e}`);
  }

  // 2. Unread DM conversations (rendered messages page).
  try {
    const convs = await readConversationsDom();
    for (const c of convs) {
      const hasUnread = c.unread && c.unread !== '0' && c.unread !== '';
      if (!hasUnread) continue;
      items.push({
        source: 'tiktok',
        type: 'dm',
        id: `tiktok-dm-${c.name}`.replace(/\s+/g, '-'),
        title: `Message from ${c.name}`,
        body: (c.preview || '').replace(/\n/g, ' ').slice(0, 300),
        url: 'https://www.tiktok.com/messages',
        from: c.name,
        date: c.time ? new Date(c.time).toISOString() : '',
        unread: true,
        repo: null,
        number: null,
      });
    }
  } catch (e) {
    console.error(`[tiktok monday] WARNING: failed to fetch messages: ${e && e.message ? e.message : e}`);
  }

  items.sort((a, b) => (b.date > a.date ? 1 : b.date < a.date ? -1 : 0));
  console.log(JSON.stringify(items.slice(0, limit), null, 2));
}

// ---------------------------------------------------------------------------
// Video seeing: transcript (captions) + filmstrip (frame contact sheet)
// (verb is `see`, not `watch` — `watch` is reserved for webhook/lick monitors
// like `gh pr watch` / `slack watch`.)
// ---------------------------------------------------------------------------
//
// An agent "sees" a TikTok by combining:
//   1. Auto-captions (WebVTT from video.subtitleInfos / claInfo.captionInfos)
//   2. A filmstrip of N frames grabbed from the in-page <video> via canvas
//
// Gotchas (learned the hard way, Aug 2026):
//   - playwright-cli `eval` top-level await (and eval-file async returning large
//     canvas payloads) can hang or come back as `{}` on TikTok tabs. Filmstrip
//     capture uses ONLY sync evals: set video.currentTime, sleep in the shell,
//     then canvas.drawImage + toDataURL.
//   - Caption VTT URLs are CDN-signed; fetch them from page context with
//     credentials so cookies/referer stay correct.
//   - Filmstrip needs the video open in a tab; transcript can use item/detail
//     when subtitleInfos are present, else falls back to the video page.

function sleep(ms) {
  return new Promise((r) => setTimeout(r, ms));
}

/** Accept a bare numeric id, a @user/video/<id> URL, or a /video/<id> URL. */
function parseVideoRef(raw) {
  const s = String(raw || '').trim();
  if (!s) return null;
  let m = s.match(/\/video\/(\d{5,})/);
  if (m) {
    const author = (s.match(/@([A-Za-z0-9._]+)/) || [])[1] || null;
    return { id: m[1], author };
  }
  m = s.match(/(\d{5,})/);
  if (m) return { id: m[1], author: null };
  return null;
}

function fmtTs(sec) {
  sec = Math.max(0, Number(sec) || 0);
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec - Math.floor(sec)) * 1000);
  const pad = (n, w) => String(n).padStart(w || 2, '0');
  if (h > 0) return pad(h) + ':' + pad(m) + ':' + pad(s) + '.' + pad(ms, 3);
  return pad(m) + ':' + pad(s) + '.' + pad(ms, 3);
}

function parseWebVtt(vtt) {
  const lines = String(vtt || '').replace(/^\uFEFF/, '').split(/\r?\n/);
  const cues = [];
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (!line.includes('-->')) continue;
    const parts = line.split('-->');
    if (parts.length < 2) continue;
    const startRaw = parts[0].trim().split(/\s+/)[0];
    const endRaw = parts[1].trim().split(/\s+/)[0];
    const toSec = (t) => {
      t = String(t).replace(',', '.');
      const p = t.split(':').map(Number);
      if (p.length === 3) return p[0] * 3600 + p[1] * 60 + p[2];
      if (p.length === 2) return p[0] * 60 + p[1];
      return Number(t) || 0;
    };
    const text = [];
    i++;
    while (i < lines.length && lines[i].trim() !== '') {
      if (!/^\d+$/.test(lines[i].trim())) text.push(lines[i].trim());
      i++;
    }
    const joined = text.join(' ').replace(/<[^>]+>/g, '').trim();
    if (!joined) continue;
    cues.push({ start: toSec(startRaw), end: toSec(endRaw), text: joined });
  }
  return cues;
}

/**
 * Run a JS expression in the TikTok tab via playwright-cli eval-file.
 * Expression should be a sync IIFE that returns a string or JSON-serializable
 * value. Avoid top-level await — it hangs on some TikTok tabs (Aug 2026).
 */
async function pwEval(tab, expression) {
  if (typeof fs.mkdirSync === 'function') {
    try { fs.mkdirSync(TMP_DIR, { recursive: true }); } catch (e) {}
  }
  const exprFile = TMP_DIR + '/eval-expr.js';
  const outFile = TMP_DIR + '/eval-out.txt';
  fs.writeFileSync(exprFile, expression);
  const r = await evalFileOnTab(tab, exprFile, outFile);
  let out = r.out;
  if (!out) {
    const err = ((r.failed || '') + ' ' + (r.stderr || '')).trim();
    throw new Error('empty eval result' + (err ? ': ' + err : ''));
  }
  if (out.endsWith('\n')) out = out.slice(0, -1);
  // Unwrap a single JSON-encoded string layer when present.
  if (out.charAt(0) === '"' && out.charAt(out.length - 1) === '"') {
    try { out = JSON.parse(out); } catch (e) {}
  }
  return out;
}

/** Like pwEval but for async page expressions (e.g. fetch). Returns parsed JSON if possible. */
async function pwEvalAsync(tab, asyncIifeSource) {
  if (typeof fs.mkdirSync === 'function') {
    try { fs.mkdirSync(TMP_DIR, { recursive: true }); } catch (e) {}
  }
  const exprFile = TMP_DIR + '/eval-async.js';
  const outFile = TMP_DIR + '/eval-async-out.txt';
  fs.writeFileSync(exprFile, asyncIifeSource);
  const r = await evalFileOnTab(tab, exprFile, outFile);
  let out = r.out;
  if (!out) {
    const err = ((r.failed || '') + ' ' + (r.stderr || '')).trim();
    throw new Error('empty async eval result' + (err ? ': ' + err : ''));
  }
  if (out.endsWith('\n')) out = out.slice(0, -1);
  if (out.charAt(0) === '"' && out.charAt(out.length - 1) === '"') {
    try { out = JSON.parse(out); } catch (e) {}
  }
  try { return JSON.parse(out); } catch (e) { return out; }
}

function extractCaptionsFromItem(item) {
  const video = (item && item.video) || {};
  const list = [];
  const seen = new Set();
  const push = (c) => {
    if (!c) return;
    const url = c.Url || c.url
      || (c.urlList && c.urlList[0])
      || (c.url_list && c.url_list[0]);
    if (!url || seen.has(url)) return;
    seen.add(url);
    list.push({
      url: url,
      language: c.LanguageCodeName || c.language || c.languageCode || '',
      format: c.Format || c.captionFormat || c.format || 'webvtt',
      source: c.Source || (c.isAutoGen ? 'ASR' : '') || '',
      isAuto: !!(c.isAutoGen || c.Source === 'ASR' || c.source === 'ASR'),
      variant: c.Version || c.variant || '',
      urlList: c.urlList || c.url_list || [url],
    });
  };
  const subs = video.subtitleInfos || video.subtitle_infos || [];
  for (let i = 0; i < subs.length; i++) push(subs[i]);
  const cla = video.claInfo || video.cla_info || (item && item.claInfo) || null;
  if (cla && cla.captionInfos) {
    for (let i = 0; i < cla.captionInfos.length; i++) push(cla.captionInfos[i]);
  }
  return list;
}

async function fetchItemStruct(id) {
  // Soft-fail variant of apiGet: on throttle / error return null so callers can
  // fall back to the open video page instead of killing the process.
  try {
    const { status, bodyText, data } = await signedRequest({
      url: '/api/item/detail/',
      query: { itemId: id },
    });
    if (!bodyText || !data) return null;
    if (data.status_code && data.status_code !== 0 && !data.itemInfo) return null;
    return (data.itemInfo && data.itemInfo.itemStruct) || null;
  } catch (e) {
    return null;
  }
}

async function ensureVideoTab(id, author) {
  let tab = await findTab();
  const cur = tab.url || '';
  if (cur.indexOf('/video/' + id) !== -1) {
    // Already on the right video, but it may be a background tab whose player
    // never loaded. Frame capture needs it visible.
    await focusTab(tab);
    return tab;
  }

  let uniqueId = author || null;
  if (!uniqueId) {
    try {
      const it = await fetchItemStruct(id);
      if (it && it.author) {
        uniqueId = it.author.uniqueId || it.author.unique_id || null;
      }
      ensureVideoTab._lastItem = it || null;
    } catch (e) {
      // throttle / API failure — continue with /@/video/id
    }
  }
  const url = uniqueId
    ? 'https://www.tiktok.com/@' + uniqueId + '/video/' + id
    : 'https://www.tiktok.com/@/video/' + id;

  try {
    await exec('playwright-cli goto ' + url + ' --tab=' + tab.targetId);
  } catch (e) {
    await exec('playwright-cli open ' + url);
  }
  // URL changed — drop cache and re-find.
  _tab = null;
  tab = await findTab();
  await focusTab(tab);

  for (let i = 0; i < 15; i++) {
    try {
      const raw = await pwEval(tab, "(() => {\n"
        + "  const v = [...document.querySelectorAll('video')].find(x => x.duration > 1 && x.videoWidth > 0);\n"
        + "  return JSON.stringify({\n"
        + "    ready: !!(v && v.readyState >= 1),\n"
        + "    duration: v ? v.duration : 0,\n"
        + "    w: v ? v.videoWidth : 0,\n"
        + "    h: v ? v.videoHeight : 0,\n"
        + "    href: location.href\n"
        + "  });\n"
        + "})()");
      const st = JSON.parse(raw);
      if (st.ready) return tab;
      if (st.href && st.href.indexOf('/video/' + id) !== -1 && i > 5 && st.duration > 0) return tab;
    } catch (e) {}
    await sleep(400);
  }
  return tab;
}

async function readItemFromPage(tab) {
  const raw = await pwEval(tab, "(() => {\n"
    + "  try {\n"
    + "    const el = document.getElementById('__UNIVERSAL_DATA_FOR_REHYDRATION__');\n"
    + "    if (!el) return JSON.stringify({ error: 'no-universal-data' });\n"
    + "    const scope = JSON.parse(el.textContent).__DEFAULT_SCOPE__ || {};\n"
    + "    let item = null;\n"
    + "    const keys = Object.keys(scope);\n"
    + "    for (let i = 0; i < keys.length; i++) {\n"
    + "      const v = scope[keys[i]];\n"
    + "      if (v && v.itemInfo && v.itemInfo.itemStruct) { item = v.itemInfo.itemStruct; break; }\n"
    + "      if (v && v.itemStruct) { item = v.itemStruct; break; }\n"
    + "    }\n"
    + "    if (!item) return JSON.stringify({ error: 'no-item', keys: keys });\n"
    + "    const video = item.video || {};\n"
    + "    const slim = {\n"
    + "      id: item.id || item.aweme_id,\n"
    + "      desc: item.desc || '',\n"
    + "      createTime: item.createTime || item.create_time,\n"
    + "      author: item.author ? {\n"
    + "        uniqueId: item.author.uniqueId || item.author.unique_id,\n"
    + "        nickname: item.author.nickname || item.author.nickName,\n"
    + "        secUid: item.author.secUid || item.author.sec_uid\n"
    + "      } : null,\n"
    + "      stats: item.statsV2 || item.stats || {},\n"
    + "      video: {\n"
    + "        duration: video.duration,\n"
    + "        width: video.width,\n"
    + "        height: video.height,\n"
    + "        ratio: video.ratio,\n"
    + "        subtitleInfos: video.subtitleInfos || video.subtitle_infos || [],\n"
    + "        claInfo: video.claInfo || video.cla_info || null\n"
    + "      }\n"
    + "    };\n"
    + "    return JSON.stringify(slim);\n"
    + "  } catch (e) {\n"
    + "    return JSON.stringify({ error: String(e) });\n"
    + "  }\n"
    + "})()");
  const data = JSON.parse(raw);
  if (data.error) throw new Error('page item: ' + data.error);
  return data;
}

async function fetchVttText(tab, urls) {
  const list = Array.isArray(urls) ? urls : [urls];
  const src = "(async () => {\n"
    + "  const urls = " + JSON.stringify(list) + ";\n"
    + "  let lastErr = '';\n"
    + "  for (let i = 0; i < urls.length; i++) {\n"
    + "    try {\n"
    + "      const r = await fetch(urls[i], { credentials: 'include' });\n"
    + "      const text = await r.text();\n"
    + "      if (r.ok && text && /WEBVTT/i.test(text)) {\n"
    + "        return JSON.stringify({ ok: true, status: r.status, text: text });\n"
    + "      }\n"
    + "      lastErr = 'HTTP ' + r.status + ' len=' + (text ? text.length : 0);\n"
    + "    } catch (e) { lastErr = String(e); }\n"
    + "  }\n"
    + "  return JSON.stringify({ ok: false, error: lastErr || 'fetch failed' });\n"
    + "})()";
  let parsed = await pwEvalAsync(tab, src);
  if (typeof parsed === 'string') {
    try { parsed = JSON.parse(parsed); } catch (e) {}
  }
  if (!parsed || !parsed.ok) {
    throw new Error('caption fetch failed: ' + ((parsed && parsed.error) || 'unknown'));
  }
  return parsed.text;
}

function videoUrlFor(ref, author) {
  const a = author || (ref && ref.author) || '';
  return 'https://www.tiktok.com/@' + a + '/video/' + ref.id;
}

// Caption CDN URLs are short-lived. A tab that has been open for a while still
// has them in its rehydration payload, but the CDN already rejects them, which
// surfaces as "caption fetch failed: TypeError: Failed to fetch" on a video that
// demonstrably HAS captions. Reload the page once and use the newly minted URLs.
// state = { tab, ref, item, cap } and is updated in place on a successful reload.
async function fetchCaptionVttWithReload(state, lang) {
  let lastErr = null;
  for (let attempt = 0; attempt < 2; attempt++) {
    if (attempt > 0) {
      const url = videoUrlFor(state.ref, authorOf(state.item));
      try {
        await exec('playwright-cli goto ' + url + ' --tab=' + state.tab.targetId);
      } catch (e) { /* fall through: the page may already be right */ }
      await focusTab(state.tab);
      await sleep(1500);
      let freshItem = null;
      try { freshItem = await readItemFromPage(state.tab); } catch (e) {}
      const caps = freshItem ? extractCaptionsFromItem(freshItem) : [];
      if (!caps.length) break;
      if (!state.item) state.item = freshItem;
      state.cap = pickCaption(caps, lang);
    }
    try {
      const urls = (state.cap.urlList && state.cap.urlList.length)
        ? state.cap.urlList : [state.cap.url];
      return await fetchVttText(state.tab, urls);
    } catch (e) { lastErr = e; }
  }
  throw lastErr || new Error('caption fetch failed: unknown');
}

function pickCaption(captions, lang) {
  if (!captions.length) return null;
  if (lang) {
    const want = String(lang).toLowerCase();
    for (let i = 0; i < captions.length; i++) {
      if ((captions[i].language || '').toLowerCase().indexOf(want) !== -1) return captions[i];
    }
  }
  for (let i = 0; i < captions.length; i++) {
    if (/eng/i.test(captions[i].language) && captions[i].isAuto) return captions[i];
  }
  for (let i = 0; i < captions.length; i++) {
    if (/eng/i.test(captions[i].language)) return captions[i];
  }
  for (let i = 0; i < captions.length; i++) {
    if (captions[i].isAuto) return captions[i];
  }
  return captions[0];
}

function authorOf(item) {
  if (!item || !item.author) return null;
  return item.author.uniqueId || item.author.unique_id || null;
}

async function cmdTranscript(args, flags) {
  const ref = parseVideoRef(args[0]);
  if (!ref) {
    console.error('Usage: tiktok transcript <videoId|url> [--lang=eng-US] [--out=path] [--json] [--raw]');
    process.exit(1);
  }
  const wantJson = !!flags.json;
  const wantRaw = !!(flags.raw || flags.vtt);
  const lang = flags.lang || flags.language || null;

  let item = null;
  let tab = null;
  item = await fetchItemStruct(ref.id);
  const apiFailed = !item;

  let captions = item ? extractCaptionsFromItem(item) : [];

  if (!captions.length) {
    tab = await ensureVideoTab(ref.id, ref.author || authorOf(item));
    const pageItem = await readItemFromPage(tab);
    if (!item) item = pageItem;
    captions = extractCaptionsFromItem(pageItem);
    if (!item.video) item.video = pageItem.video;
  }

  if (!captions.length) {
    console.error('No captions/subtitles available for video ' + ref.id
      + '. (TikTok only ships auto-captions on some videos.)');
    process.exit(2);
  }

  const cap = pickCaption(captions, lang);
  if (!tab) tab = await findTab();

  const tState = { tab: tab, ref: ref, item: item, cap: cap };
  let vtt;
  try {
    vtt = await fetchCaptionVttWithReload(tState, lang);
    if (tState.item) item = tState.item;
  } catch (e) {
    console.error('Failed to download captions: ' + (e.message || e));
    process.exit(1);
  }

  const cues = parseWebVtt(vtt);
  const meta = {
    id: String((item && item.id) || ref.id),
    author: authorOf(item) || ref.author || null,
    desc: ((item && item.desc) || '').replace(/\n/g, ' ').trim(),
    duration: (item && item.video && item.video.duration) || null,
    language: cap.language,
    source: cap.source || (cap.isAuto ? 'ASR' : 'unknown'),
    cueCount: cues.length,
  };

  if (flags.out) {
    const outPath = String(flags.out);
    if (wantRaw || /\.vtt$/i.test(outPath)) fs.writeFileSync(outPath, vtt);
    else if (wantJson || /\.json$/i.test(outPath)) {
      fs.writeFileSync(outPath, JSON.stringify(Object.assign({}, meta, { cues: cues }), null, 2));
    } else {
      const body = cues.map((c) => fmtTs(c.start) + '  ' + c.text).join('\n') + '\n';
      fs.writeFileSync(outPath, body);
    }
    console.error('wrote ' + outPath);
  }

  if (wantRaw) {
    process.stdout.write(vtt.endsWith('\n') ? vtt : vtt + '\n');
    return;
  }
  if (wantJson) {
    console.log(JSON.stringify(Object.assign({}, meta, { cues: cues }), null, 2));
    return;
  }

  console.log('Transcript for ' + meta.id + (meta.author ? ' @' + meta.author : ''));
  if (meta.desc) console.log('  ' + meta.desc.slice(0, 100));
  console.log('  language: ' + (meta.language || '?')
    + '  source: ' + meta.source
    + '  cues: ' + meta.cueCount
    + (meta.duration ? '  duration: ' + meta.duration + 's' : '')
    + (apiFailed ? '  (via page)' : ''));
  console.log('');
  for (let i = 0; i < cues.length; i++) {
    console.log(fmtTs(cues[i].start) + '  ' + cues[i].text);
  }
}

async function cmdFilmstrip(args, flags) {
  const ref = parseVideoRef(args[0]);
  if (!ref) {
    console.error('Usage: tiktok filmstrip <videoId|url> [--frames=8] [--width=160] [--out=path] [--seek-wait=700] [--json]');
    process.exit(1);
  }
  const nFrames = Math.max(1, Math.min(24, parseInt(flags.frames || flags.n || '8', 10) || 8));
  const thumbW = Math.max(64, Math.min(480, parseInt(flags.width || flags.w || '160', 10) || 160));
  const seekWait = Math.max(200, Math.min(3000, parseInt(flags['seek-wait'] || '700', 10) || 700));
  const outPath = String(flags.out || (TMP_DIR + '/filmstrip-' + ref.id + '.jpg'));
  const wantJson = !!flags.json;

  const tab = await ensureVideoTab(ref.id, ref.author);

  const PROBE_SRC = "(() => {\n"
    + "  const v = [...document.querySelectorAll('video')].find(x => x.duration > 1 && x.videoWidth > 0)\n"
    + "    || document.querySelector('video');\n"
    + "  if (!v) return JSON.stringify({ error: 'no-video-element' });\n"
    + "  return JSON.stringify({\n"
    + "    duration: v.duration,\n"
    + "    w: v.videoWidth,\n"
    + "    h: v.videoHeight,\n"
    + "    ready: v.readyState\n"
    + "  });\n"
    + "})()";

  // The player may still be initialising — a freshly opened tab (including one
  // adopted after a dead-session recovery) has no decoded video yet. Poll for up
  // to ~10s instead of failing on the first look.
  let probe = null;
  let probeErr = null;
  for (let attempt = 0; attempt < 20; attempt++) {
    try {
      probe = JSON.parse(await pwEval(tab, PROBE_SRC));
      probeErr = null;
    } catch (e) {
      probe = null;
      probeErr = e && e.message ? e.message : String(e);
    }
    if (probe && !probe.error && Number(probe.duration) > 0 && Number(probe.w) > 0) break;
    await sleep(500);
  }

  if (!probe) {
    console.error('Could not read <video> on the page: ' + (probeErr || 'unknown'));
    process.exit(1);
  }
  if (probe.error) {
    console.error('No playable <video> element found for ' + ref.id
      + '. Open the video on www.tiktok.com and retry.');
    process.exit(1);
  }

  const duration = Number(probe.duration) || 0;
  if (!(duration > 0)) {
    console.error('Video duration is still 0/NaN after ~10s — the player never initialised.');
    console.error('The tab may be showing a login wall or an age gate. Open the video manually and retry.');
    process.exit(1);
  }
  const thumbH = Math.round(thumbW * (probe.h || 16) / (probe.w || 9));

  await pwEval(tab, "(() => {\n"
    + "  const N = " + nFrames + ", tw = " + thumbW + ", th = " + thumbH + ";\n"
    + "  const c = document.createElement('canvas');\n"
    + "  c.width = tw * N; c.height = th;\n"
    + "  window.__ttStrip = { c: c, ctx: c.getContext('2d'), tw: tw, th: th, N: N, times: [] };\n"
    + "  return 'ok';\n"
    + "})()");

  const times = [];
  for (let i = 0; i < nFrames; i++) {
    const t = (duration * (i + 0.5)) / nFrames;
    times.push(Math.round(t * 10) / 10);
    const label = fmtTs(t).replace(/\.\d+$/, '');

    await pwEval(tab, "(() => {\n"
      + "  const v = [...document.querySelectorAll('video')].find(x => x.duration > 1)\n"
      + "    || document.querySelector('video');\n"
      + "  if (!v) return 'no-video';\n"
      + "  v.muted = true;\n"
      + "  try { v.pause(); } catch (e) {}\n"
      + "  v.currentTime = " + t + ";\n"
      + "  return 'seek:' + v.currentTime;\n"
      + "})()");
    await sleep(seekWait);

    await pwEval(tab, "(() => {\n"
      + "  const s = window.__ttStrip;\n"
      + "  const v = [...document.querySelectorAll('video')].find(x => x.duration > 1)\n"
      + "    || document.querySelector('video');\n"
      + "  if (!s || !v) return 'missing';\n"
      + "  const i = " + i + ";\n"
      + "  s.ctx.drawImage(v, 0, 0, v.videoWidth, v.videoHeight, i * s.tw, 0, s.tw, s.th);\n"
      + "  s.ctx.fillStyle = 'rgba(0,0,0,0.55)';\n"
      + "  s.ctx.fillRect(i * s.tw, s.th - 22, s.tw, 22);\n"
      + "  s.ctx.fillStyle = '#fff';\n"
      + "  s.ctx.font = 'bold 14px sans-serif';\n"
      + "  s.ctx.fillText(" + JSON.stringify(label) + ", i * s.tw + 8, s.th - 6);\n"
      + "  s.times[i] = " + t + ";\n"
      + "  return 'drew:' + i;\n"
      + "})()");
  }

  const dataUrl = await pwEval(tab, "(() => {\n"
    + "  const s = window.__ttStrip;\n"
    + "  if (!s) return '';\n"
    + "  return s.c.toDataURL('image/jpeg', 0.85);\n"
    + "})()");

  if (!dataUrl || String(dataUrl).indexOf('data:image') !== 0) {
    console.error('Filmstrip export failed (empty or non-image data URL).'
      + ' The canvas may be tainted or the player not ready.');
    process.exit(1);
  }
  const b64 = String(dataUrl).replace(/^data:image\/\w+;base64,/, '');
  const buf = Buffer.from(b64, 'base64');
  try {
    const slash = outPath.lastIndexOf('/');
    if (slash > 0 && typeof fs.mkdirSync === 'function') {
      fs.mkdirSync(outPath.slice(0, slash), { recursive: true });
    }
  } catch (e) {}
  fs.writeFileSync(outPath, buf);

  const result = {
    id: ref.id,
    out: outPath,
    bytes: buf.length,
    frames: nFrames,
    width: thumbW * nFrames,
    height: thumbH,
    thumbWidth: thumbW,
    thumbHeight: thumbH,
    duration: duration,
    times: times,
    videoWidth: probe.w,
    videoHeight: probe.h,
  };

  if (wantJson) {
    console.log(JSON.stringify(result, null, 2));
  } else {
    console.log('Filmstrip ' + ref.id);
    console.log('  frames:   ' + nFrames + ' @ ' + thumbW + 'x' + thumbH
      + '  (sheet ' + result.width + 'x' + result.height + ')');
    console.log('  duration: ' + duration.toFixed(1) + 's');
    console.log('  times:    ' + times.join(', '));
    console.log('  out:      ' + outPath + '  (' + buf.length + ' bytes)');
  }
  return result;
}

async function cmdSee(args, flags) {
  const ref = parseVideoRef(args[0]);
  if (!ref) {
    console.error('Usage: tiktok see <videoId|url> [--frames=8] [--width=160] [--lang=eng-US] [--dir=path] [--json]');
    console.error('  Opens the video, extracts transcript + filmstrip so an agent can "see" it.');
    process.exit(1);
  }
  const dir = String(flags.dir || (TMP_DIR + '/see-' + ref.id));
  if (typeof fs.mkdirSync === 'function') {
    try { fs.mkdirSync(dir, { recursive: true }); } catch (e) {}
  }

  const tab = await ensureVideoTab(ref.id, ref.author);
  let item = null;
  try {
    item = await readItemFromPage(tab);
  } catch (e) {
    try { item = await fetchItemStruct(ref.id); } catch (e2) {}
  }

  let transcript = null;
  let transcriptError = null;
  // 'none'  = the video genuinely ships no captions (an expected outcome)
  // 'fetch' = captions exist but the WebVTT download failed (an operational fault)
  let transcriptErrorKind = null;
  try {
    const captions = item ? extractCaptionsFromItem(item) : [];
    if (!captions.length) {
      const none = new Error('no captions on item');
      none.kind = 'none';
      throw none;
    }
    const lang = flags.lang || flags.language || null;
    const cap = pickCaption(captions, lang);
    const sState = { tab: tab, ref: ref, item: item, cap: cap };
    const vtt = await fetchCaptionVttWithReload(sState, lang);
    if (sState.item) item = sState.item;
    const cues = parseWebVtt(vtt);
    const vttPath = dir + '/captions.vtt';
    const txtPath = dir + '/transcript.txt';
    fs.writeFileSync(vttPath, vtt);
    fs.writeFileSync(txtPath, cues.map((c) => fmtTs(c.start) + '  ' + c.text).join('\n') + '\n');
    const usedCap = sState.cap || cap;
    transcript = {
      language: usedCap.language,
      source: usedCap.source || (usedCap.isAuto ? 'ASR' : 'unknown'),
      cueCount: cues.length,
      vtt: vttPath,
      text: txtPath,
      cues: cues,
    };
  } catch (e) {
    transcriptError = e && e.message ? e.message : String(e);
    transcriptErrorKind = (e && e.kind)
      || (/^caption fetch failed/.test(transcriptError) ? 'fetch' : 'error');
  }

  let filmstrip = null;
  let filmstripError = null;
  try {
    const fsFlags = Object.assign({}, flags, { out: dir + '/filmstrip.jpg' });
    const prevLog = console.log;
    const prevErr = console.error;
    if (flags.json) {
      console.log = function () {};
      console.error = function () {};
    }
    try {
      filmstrip = await cmdFilmstrip([ref.id], fsFlags);
    } finally {
      console.log = prevLog;
      console.error = prevErr;
    }
  } catch (e) {
    filmstripError = e && e.message ? e.message : String(e);
  }

  const author = authorOf(item);
  const summary = {
    id: ref.id,
    url: author
      ? 'https://www.tiktok.com/@' + author + '/video/' + ref.id
      : 'https://www.tiktok.com/@/video/' + ref.id,
    author: author,
    nickname: item && item.author ? (item.author.nickname || null) : null,
    desc: item ? (item.desc || '').replace(/\n/g, ' ').trim() : null,
    duration: (item && item.video && item.video.duration)
      || (filmstrip && filmstrip.duration) || null,
    stats: (item && item.stats) || null,
    dir: dir,
    transcript: transcript ? {
      language: transcript.language,
      source: transcript.source,
      cueCount: transcript.cueCount,
      vtt: transcript.vtt,
      text: transcript.text,
    } : null,
    transcriptError: transcriptError,
    transcriptErrorKind: transcriptErrorKind,
    filmstrip: filmstrip ? {
      out: filmstrip.out,
      frames: filmstrip.frames,
      width: filmstrip.width,
      height: filmstrip.height,
      times: filmstrip.times,
      bytes: filmstrip.bytes,
    } : null,
    filmstripError: filmstripError,
    cues: transcript ? transcript.cues : null,
  };

  try {
    fs.writeFileSync(dir + '/summary.json', JSON.stringify(summary, null, 2));
  } catch (e) {}

  // Exit contract, matching `transcript` and documented in SKILL.md:
  //   0 = every requested artefact was produced
  //   2 = the video genuinely has no captions (filmstrip may still be fine)
  //   1 = something failed that was supposed to work
  // Assigning `process.exitCode` does NOT stick in this runtime — only an
  // explicit process.exit() does — so the code is applied after the output is
  // printed, once there is nothing left to flush.
  const exitCode = (filmstripError
      || transcriptErrorKind === 'fetch'
      || transcriptErrorKind === 'error') ? 1
    : transcriptErrorKind === 'none' ? 2
      : 0;

  if (flags.json) {
    console.log(JSON.stringify(summary, null, 2));
    if (exitCode) process.exit(exitCode);
    return summary;
  }

  console.log('See ' + summary.id + (summary.author ? ' @' + summary.author : ''));
  if (summary.desc) console.log('  ' + summary.desc.slice(0, 120));
  if (summary.duration) console.log('  duration: ' + summary.duration + 's');
  if (summary.stats) {
    const s = summary.stats;
    console.log('  ▶ ' + num(s.playCount)
      + '  ❤ ' + num(s.diggCount)
      + '  💬 ' + num(s.commentCount)
      + '  ↪ ' + num(s.shareCount));
  }
  console.log('  dir: ' + dir);
  console.log('');
  if (transcript) {
    console.log('Transcript (' + (transcript.language || '?')
      + ', ' + transcript.source + ', ' + transcript.cueCount + ' cues):');
    console.log('  ' + transcript.text);
    console.log('');
    for (let i = 0; i < transcript.cues.length; i++) {
      console.log(fmtTs(transcript.cues[i].start) + '  ' + transcript.cues[i].text);
    }
    console.log('');
  } else {
    console.log('Transcript: unavailable (' + (transcriptError || 'unknown') + ')');
    console.log('');
  }
  if (filmstrip) {
    console.log('Filmstrip: ' + filmstrip.out);
    console.log('  ' + filmstrip.frames + ' frames, '
      + filmstrip.width + 'x' + filmstrip.height
      + ', times: ' + filmstrip.times.join(', '));
  } else {
    console.log('Filmstrip: unavailable (' + (filmstripError || 'unknown') + ')');
  }
  if (exitCode) process.exit(exitCode);
  return summary;
}

// ---------------------------------------------------------------------------
// Dispatch
// ---------------------------------------------------------------------------

const commands = {
  whoami: cmdWhoami,
  search: cmdSearch,
  video: cmdVideo,
  comments: cmdComments,
  'user-videos': cmdUserVideos,
  posted: cmdUserVideos,
  reposts: cmdReposts,
  liked: cmdLiked,
  favorites: cmdFavorites,
  notifications: cmdNotifications,
  notices: cmdNotifications,
  'notice-count': cmdNoticeCount,
  conversations: cmdConversations,
  messages: cmdConversations,
  'read-messages': cmdReadMessages,
  'send-message': cmdSendMessage,
  api: cmdApi,
  studio: cmdStudio,
  monday: cmdMonday,
  transcript: cmdTranscript,
  captions: cmdTranscript,
  filmstrip: cmdFilmstrip,
  frames: cmdFilmstrip,
  see: cmdSee,
};

function parseArgs(argv) {
  const flags = {};
  const positional = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const eq = a.indexOf('=');
      if (eq !== -1) flags[a.slice(2, eq)] = a.slice(eq + 1);
      else if (i + 1 < argv.length && !argv[i + 1].startsWith('--')) flags[a.slice(2)] = argv[++i];
      else flags[a.slice(2)] = true;
    } else positional.push(a);
  }
  return { flags, positional };
}

const rawArgs = process.argv.slice(2);
const [cmd, ...rest] = rawArgs;

if (!cmd || cmd === 'help' || cmd === '--help') {
  console.log('TikTok web API client — drive TikTok from the command line.\n');
  console.log('Requires a logged-in www.tiktok.com tab open in your browser.\n');
  console.log('Usage: tiktok <command> [args] [flags]\n');
  console.log('Account:');
  console.log('  whoami                                        Show the logged-in TikTok account\n');
  console.log('Search:');
  console.log('  search <query> [--type=general|video|user] [--count=N] [--cursor=N]');
  console.log('                                                Search TikTok (general = mixed feed)\n');
  console.log('Videos & stats:');
  console.log('  video <videoId>                               Full video detail + play/like/comment/share/save stats');
  console.log('  comments <videoId> [--count=N] [--cursor=N]   List comments on a video');
  console.log('  user-videos <secUid> [--count=N] [--cursor=N] List a user\'s posted videos (+stats). Alias: posted\n');
  console.log('Profile tabs (secUid optional — defaults to your own account):');
  console.log('  posted    [<secUid>] [--count=N] [--cursor=N]   Posted videos');
  console.log('  reposts   [<secUid>] [--count=N] [--cursor=N]   Reposted videos');
  console.log('  liked     [<secUid>] [--count=N] [--cursor=N]   Liked videos (usually self-only)');
  console.log('  favorites [<secUid>] [--count=N] [--cursor=N]   Favorited/bookmarked videos (self-only)\n');
  console.log('Notifications:');
  console.log('  notice-count                                  Unread notification counts by group');
  console.log('  notifications [--group=N] [--count=N] [--mark-read] [--cursor=<max_time>]');
  console.log('                                                Activity feed (group 500 = all). Alias: notices\n');
  console.log('Direct messages (rendered via the messages page):');
  console.log('  conversations                                 List DM conversations + previews. Alias: messages');
  console.log('  read-messages "<name>"                        Read the latest messages in a conversation');
  console.log('  send-message "<name>" "<text>"                Send a DM (best run with the TikTok tab focused)\n');
  console.log('Creator analytics (TikTok Studio):');
  console.log('  studio analytics [--range=7d|28d|60d|365d]    Views/likes/comments/shares/followers overview');
  console.log('  studio user                                   Studio creator profile info\n');
  console.log('Aggregation:');
  console.log('  monday [--limit=N] [--date=Nd]                Unified inbox JSON (notifications + unread DMs)\n');
  console.log('Escape hatch (like `gh api`):');
  console.log('  api <path> [--method=GET] [--query k=v ...] [--data \'<json>\'] [--bare] [--raw] [--include]');
  console.log('                                                Call any TikTok endpoint from the signed page context\n');

  console.log('See a video (transcript + filmstrip — one-shot, not a webhook watcher):');
  console.log('  transcript <videoId|url> [--lang=eng-US] [--out=path] [--json] [--raw]');
  console.log('                                                Pull auto-captions (WebVTT) as a timed transcript');
  console.log('                                                Aliases: captions');
  console.log('  filmstrip  <videoId|url> [--frames=8] [--width=160] [--out=path] [--seek-wait=700] [--json]');
  console.log('                                                Contact sheet of N frames from the in-page player');
  console.log('                                                Aliases: frames');
  console.log('  see        <videoId|url> [--frames=8] [--width=160] [--lang=eng-US] [--dir=path]');
  console.log('                                                [--seek-wait=700] [--json]');
  console.log('                                                Open video + transcript + filmstrip in one shot');
  console.log('                                                (not a webhook watcher — use transcript/filmstrip/see, never "watch")\n');
  console.log('Tip: get a secUid for user-videos via `tiktok search <name> --type=user`.');
  console.log('Tip: see/transcript/filmstrip accept a bare video id or a full @user/video/<id> URL.');
  process.exit(0);
}

if (!commands[cmd]) {
  console.error(`Unknown command: ${cmd}`);
  console.error('Run "tiktok help" for usage.');
  process.exit(1);
}

const { flags, positional } = parseArgs(rest);
await commands[cmd](positional, flags, rest);
